server/apps/io/dpa.py
server/requirements.txt

This PR is dependent on superdesk/superdesk-core#37

[SD-3394] fix parsing errors for DPA

---

client/app/scripts/superdesk-authoring/metadata/metadata.js
client/app/scripts/superdesk-authoring/metadata/views/metadata-dropdown.html
client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-authoring/views/header-info.html

feat(authoring): SD-3176 Returned genre field in authoring header

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/views/authoring-topbar.html
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-monitoring/monitoring.spec.js

[SD-3376] - On send, preview is now closed,
[SD-3434] - On duplicate, monitoring list is refreshed

[SD-3334] - Unlock button is no visible when sending item

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-workspace/workspace.js

fix(monitoring): SD-3428 Fixed empty monitoring list after item being closed

---

client/app/scripts/superdesk-archive/views/media-box-grid.html
client/app/scripts/superdesk-archive/views/preview.html
client/app/scripts/superdesk-highlights/highlights.js
client/app/scripts/superdesk-items-common/styles/media-archive.less

feat(preview): SD-3410 Improved grid view on search

---

client/app/scripts/superdesk-dashboard/grid/grid.js
client/app/scripts/superdesk-items-common/styles/media-archive.less
client/app/scripts/superdesk-planning/views/planning.html
client/app/scripts/superdesk-users/views/list.html
client/app/styles/less/layouts.less

[SD-3451] - Preview pane i planning and user settings can close

[SD-3006] - No more error in console on remove/replace widgets

---

client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/tests/sdDeskeditMacros-spec.js
client/spec/desks_management_spec.js
client/spec/helpers/desks.js

Resolves [SD-2543](https://dev.sourcefabric.org/browse/SD-2543).

Display macros under the Macros tab when creating a new desk, too

---

client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-monitoring/monitoring.spec.js
server/apps/duplication/archive_duplication.py
server/features/content_duplication.feature

(fix) Adding appropriate notification message for content:update event

---

client/app/scripts/superdesk-archive/directives.js
client/app/scripts/superdesk-archive/tests/archive_spec.js
client/app/scripts/superdesk-legal-archive/views/legal_archive.html
client/spec/helpers/monitoring.js
client/spec/monitoring_spec.js

[SD-1950](https://dev.sourcefabric.org/browse/SD-1950) - Links for related items 
[SD-3417](https://dev.sourcefabric.org/browse/SD-3417) - Layout issue is legal archive for grid/list tooltip

Fixed Issues

---

client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/editor.spec.js

fix(editor): Fixed spellchecker to be responsive during updating markup.

---

client/app/scripts/superdesk-authoring/widgets/widgets.js
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-workspace/workspace.js
client/spec/helpers/utils.js
client/spec/workspace_spec.js

feat(workspace): SD-3411 By using keyboard shortcuts, change the current showed view

---

server/apps/ldap/commands.py
server/apps/ldap/ldap.py
server/apps/ldap/tests.py

(fix) Fixing the duplicate user issue for LDAP Authentication

---

client/app/index.html

disable planning module not to confuse users
SD-3464

fix(planning): disable planning module

---

server/apps/io/dpa.py
server/apps/io/fixtures/IPTC7901_odd_charset.txt
server/apps/io/tests.py
server/apps/io/update_ingest_tests.py
server/apps/prepopulate/data_initialization/vocabularies.json
server/features/ingest.feature
server/features/steps/steps.py
server/requirements.txt

This PR is dependent on superdesk/superdesk-core#46

[SD-3386] map iptc subject to anpa category and vice-versa

---

client/app/scripts/superdesk-content-filters/styles/content-filters.less
client/app/scripts/superdesk-content-filters/views/production-test.html
client/app/scripts/superdesk-ingest/styles/settings.less

Modal-Body was not visible after PR #1275

[SD-3473] - Content filter test popup body is hidden

---

client/app/scripts/superdesk-content-filters/content-filters.js
client/app/scripts/superdesk-content-filters/views/manage-filters.html
client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/views/desk-config-modal.html
client/app/scripts/superdesk-ingest/module.js
client/app/scripts/superdesk-publish/publish.js
client/app/scripts/superdesk-publish/views/subscribers.html
client/app/scripts/superdesk-templates/templates.js
client/app/scripts/superdesk-users/users.js
client/app/scripts/superdesk-users/views/settings-privileges.html
client/app/scripts/superdesk-users/views/user-privileges.html
client/app/scripts/superdesk-vocabularies/vocabularies.js
client/app/scripts/superdesk/filters.js
client/app/scripts/superdesk/notification/tests/notification_spec.js
client/app/scripts/superdesk/tests/filters_spec.js
server/apps/content_filters/content_filter.py
server/apps/content_filters/filter_condition.py
server/apps/desks.py
server/apps/privilege.py
server/apps/rules/routing_rules.py
server/apps/rules/rule_sets.py
server/requirements.txt

[SD-3426](https://dev.sourcefabric.org/browse/SD-3426): Order the results by name alphabetically
Requires https://github.com/superdesk/superdesk-core/pull/49

[SD-3426] Order the results by name alphabetically:

---

client/app/scripts/superdesk-search/search.js
client/app/scripts/superdesk-search/views/item-search.html
client/spec/helpers/search.js
client/spec/search_spec.js

Resolves [SD-1961](https://dev.sourcefabric.org/browse/SD-1961)

(fix) [SD-1961] Disable the GO button if none of the repos are ticked

---

client/app/scripts/superdesk-archive/module.js
client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/widgets/widgets.js
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-packaging/packaging.js
client/app/scripts/superdesk-workspace/workspace.js
client/app/scripts/superdesk/keyboard/keyboard.js

SD-3413
Also fixed the commented issue for SD-3411 and SD-3412.

feat(monitoring): SD-3413 Added keyboard shortcuts for starting item actions

---

client/app/scripts/superdesk/directives/sdTypeahead.js

Resolves [SD-3390](https://dev.sourcefabric.org/browse/SD-3390) When cursor leaves the Dateline field it changes the value

(fix) [SD-3390] When cursor leaves the Dateline field it changes the value

---

client/app/scripts/superdesk-authoring/views/authoring.html
client/app/styles/less/layouts.less
client/spec/helpers/authoring.js
client/spec/send_spec.js

Resolves: [SD-3524](https://dev.sourcefabric.org/browse/SD-3524) Send-to panel not working when in full screen edit

(fix) [SD-3524] Send-to panel not working when in full screen edit

---

client/app/scripts/superdesk-users/tests/sdUserPrivileges_spec.js
client/app/scripts/superdesk-users/users.js
client/app/scripts/superdesk-users/views/user-privileges.html
client/spec/helpers/user_prefs.js
client/spec/users_spec.js

Resolves [SD-2548](https://dev.sourcefabric.org/browse/SD-2548).

Add Cancel button to the user priviliges settings form

---

client/app/scripts/superdesk-authoring/views/authoring-topbar.html

fix(authoring): SD-3486 Removed minimize button for locked items

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-workspace/content/content.js
client/spec/authoring_spec.js

feat(authoring): Added shortcuts for create, save, close, unlock.

---

docker/docker-compose-prebuilt.yml
scripts/docker-local-create-user.sh
scripts/docker-local-demo.sh

resolves https://dev.sourcefabric.org/browse/SD-2194

chore(docker): use prebuilt docker images for demo

---

client/app/scripts/superdesk-items-common/styles/media-archive.less
client/app/scripts/superdesk/editor/editor.js

fix(authoring): SD-3248 Fixed focus issue in slugline field on opening item for authoring

---

client/app/scripts/superdesk-users/styles/users.less
client/app/scripts/superdesk-users/tests/sdUserPreferences_spec.js
client/app/scripts/superdesk-users/users.js
client/app/scripts/superdesk-users/views/user-preferences.html
server/apps/archive/archive_media.py
server/apps/archive/common.py
server/apps/preferences.py
server/features/archive.feature

Resolves [SD-3531](https://dev.sourcefabric.org/browse/SD-3531)

(feat) [SD-3531] Set a default place in user profile

---

server/requirements.txt
server/settings.py

now it has to use `iptc` subject codes explicitly

chore(server): update superdesk-core

---

client/app/index.html

feat(responsive): Added viewport meta tags for initial scale on tablet and mobile devices

---

server/features/steps/steps.py
server/settings.py

Use new variable `BEHAVE_TESTS_FIXTURES_PATH` to define the behave tests fixtures folder.
This is useful for projects that use SD as library

Introduce new variable `BEHAVE_TESTS_FIXTURES_PATH`

---

server/features/ingest_provider.feature
server/requirements.txt

Requires: https://github.com/superdesk/superdesk-core/pull/62

(fix) [SD-2316] Adding Notifications when a channel is created/deleted.

---

client/app/scripts/superdesk-desks/styles/aggregate.less
client/app/scripts/superdesk-desks/views/aggregate-settings-configuration.html
client/app/scripts/superdesk-desks/views/aggregate-settings.html
client/app/styles/less/modals.less
client/spec/helpers/monitoring.js

fix(monitoring): SD-3584 Fixed monitoring widget responsive behavior

---

client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-authoring/views/authoring-topbar.html
client/app/scripts/superdesk-desks/views/task-status-items.html
client/app/scripts/superdesk-desks/views/user-role-items.html
client/app/scripts/superdesk-users/views/user-list-item.html
client/app/scripts/superdesk/directives/sdUserAvatar.js
client/app/styles/less/sf-additional.less
client/app/styles/less/variables.less

feat(authoring): SD-3471 Added user avatar in top header of locked items

---

client/app/scripts/superdesk-desks/styles/desks.less
client/app/styles/less/forms.less

- error message cut off fixed in edit desk modal
- added drop down arrow for select tag (firefox)

[SD-3567] - Firefox fixes

---

client/app/scripts/superdesk-archive/directives.js
client/app/scripts/superdesk-archive/views/media-box.html
client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-authoring/views/article-edit.html
server/apps/publish/content/common.py
server/apps/publish/content/tests.py
server/apps/publish/published_item.py

used for text items only, you can drop there pictures from any list

feat(associations): implement featured image field

---

client/app/scripts/superdesk-desks/aggregate-widget/configuration.html
client/app/scripts/superdesk-desks/views/aggregate-settings-configuration.html
client/app/styles/less/modals.less

fix(monitoring): SD-3612 Fixed monitoring widget responsive behavior

---

server/features/ingest_provider.feature
server/features/steps/steps.py
server/requirements.txt

Requires https://github.com/superdesk/superdesk-core/pull/66

(fix) [SD-3599] Disabled users should not get error notifications

---

server/apps/content_filters/content_filter.py
server/apps/content_filters/content_filter_tests.py

Change the action of not having a filter to pass content.

[SD-2201] No filter matches all articles

---

client/app/scripts/superdesk-authoring/comments/views/comments-widget.html
client/app/scripts/superdesk-dashboard/workspace-tasks/views/assignee-view.html
client/app/scripts/superdesk-dashboard/workspace-tasks/views/task-preview.html
client/app/scripts/superdesk-desks/styles/desks.less
client/app/scripts/superdesk-desks/views/desk-config-modal.html
client/app/scripts/superdesk-desks/views/user-select.html
client/app/scripts/superdesk-groups/styles/groups.less
client/app/scripts/superdesk-groups/views/groups-config-modal.html
client/app/scripts/superdesk-planning/views/assignee-box.html
client/app/scripts/superdesk-stream/views/activity-stream.html
client/app/scripts/superdesk-users/styles/users.less
client/app/scripts/superdesk-users/views/edit-form.html
client/app/scripts/superdesk-users/views/mentions-menu.html
client/app/scripts/superdesk/directives/sdUserAvatar.js
client/app/scripts/superdesk/menu/notifications/views/notifications.html
client/app/scripts/superdesk/menu/views/menu.html
client/app/styles/less/sf-additional.less

feat(avatars): SD-3613 Make user avatars consistent on every list

---

client/app/scripts/superdesk-desks/views/settings.html
client/app/scripts/superdesk-highlights/styles/highlights.less
client/app/scripts/superdesk-highlights/views/package_highlights_dropdown_directive.html
client/app/scripts/superdesk-workspace/workspace.js
client/app/scripts/superdesk/menu/styles/menu.less
client/app/styles/less/dropdowns.less

feat(monitoring): SD-3509 Added keyboard shortcuts for opening highlights list

---

.gitignore
client/app/scripts/superdesk-archive/controllers/list.js
client/app/scripts/superdesk-archive/directives.js
client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/tests/authoring_spec.js
client/app/scripts/superdesk-highlights/highlights.js
client/app/scripts/superdesk-highlights/views/highlights_title_directive.html
client/app/scripts/superdesk-monitoring/monitoring.js
server/apps/highlights/service.py
server/apps/highlights/service_tests.py

[SD-3121] - Highlight in monitoring and authoring is consistent

---

client/app/scripts/superdesk-users/styles/users.less

update(avatars): SD-3613 Updated avatar in profile page

---

client/app/scripts/superdesk-authoring/views/authoring-topbar.html
client/app/scripts/superdesk-workspace/content/content.js

On selecting template modal window closes

---

client/app/scripts/superdesk-search/search.js

[SD-2326] - On search scroll doesn't go up

---

client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-monitoring/views/monitoring-view.html
client/app/scripts/superdesk-workspace/workspace.js
client/spec/highlights_spec.js

Change desk on highlights switch to monitoring

---

client/app/scripts/superdesk-users/users.js
client/app/scripts/superdesk-users/views/user-preferences.html

Resolves [SD-3630](https://dev.sourcefabric.org/browse/SD-3630)

(fix) [SD-3630] "place" drop down list is empty in the user profile section

---

client/tasks/options/copy.js

when building client use fonts from repo

fix(client): copy fonts into dist folder

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/views/authoring-topbar.html
client/app/scripts/superdesk/editor/editor.js
client/spec/authoring_spec.js
client/spec/helpers/utils.js

fix(authoring): Fixed authoring shortcuts.

---

client/app/scripts/superdesk-desks/aggregate-widget/aggregate.js

update monitoring widget description

---

client/app/scripts/superdesk-users/users.js
client/app/scripts/superdesk/directives/sdUserAvatar.js

This also solves the following tickets:
SD-3631
SD-3651
SD-3652

[SD-3634] - User list, save and preview issues

---

client/app/scripts/superdesk-desks/aggregate.js
client/app/scripts/superdesk-desks/styles/aggregate.less
client/app/scripts/superdesk-desks/views/aggregate-settings.html
client/app/scripts/superdesk-items-common/styles/archive-filtering.less
client/app/scripts/superdesk-search/search.js
client/app/scripts/superdesk-search/views/save-search.html
client/app/scripts/superdesk-search/views/saved-searches.html
client/app/scripts/superdesk-search/views/search-facets.html
client/spec/helpers/monitoring.js
client/spec/helpers/search.js
client/spec/helpers/workspace.js
client/spec/monitoring_spec.js
client/spec/saved_search_spec.js
server/apps/archive/__init__.py
server/apps/archive/saved_searches.py
server/apps/prepopulate/app_prepopulate_data.json
server/apps/saved_searches/__init__.py
server/apps/saved_searches/saved_searches.py
server/features/saved_searches.feature
server/settings.py

[SD-3436] [SD-3596] Global saved searches

---

README.md

This adds some info which I had trouble finding as I worked on setting up an initial install.
Thanks!

Add the default username and password to the readme.

---

client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/views/stage-header.html
client/spec/dashboard_spec.js

Resolves: [SD-3678](https://dev.sourcefabric.org/browse/SD-3678)

(fix) [SD-3678] Output/Published stage doesn't work for monitoring widget

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/versioning/history/views/publish_queue.html
client/app/scripts/superdesk-authoring/views/article-edit.html
client/app/scripts/superdesk-monitoring/monitoring.js
client/spec/authoring_spec.js
client/spec/helpers/authoring.js
server/apps/archive/archive.py
server/apps/archive/common.py
server/apps/packages/takes_package_service.py
server/apps/prepopulate/app_prepopulate_data.json
server/apps/prepopulate/data_initialization/vocabularies.json
server/apps/publish/content/remove_tests.py
server/apps/publish/formatters/aap_bulletinbuilder_formatter.py
server/apps/publish/formatters/aap_bulletinbuilder_formatter_tests.py
server/apps/publish/formatters/aap_ipnews_formatter.py
server/apps/publish/formatters/aap_ipnews_formatter_test.py
server/apps/publish/formatters/aap_sms_formatter.py
server/apps/publish/formatters/aap_sms_formatter_test.py
server/apps/publish/formatters/anpa_formatter.py
server/apps/publish/formatters/anpa_formatter_test.py
server/apps/publish/formatters/newsml_g2_formatter.py
server/features/packages.feature
server/features/steps/fixtures/vocabularies.json
server/requirements.txt

Resolves: [SD-3628](https://dev.sourcefabric.org/browse/SD-3628)
Requires: https://github.com/superdesk/superdesk-core/pull/77

(feat) [SD-3628] Add footer for public service announcements

---

client/app/scripts/superdesk-archive/related-item-widget/relatedItem.js
client/app/scripts/superdesk/itemList/itemList.js
client/app/scripts/superdesk/itemList/itemList_spec.js
server/apps/prepopulate/app_prepopulate.py
server/requirements.txt
server/settings.py

This PR is dependent on [CORE-PR](https://github.com/superdesk/superdesk-core/pull/80)
This PR requires following command:
`python manage.py app:rebuild_elastic_index`
Or
Drop the Superdesk Index and Stop-Start the backend and it should create new empty Superdesk index.
Then run the following commands.
`python manage.py app:index_from_mongo --from ingest`
`python manage.py app:index_from_mongo --from archive`
`python manage.py app:index_from_mongo --from published`

(feat) [SD-3626] Modified the related item widget based on the pharse prefix query.

---

client/app/scripts/superdesk/notification/notification.js
server/features/vocabularies.feature
server/requirements.txt

Resolves: [SD-3650](https://dev.sourcefabric.org/browse/SD-3650)
Requires: https://github.com/superdesk/superdesk-core/pull/81 and https://github.com/superdesk/superdesk/pull/1391

(imp) [SD-3650] Page refreshing is required for vocabulary changes to take effect

---

server/features/amazons3.feature
server/features/auth.feature
server/features/environment.py
server/features/steps/steps.py
server/requirements.txt

If 'AMAZON_CONTAINER_NAME' is not defined the behave test will be
skipped.

chore(amazons3): Add behave test for arhive with Amazon S3 storage

---

client/app/scripts/superdesk-templates/templates.js
client/app/scripts/superdesk-templates/views/templates.html

Fixed content templates issues

---

client/app/scripts/superdesk-desks/desks.js
client/spec/desks_spec.js
client/spec/helpers/desks.js

Fix covers SD-3676: Update is not initiated when adding/removing a stage to/from a desk

[sd-3666]-UI: Newly created desk doesn't reflect the stage count

---

client/app/scripts/superdesk-archive/views/media-box-list.html
client/app/scripts/superdesk-highlights/highlights.js
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk/activity/views/activity-item.html
client/app/styles/less/dropdowns.less

SD-3509
Please fill free to give some tips for code improvement! I couldn't find better way to implement this.

feat(shortcuts): SD-3509 Added ability to open highlights list and mark some item with keyboard

---

client/app/scripts/superdesk-users/styles/change-avatar.less
client/app/scripts/superdesk-users/users.js
client/app/scripts/superdesk-users/views/change-avatar.html
client/app/scripts/superdesk/upload/crop-directive.js

fix: add error messages and notification info regarding min size.

---

client/app/scripts/superdesk-archive/module.js
client/app/scripts/superdesk-archive/related-item-widget/relatedItem.js
client/app/scripts/superdesk-archive/views/media-box-grid.html
client/app/scripts/superdesk-archive/views/preview.html
client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/tests/authoring_spec.js
client/app/scripts/superdesk-workspace/content/views/sd-content-create.html
client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/views/editor.html

Add preformatted removed

---

client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/styles/desks.less
client/app/scripts/superdesk-desks/views/desk-config-modal.html
server/apps/archive/archive.py
server/apps/desks.py
server/apps/tasks.py
server/features/content_move.feature
server/features/desks.feature

it adds metadata to desk and populate it on item when sending it to desk or creating it there

Feat desk metadata

---

client/app/scripts/superdesk-archive/module.js

fix(shortcut): Added new keyboard shortcut for "New Take" action

---

server/apps/publish/content/correct.py
server/apps/publish/content/kill.py
server/features/content_publish.feature
server/features/steps/steps.py

it creates a new version so versioncreated should get updated

fix(publish): update versioncreated on kill/correct

---

client/app/scripts/superdesk-search/search.js
client/app/scripts/superdesk-search/views/item-search.html
server/apps/saved_searches/__init__.py
server/apps/saved_searches/saved_searches.py
server/features/saved_searches.feature
server/features/steps/steps.py

[SD-2955]
[SD-3261]
This PR also changes the way the search is saved so when it is merged please remove all the existing saved searches from the system.

Search and Saved search fixes

---

client/app/scripts/translations.js

fix(authoring): rename slugline to keyword

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/views/article-edit.html
client/app/scripts/superdesk-authoring/views/header-info.html
client/app/scripts/superdesk-workspace/content/content.js
client/app/scripts/superdesk-workspace/content/content.spec.js
client/app/scripts/superdesk-workspace/content/views/sd-content-create.html
server/apps/content_types/__init__.py
server/apps/content_types/content_types.py
server/apps/prepopulate/app_initialize.py
server/apps/prepopulate/data_initialization/content_types.json
server/apps/validate/validate.py
server/features/validate.feature
server/settings.py

it can be used for validation if exists
@eozan I've only added fields to schema that should be validated, not sure if we should hide everything else or how you want to use it?

feat(content_types): introduce content types

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/views/change-image.html
client/app/scripts/superdesk-authoring/views/item-association.html
client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/views/block-embed.html
client/app/scripts/superdesk/upload/image-crop-directive.js
server/apps/picture_crop/__init__.py
server/apps/publish/content/common.py
server/features/content_crop.feature
server/features/steps/steps.py
server/settings.py

it can create a new crop using given picture item and crop specs

feat(picture_crop): add picture crop resource

---

client/app/scripts/superdesk-authoring/metadata/metadata.js
client/app/scripts/superdesk-authoring/metadata/views/metadata-dropdown.html
client/app/scripts/superdesk-authoring/metadata/views/metadata-terms.html
client/app/scripts/superdesk-highlights/highlights.js
client/app/scripts/superdesk/ui/ui.js

feat(authoring): SD-3698 Improved usability of Subject and Category popup

---

client/app/scripts/superdesk-workspace/content/content.js
client/app/scripts/superdesk-workspace/content/content.spec.js
server/apps/content_types/content_types.py
server/apps/prepopulate/data_initialization/content_types.json

there is no way to remove an item via initialize_data command,
so adding a param - enabled - and use it for filtering in ui.

fix(content_types): rename article to story

---

client/app/scripts/superdesk-workspace/content/content.js
client/app/scripts/superdesk-workspace/content/content.spec.js
server/apps/validate/validate.py
server/features/validate.feature

+ fixing new item not being attached to current desk

fix(validate): allow picture type items in schema

---

client/app/scripts/superdesk/directives/sdUserAvatar.js

fix(avatars): SD-3709 Fixed issue with avatars on users page

---

client/app/scripts/superdesk-publish/views/subscribers.html
client/app/scripts/superdesk/activity/activity-list-directive.js

User buttons refresh on action

---

client/app/index.html
client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-authoring/views/item-association.html
client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/styles.less
client/app/scripts/superdesk/editor/views/block-embed.html
client/app/scripts/superdesk/editor/views/editor.html
client/bower.json
client/test-main.js

new editor: editable caption for images SDPA-44

---

client/app/scripts/superdesk-authoring/views/item-association.html
server/apps/pa_img/pa_img_datalayer.py
server/requirements.txt

use decription_text for picture captions

chore(server): update core

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/views/authoring-topbar.html

Resolves: [SD-3728](https://dev.sourcefabric.org/browse/SD-3728), [SD-3345](https://dev.sourcefabric.org/browse/SD-3345)

(fix) [SD-3728] Unlock button is missing in avatar window for published items

---

client/app/scripts/superdesk-legal-archive/legal_archive.js
client/app/scripts/superdesk-legal-archive/views/legal_archive.html
client/spec/legal_archive_spec.js

On open preview closes in legal archive

---

client/app/scripts/superdesk-search/search.js

fix(search): SD-3610 Fixed opening item from ctrl+0 menu

---

server/apps/publish/content/common.py
server/features/content_publish.feature

The problem was attempting to append the body in the save and publish to a null body in the digital package item.
@mugurrus This is the task that @sivakuna-aap linked to yours, it might be worth merging just for the test. If you want to take care of t yourself just let me know and I'll close it.

Extra error message when publishing with body missing

---

client/app/scripts/superdesk-highlights/highlights.js
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-monitoring/views/monitoring-view.html

Added items count in highlights header

---

client/app/scripts/superdesk-search/views/multi-action-bar.html

On multiselect create package button visible

---

client/app/scripts/superdesk-desks/views/slugline-items.html
server/apps/desks.py
server/features/desks.feature

Following feedback from Vince, times have been added and Domestic and Rest of World have been grouped seperatly

[SD-3654] Add times to sluglines report

---

client/app/scripts/superdesk-archive/views/media-box-list.html
client/app/scripts/superdesk-authoring/styles/themes.less
client/app/scripts/superdesk-content-filters/views/production-test-view.html
client/app/scripts/superdesk-items-common/styles/media-archive.less
client/app/scripts/superdesk-search/search.js
client/app/styles/less/labels.less
client/app/styles/less/sf-additional.less
client/app/styles/less/variables.less

- state labels
- desk label (list item in search)
- text styling for locked items

(fix) style fixes

---

client/app/scripts/superdesk-authoring/tests/authoring_spec.js
client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/editor.spec.js
client/tasks/options/template.js

configuration implemented as grunt option. i.e: 'disableEditorToolbar'.
usage: --disableEditorToolbar = true, in grunt command, will disable editor toolbar

[sd-3170]-Make the floating, green toolbar in the editor configurable

---

server/apps/archive/archive_spike.py
server/apps/legal_archive/__init__.py
server/apps/legal_archive/commands.py
server/apps/legal_archive/service.py
server/apps/publish/content/common.py
server/apps/publish/content/remove_tests.py
server/apps/publish/published_item.py
server/features/content_publish.feature
server/features/package_publish.feature
server/features/steps/steps.py
server/scripts/start_e2e_server.sh
server/settings.py

*Change includes:*
- Moving an item into legal archive on publish actions (except scheduling an item). 
- For schedule publish, the moving into legal archive will be handled by the async publishing PR (@mugurrus).
- Do we need a `Date` parameter for ImportLegalPublishQueueCommand??

[SD-2564] [SD-3493] Import document to legal archive after publish actions.

---

client/app/scripts/superdesk-search/search.js
client/app/scripts/superdesk-search/views/multi-action-bar.html

Fixed add to package for killed items

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-authoring/styles/themes.less
client/app/scripts/superdesk-authoring/views/authoring-header.html
client/app/scripts/superdesk-authoring/views/authoring.html
client/app/scripts/superdesk-authoring/widgets/widgets.js

feat(authoring): SD-3294 Created sticky header on authoring screen

---

client/app/scripts/superdesk-templates/templates.js
client/app/scripts/superdesk-templates/templates.spec.js
client/app/scripts/superdesk-templates/views/create-template.html

- fix save as desk template
- let only user with privileges create desk templates

template fixes

---

client/app/scripts/superdesk-search/search.js
client/app/scripts/superdesk-search/views/save-search.html

Resolves: [SD-3763](https://dev.sourcefabric.org/browse/SD-3763)

(fix) [SD-3763] 'Save as' option in saving a search should have the search name and description emtpy prior to saving

---

client/app/scripts/superdesk-content-filters/content-filters.js
client/app/scripts/superdesk-content-filters/views/manage-filter-conditions.html
client/app/scripts/superdesk/filters.js

Resolves [SD-3729](https://dev.sourcefabric.org/browse/SD-3729)

(fix) [SD-3729] Filter condition value does not show the actual readable value

---

client/app/scripts/superdesk-templates/templates.js
client/app/scripts/superdesk-templates/templates.spec.js
client/app/scripts/superdesk-templates/views/templates.html

fix(templates): filter out private templates in settings

---

client/app/scripts/superdesk-content-filters/content-filters.js
client/app/scripts/superdesk-content-filters/views/manage-filter-conditions.html

Resolves: [SD-3279](https://dev.sourcefabric.org/browse/SD-3729)
1. Fixing the swift appearance of angular script while loading conditions. 
2. Also, clearing the value from the condition when the field is changed

(fix) [SD-3729] Issues in Filter Conditions

---

client/app/scripts/superdesk-desks/desks.js

Monitoring widget refreshes on item update

---

client/app/scripts/superdesk-archive/directives.js
client/app/scripts/superdesk-authoring/authoring.js
client/app/styles/less/layouts.less

On unlock from preview item is unlocked in authoring

---

client/app/scripts/superdesk-monitoring/monitoring.js

On desk change selected items are reseted

---

client/app/scripts/superdesk-monitoring/aggregate.js
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-search/search.js

Disabled spiking locked item in multiselect

---

server/apps/archive/common.py

This requires drop/recreating of elasticsearch index for company codes. It would be best to merge this PR and [Expiry Related PR](https://github.com/superdesk/superdesk/pull/1531) together and perform the steps as mentioned in the Expiry Related PR.

(fix) Modified company codes schema for elastic search.

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/views/send-item.html
client/app/scripts/superdesk-ingest/ingest.spec.js
client/app/scripts/superdesk-ingest/module.js
client/app/scripts/superdesk-search/views/multi-action-bar.html

feat(monitoring): Added send to functionality for multiple items on monitoring view

---

client/app/docs/styles/main.less
client/app/docs/views/main.html

Icon font specification added to the docs page

Docs page update

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/tests/authoring_spec.js
client/app/scripts/superdesk-authoring/views/authoring-topbar.html

[sd-3804] Remove desk/stage link to workspace content at top of edit view

---

client/app/scripts/superdesk-authoring/metadata/metadata.js
client/app/scripts/superdesk-content-filters/content-filters.js
client/app/scripts/superdesk-ingest/module.js
client/app/scripts/superdesk-ingest/views/settings/ingest-sources-content.html
client/app/scripts/superdesk-publish/publish.js

[SD-3351](https://dev.sourcefabric.org/browse/SD-3351) Some (additional) lists that have to be ordered alphabetically
[SD-3861](https://dev.sourcefabric.org/browse/SD-3861) Make the "genre" list alphabetical

(fix) [SD-3351] and [SD-3861]

---

server/apps/archived/archived.py
server/apps/publish/__init__.py
server/apps/publish/commands.py
server/apps/publish/published_item.py
server/features/archived_kill.feature
server/features/steps/steps.py
server/settings.py

Improvements to the process:
1. Copying the latest version to archive and archive_versions collections. This enables to have display allowed actions in the client.
2. Removed the published expiry job as this is redundant and expiry of items is taken care by the archive expiry.

(imp) [SD-3035] Killing from Dusty Archive

---

server/apps/io/feeding_services/reuters.py
server/apps/io/update_ingest_tests.py
server/features/steps/steps.py
server/requirements.txt

This is dependent on superdesk/superdesk-core#118

fix(reuters image ingestion) token was not passed on rendition requests

---

client/app/scripts/superdesk-authoring/views/authoring-topbar.html
client/app/scripts/superdesk-search/search.js

imp(global search): SD-3735 UI Improvement for saved search and eliminated minimize button

---

client/app/scripts/superdesk-ingest/module.js
client/app/scripts/superdesk-monitoring/styles/aggregate.less
client/app/scripts/superdesk-monitoring/views/monitoring-group-header.html
client/app/scripts/superdesk-monitoring/views/monitoring-group.html
client/app/scripts/superdesk-monitoring/views/monitoring-view.html
client/spec/monitoring_spec.js

Fetch reset fixed and links in monitoring and spike monitoring removed

---

client/app/scripts/superdesk/menu/notifications/notifications.js
client/app/scripts/superdesk/menu/notifications/notifications_spec.js
server/apps/desks.py
server/requirements.txt

Depends on 
https://github.com/superdesk/superdesk-core/pull/122
https://github.com/superdesk/superdesk-core/pull/123

(fix) [SD-3866] there is no prompting re-login notification received for the newly added user to a desk(s)

---

server/app.py
server/apps/legal_archive/commands.py
server/apps/prepopulate/app_initialize.py
server/apps/prepopulate/app_scaffold_data.py
server/apps/publish/content/common.py
server/apps/publish/content/kill.py
server/features/__init__.py
server/logging_config.yml
server/requirements.txt
server/settings.py
server/worker.py
server/ws.py

This depends on  [PR 124](https://github.com/superdesk/superdesk-core/pull/124).
The issue was handlers were not set for `INFO`\`DEBUG` level log record for the apps, macros packages and didn't want to set the handlers again at the apps, macros packages level. Hence, modified the logging functionality to used .yml file.

(fix)Modified logging so that is controlled via .yml file.

---

client/app/scripts/superdesk-search/search.js
client/app/scripts/superdesk-search/views/multi-action-bar.html

Resolves [SD-3890](https://dev.sourcefabric.org/browse/SD-3890)

(fix) [SD-3890] Highlight button should not disappear from top panel when a published item is selected

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/workqueue/workqueue.js

feat(authoring): SD-3606 Show unlocking info for minimized items

---

client/app/scripts/superdesk-authoring/editor/find-replace.js
client/app/scripts/superdesk-authoring/editor/views/find-replace.html
client/app/scripts/superdesk/editor/editor.js

feat(authoring): SD-2512 Implemented case sensitive/insensitive Find Replace operation

---

client/app/scripts/superdesk-authoring/views/header-info.html

fix(authoring): Fixed order of service, topic and keyword fields.

---

client/app/scripts/superdesk-authoring/workqueue/workqueue.js

fix(highlights): Keep the highlight package on edit mode when a contained item is closed (SD-3580)

---

client/app/scripts/superdesk/editor/editor.js

Fixed undo redo and some other problems with editor and spellchecker.
SD-3570

Text editor undo/redo fixed

---

client/app/scripts/superdesk-authoring/workqueue/workqueue.js
client/app/scripts/superdesk-highlights/styles/highlights.less
client/app/scripts/superdesk-highlights/views/highlights_title_directive.html
client/app/scripts/superdesk-highlights/views/package_highlights_dropdown_directive.html
client/app/scripts/superdesk-highlights/views/settings.html
client/app/styles/less/sf-additional.less

fix(workqueue) SD-3606 Show unlocking info for minimized items

---

client/app/scripts/superdesk-archive/module.js
client/app/scripts/superdesk-archive/tests/archive_spec.js
client/app/scripts/superdesk-search/search.js

Creating new item in personal workspace with selected desk fixed

---

client/app/scripts/superdesk-authoring/workqueue/workqueue.js

fix(workqueue): SD-3775 Update workqueue headline on item save

---

client/app/index.html
client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/editor.spec.js
client/bower.json
client/tasks/options/template.js
client/test-main.js
docker/common.yml
docker/start.sh

Editor: Use iframely instead of embedly

---

client/app/scripts/superdesk-monitoring/monitoring.js

On personal workspace copy list is refreshed

---

client/app/scripts/superdesk/ui/ui.js

fix(authoring): SD-3504 Fixed focus issue on Firefox

---

client/app/scripts/superdesk-monitoring/monitoring.js

fix(monitoring): Fixed displaying spinner when not scrolling.

---

client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-items-common/styles/archive-preview.less

Added transition effects on preview and authoring headers

(feat) Transition effects on Header info

---

client/app/scripts/superdesk-workspace/content/content.js
client/app/scripts/superdesk-workspace/content/views/sd-content-create.html

On creating item from templates, templates list is refreshed

---

server/apps/archive/commands.py
server/apps/archive/common.py
server/features/archive.feature
server/features/steps/steps.py
server/features/tasks.feature

Also added the option on behave tests to specify that a field should not be present in response.

fix(personal): Items created in personal workspace should not have expiry field present(SD-3877)

---

client/app/scripts/superdesk-templates/templates.js
client/app/scripts/superdesk-workspace/content/content.js

Saving template with spaces in headers trims spaces

---

client/app/scripts/superdesk-monitoring/monitoring.js

On firefox scroll fixed

---

client/app/index.html
client/bower.json

After this, bower update is needed.
Requested by @fritzSF , for new and fancy animations! :)

feat(ng-animate): Added support for angular-animate library

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-authoring/views/item-association.html

fix(authoring): Implemented removing associated images.

---

client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-authoring/styles/themes.less

Chrome issue shown in the video example is fixed

(fix) [SD-3942] Chrome Slow + Unresponsive Script Error in FF is back

---

client/app/scripts/superdesk-authoring/editor/find-replace.js
client/app/scripts/superdesk-authoring/editor/views/find-replace.html
client/app/scripts/superdesk-authoring/versioning/history/history.js
client/app/scripts/superdesk-authoring/versioning/history/history.less
client/app/scripts/superdesk-authoring/versioning/history/views/history.html
client/app/scripts/superdesk-authoring/versioning/versions/versions.js
client/app/scripts/superdesk-authoring/versioning/versions/views/versions.html
client/app/styles/less/sf-additional.less

Also, disabled restore function in versioning.
SD-3499

fix(authoring): SD-3499 Disabled find&replace for read-only items

---

client/app/scripts/superdesk-legal-archive/views/legal_archive.html
client/app/scripts/superdesk-search/views/item-search.html
client/app/scripts/superdesk-search/views/search.html
client/app/scripts/superdesk/ui/ui.js
client/app/scripts/superdesk/ui/views/sd-datepicker.html
client/app/styles/less/layouts.less

fix(legal archive / search): SD-3881 Fixed pressing enter effects other fields

---

client/app/scripts/superdesk-authoring/views/authoring-topbar.html
client/app/scripts/superdesk-highlights/highlights.js
client/app/scripts/superdesk-highlights/styles/highlights.less
client/app/scripts/superdesk-highlights/views/highlights_title_directive.html
client/app/scripts/superdesk/ui/ui.js

Highlight on/off on mouse over
SD-3928

feat(highlights): SD-3928 Highlights dropdown position smarter

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-highlights/styles/highlights.less

feat(authoring): SD-3944 Added item based loader

---

client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk/editor/editor.js

Text editor fixed

---

client/app/scripts/superdesk-authoring/styles/themes.less
client/app/scripts/superdesk-authoring/views/article-edit.html
client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/styles.less
client/app/scripts/superdesk/editor/views/block-text.html

Tasks SDPA-168 and SDPA-176 (content editor improvements):
- field labels always visible, changed color
- placeholders added to the content fields

Pa poc editor fix

---

client/app/scripts/superdesk/directives/sdTypeahead.js
client/app/scripts/superdesk/views/sdTypeahead.html
client/protractor-conf-base.js
client/spec/authoring_spec.js
client/spec/helpers/authoring.js
client/spec/monitoring_spec.js
client/spec/publishing_spec.js

fix(editor): Added autofocus to input in typeahead dropdowns.

---

client/app/scripts/superdesk/editor/editor.js

feat(editor): Added custom playbuzz embed.

---

client/app/scripts/superdesk-dashboard/workspace-tasks/tasks.js

fix(master desk): SD-3843 Corrected items shown in working stage

---

client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-authoring/views/article-edit.html
client/app/scripts/superdesk/editor/views/add-embed.html

SDPA-111 Fix placeholder text.

---

client/app/scripts/superdesk-archive/views/media-box-grid.html

replacing image slug with title in thumbnail view.

SDPA-138 Display image title in thumbnail view.

---

client/app/scripts/superdesk/editor/editor.js
client/spec/authoring_spec.js

…ctionable text when killing an item

[sd-3917] - (fix) - I should not be able to Ctrl-z to the original, actionable text when killing an item

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/metadata/metadata.js
client/app/scripts/superdesk-authoring/metadata/views/metadata-terms.html
client/app/scripts/superdesk-authoring/views/header-info.html
server/apps/prepopulate/data_initialization/vocabularies.json
server/features/vocabularies.feature

adding additional vocabularies which are displayed according to selected service (category)

feat(cvs): show cvs for selected service

---

server/requirements.txt

it enables service/priority fields in vocabularies

fix(server): update server core

---

server/gunicorn_config.py
server/requirements.txt

it supports new params in access log which makes it more readable

chore(server): update gunicorn

---

server/apps/prepopulate/data_initialization/pa/vocabularies.json
server/apps/prepopulate/data_initialization/vocabularies.json

Pushing the PA cv to the pa directory

Moving PA vocabularies to the right directory

---

.travis.yml
server/aap_mm/__init__.py
server/aap_mm/aap_mm_datalayer.py
server/aap_mm/resource.py
server/aap_mm/service.py
server/dev-requirements.txt
server/features/aap_mm.feature
server/features/environment.py
server/features/steps/__init__.py
server/features/steps/steps.py
server/requirements.txt

This depends on  https://github.com/superdesk/superdesk-core/pull/142

(fix) Fixing the aap multimedia behave test after merge.

---

client/app/scripts/superdesk-archive/directives.js

fix(search): Fixed credit/source.

---

server/apps/prepopulate/data_initialization/pa/vocabularies.json

Controlled vocabularies in the prepopulation scripts have been updated to add PA namespaces to qcode values.

Sets PA namespaces on qcode values

---

client/package.json

SD-3070
SD-3853 - I think this is now finally fixed
SD-3917 - Small fix

Item actions menu is closed on scroll

---

client/app/scripts/superdesk-items-common/styles/media-archive.less

UI improvement - small css fix

Fix for sticky labels in the list

---

client/app/scripts/superdesk-authoring/styles/themes.less
client/app/scripts/superdesk/editor/add-embed.ctrl.js
client/app/scripts/superdesk/editor/editor.ctrl.js
client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/styles.less
client/app/scripts/superdesk/editor/views/editor.html
client/app/styles/less/buttons.less

Reverts superdesk/superdesk#1707

Revert "Editor: reorder blocks"

---

client/app/scripts/superdesk-archive/views/preview.html

fix(preview): Fixed image captions.

---

.travis.yml
client/package.json
server/features/environment.py
server/requirements.txt
server/settings.py

remove some settings that are part of default settings

chore: update server/client

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/views/authoring.html
client/app/scripts/superdesk-authoring/views/full-preview.html
client/app/scripts/superdesk/menu/menu.js
client/app/scripts/superdesk/menu/views/superdesk-view.html

feat(authoring): Implemented opening full-preview in new tab.

---

client/app/scripts/superdesk/editor/add-embed.ctrl.js

fix(authoring): Fixed removing \n from embed codes.

---

server/apps/pa_img/pa_img_datalayer.py

and switch from urllib to requests

fix(paimg): fix paimg url

---

client/app/scripts/superdesk-authoring/views/full-preview.html

fix(authoring): Fixed topics in preview.

---

server/apps/prepopulate/data_initialization/pa/desks.json
server/apps/prepopulate/data_initialization/pa/stages.json

Added Motoring and Real Life desks to prepopulation files.

---

client/app/scripts/superdesk-authoring/views/article-edit.html
client/app/scripts/superdesk/editor/add-embed.ctrl.js
client/app/scripts/superdesk/editor/editor.ctrl.js
client/app/scripts/superdesk/editor/editor.js
server/apps/prepopulate/data_initialization/pa/validators.json
server/apps/prepopulate/data_initialization/validators.json

References are stored in `associations` like:
```
"_embedded_8964700761":{"_created":"2016-02-18T13:58:37+0000","_etag":"c31b3ed93c4afbc424671a0905fb7fbfa553b770","_id":"56c5ce0d91e3ff00ac9bf9ce","_links":{"self":{"href":"picture_crop/56c5ce0d91e3ff00ac9bf9ce","title":"Picture_crop"}},"_status":"OK","_updated":"2016-02-18T13:58:37+0000","crop":{"CropBottom":720,"CropLeft":0,"CropRight":960,"CropTop":0},"height":720,"href":"http://localhost:5000/api/upload/56c5ce0d91e3ff00ac9bf9ce/raw?_schema=http","item":{"_created":"2016-02-18T11:03:02+0000","_current_version":2,"_etag":"28cfa2aa288aefdcdfc41514bafb341eaae7666e","_id":"urn:newsml:localhost:2016-02-18T11:03:02.406621:d8ec9999-0531-4f9c-8a8b-e71c04035159","_links":{"self":{"href":"/archive/urn:newsml:localhost:2016-02-18T11:03:02.406621:d8e …
```

Keep embeds refs in ninjs associations [SDPA-155]

---

client/package.json

it has fix for authoring slow loading

update client core

---

server/data/vocabularies.json

Removed desired response and reader type from News, sport and motoring.

---

server/data/vocabularies.json

SDPA-235 - Territory options do not match requested options

Missing territories to Territory controlled vocabulary

---

client/app/index.html

this will make more sense when https://github.com/superdesk/superdesk-client-core/pull/64 is merged

set client to use alchemy tags

---

server/data/content_types.json
server/settings.py

Updated vocabularies and content types for using urgency field.

---

client/app/index.html
client/app/main.js
client/bower.json
client/package.json
server/requirements.txt

chore: update client/server cores

---

client/app/scripts/superdesk-authoring/views/authoring-header.html

Removed Topic field.

---

server/data/vocabularies.json

Updates image crop renditions

---

server/aap_mm/aap_mm_datalayer.py

This should fix the failing test in superdesk/superdesk#1822

fix(aap multimedia) a change in the core broke it.

---

.travis.yml
client/package.json
server/requirements.txt

and disable running there e2e tests, it runs on superdesk-client-core repo

update master cores

---

server/data/search_providers.json

should be setup by the pre-populate script

SDPA-256 : PA Image API search activation

---

scripts/update-cores-references.py

I share a script I use to update dependencies.
I don't know if it's useful for the repository...

script to update core dependencies

---

server/data/desks.json

Updated population data, added services to desks.

---

client/app/index.html
client/app/translations.js
client/package.json

taken from client-core
hi @marwoodandrew I've moved it here so it won't affect others

fix(translations): add aap specific translations

---

client/app/index.html

Added autopopulateByline setting to config.

---

server/data/vocabularies.json

Missed the none-core version of the vocabularies json file, when I did the qcode changes.

fix(vocabularies) make the vocabularies json files consitant

---

server/settings.py

it will make macros written for aap not available for pa

disable aap macros

---

client/app/index.html
client/bower.json

it's used to get metadata of an image when uploading

fix(upload): add exif lib to index

---

client/app/index.html

Depends on https://github.com/superdesk/superdesk-client-core/pull/220

feat(editor): Added indentation for paragraphs in editor [SDNTB-27]

---

client/package.json
scripts/update-cores-references.py
server/requirements.txt

plus fix update cores script pattern

chore: update server/client core

---

client/app/index.html

https://dev.sourcefabric.org/browse/SDNTB-148

Added configuration for authoring topbar buttons

---

client/app/docs.html

Removed require from UI documentation page

fix(ui-doc): Fixed UI documentation page

---

.travis.yml
Dockerfile
client/app/index.html
client/bower.json
client/package.json
server/requirements.txt

SDNTB-135 get the latest translations

chore(core): Update superdesk cores

---

server/settings.py
server/ws.py

This PR depends on  [core PR 262](https://github.com/superdesk/superdesk-core/pull/262)

[SD-3952] Modify socket to use broker.

---

client/app/translations.js

Renaming not needed as the main CATEGORY button was changed to SERVICE

SDNTB-160 Localization: custom button in the editor

---

client/app/docs/views/main.html

Also changed line endings from CRLF to LF

feat(ui-doc): Added info for resizing and reordering authoring items

---

server/data/content_types.json

abstract and body_html added to content type. Fix the disapearing toolbar

---

client/app/translations.js
server/data/content_types.json
server/data/vocabularies.json
server/requirements.txt

Ranking field removed.

---

client/package.json

Client package.json updated.

---

server/data/content_types.json

Ranking field is set to be displayed only on selected services.

---

client/app/index.html

Timeformat fixed.

---

server/data/vocabularies.json

"Quiz" is a new option added to the Assets metadata field

Updates Assets controlled vocabulary by adding 'Quiz'

---

server/data/content_types.json

Anchor button removed.

---

client/package.json
server/pa/pa_img/pa_img_datalayer.py
server/requirements.txt

depends on https://github.com/superdesk/superdesk-core/pull/303
and
https://github.com/superdesk/superdesk-client-core/pull/330

Apply custom renditions for PA images SDPA-402

---

bower.json
client/bower.json
server/data/content_types.json

Anchor in editor fixed.

---

client/app/index.html
server/ntb/macros/__init__.py
server/ntb/macros/valuta.py
server/settings.py

The example ntb macro is not final yet, the integration is done

feat(macros): Integrate a custom ntb macro.

---

client/app/index.html
client/app/index.less
client/bower.json
client/package.json
server/requirements.txt

feat(editor): setup new editor for master

---

server/data/desks.json
server/data/stages.json

Fixing up desks and stages in prepop json to create draft/working stages in the style as seen in master branch json files.

SDPA-421 : Update deployment scripts to set desk stages properly

---

server/data/vocabularies.json

fix(publish): enable newsml1.2 for wire clients

---

server/data/subscribers.json

Relates to https://dev.sourcefabric.org/browse/SDPA-445

Updates publishing subscriber to use PA's Amazon environment

---

client/app/index.html

after https://github.com/superdesk/superdesk-client-core/pull/434 it would switch to italics

set abstract not to use italics

---

client/app/index.html

after https://github.com/superdesk/superdesk-client-core/pull/434 it would switch to italics

set config for italic abstract

---

server/ntb/scanpix/__init__.py
server/ntb/scanpix/scanpix_datalayer.py
server/ntb/scanpix/scanpix_datalayer_tests.py
server/settings.py

Implement Scanpix Search provider with features such as black&white
or clearEdge pictures search, and search by one or severals IDs
SDNTB-15

[SDNTB-15] [SDNTB-159] Create Scanpix search provider

---

server/ntb/scanpix/scanpix_datalayer.py

bug introduced my last PR, this PR fix it.

Fixed MIME type detection for Scanpix search provider

---

client/app/translations.js
server/settings.py

+ Also [SD-4510] - Default genre value

fix(translation) - 'Services' to 'Categories' translation

---

client/app/docs.html
client/package.json

Fixes a problem with the docs, depends on [this pull request](https://github.com/superdesk/superdesk-client-core/pull/495)

ui(fix): docs

---

client/app/index.html

SDNTB-189
this will make more sense once https://github.com/superdesk/superdesk-client-core/pull/458 gets merged, but it won't hurt to have it in place :wink:

feat(monitoring): add single line config for monitoring lists

---

client/package.json
server/aap/import_text_archive/commands.py
server/data/validators.json
server/requirements.txt

This also includes PR from @marwoodandrew 
- [SD-4491] Mark tabular content as format preserved and pre tag it

[AAP] - Updating cores

---

.travis.yml
client/app/index.html
client/package.json
server/requirements.txt
server/settings.py

depends on:
https://github.com/superdesk/superdesk-core/pull/366
https://github.com/superdesk/superdesk-client-core/pull/506

SDPA-456 Blocked and then repeat publishing caused by "Failed to move to archived." error

---

client/Gruntfile.js
client/package.json

feat(tansa): Configure the proxy for tansa server

---

.travis.yml
server/ntb/scanpix/scanpix_datalayer_tests.py
server/ntb/tests/io/feed_parsers/nitf_tests.py
server/ntb/tests/io/fixtures/nitf_test.xml
server/requirements.txt
server/settings.py

NTB specific data mapping is done in settings, following the refactoring
of nitf parser
SDNTB-201

[SDNTB-201] Modify NITF parser to be able to ingest NTB metadata

---

server/data/vocabularies.json

This PR depends on [#390](https://github.com/superdesk/superdesk-core/pull/390)

[SD-4611] Removed AAP related formatters from master branch.

---

server/settings.py

@vied12  This is needed also for PA
@akintolga This is needed also for AAP

fix(locators): Read the default locators on dateline (SD-4639)

---

server/settings.py

@gbbr this should do the trick

fix(server): enable content profiles api

---

client/app/index.html
server/Procfile
server/newrelic.ini
server/requirements.txt

it was missing css for resize handle

fix(authoring): fix resizable authoring

---

client/app/translations.js

Missing keyword notification on publish fixed.

---

client/app/docs.html

feat(docs): SD-4307 Updated documentation page with editor format options

---

client/package.json
server/settings.py

requires https://github.com/superdesk/superdesk-core/pull/352

picture_renditions added to installed apps

---

server/ntb/tests/io/feed_parsers/nitf_tests.py
server/ntb/tests/io/fixtures/nitf_test.xml
server/settings.py

Added anpa_category (used for service) and updated priority to use meta element named "NTBPrioritet"
SDNTB-221

[NITF] Ingest SERVICE and priority value from NITF files

---

server/data/vocabularies.json

fix(vocabularies): set priority as managable cv

---

server/ntb/tests/io/feed_parsers/nitf_tests.py
server/settings.py

This commit fix the handling of services for NTB, qcode and language
found in vocabularies are used (or name is used as qcode if not found).
fix SDNTB-233

[NITF] fixed parsing of services (anpa_category)

---

client/app/docs.html
client/app/docs/styles/main.less

- fixed broken styles
- added radio buttons
- icon font updated
- css refactoring

Documentation page

---

server/data/content_types.json
server/data_updates/00001_20160701-013007_desks.py

metadata validation and upgrade for PA

SD-4886 Metadata validation on content profiles does not work correctly

---

client/package.json

Update client to https://github.com/superdesk/superdesk-client-core/commit/0487f6456dc7b6a7b99c54824e81f6f0df5eeb7d

Bump version to 0487f6456

---

server/data/vocabularies.json
server/ntb/publish/__init__.py
server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py
server/requirements.txt
server/settings.py

This commit implement a new NTBNITF subscribe type and publish items
in NITF format with customizations for NTB.
SDNTB-229

[NITF] NITF Publisher with customizations for NTB

---

server/ntb/publish/ntb_nitf.py
server/requirements.txt

changed default extension of NTB NITF formatter from "ntf" to "xml"
SDNTB-252

[NITF][Formatter] changed default extension

---

server/ntb/publish/ntb_nitf.py

<evloc/> element was missing, this patch add it
SDNTB-229

[NITF] added evloc element in NTB NITF

---

client/superdesk.config.js

"Category" is translated to "Service"

---

server/data/validators.json
server/data_updates/00002_20160803-171643_validators.py

updated validators for embedded pictures

SD-4926 Story with Feature image can be published without required fields

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

[NITF] NTB NITF is now encoded in iso-8859-1

---

server/data/content_types.json

Added body footer

---

client/package.json

superdesk/superdesk-client-core@eb1988acc

Bump client core to eb1988acc

---

client/superdesk.config.js

chore(config): add default required media metatadata fields

---

client/package.json

Same as https://github.com/superdesk/superdesk-client-core/pull/881

ui(hotfix): fixes a problem with a regression in webpack

---

client/package.json
server/data/validators.json
server/data_updates/00002_20160803-171643_validators.py
server/requirements.txt

updated validators for embedded pictures

SDPA-441 Publish - Image metadata validation - API images

---

server/data/validators.json
server/data_updates/00003_20160829-094134_validators.py

it prevented publishing of embedded images together with text item.

fix(publish): add embedded flag to embedded validators

---

client/superdesk.config.js

- anpa_category, genre, priority and urgency exist in aggregations and they can be used from "Filters"

refact(search) - Duplicate search parameters that exist in filters removed

---

server/data/content_types.json

body footer has now a default value of "©NTB"
SDNTB-261

[content types] added default value for body footer

---

server/ntb/publish/ntb_nitf.py

body footer is added a new paragraph at the end of the body_content
SDNTB-263

[NITF] [FORMATTER] added body footer

---

server/ntb/publish/ntb_nitf.py

[NTB] [FORMATTER] doc-id, footer and tagline fixes

---

server/ntb/macros/npk_metadata.py

NPKSisteNytt Metadata Macro will perform the following changes to
current content item:
- change the byline to "(NPK-NTB)"
- change the signoff to "npk@npk.no"
- change the body footer to "(©NPK)" - NB: copyrightsign, not @
- change the service to "NPKSisteNytt"

feat(macro): NPKSisteNytt Metadata Macro

---

server/ntb/publish/ntb_nitf.py
server/requirements.txt

<distributor/> element is now added in its own method so it is added in
the right location.
SDNTB-280

[NITF] [FORMATTER] moved <distributor/> element creation in new method

---

server/ntb/macros/extract_html.py

Delete from body_html all html tags except links

feat(macro): Extract Html Macro

---

server/ntb/publish/ntb_nitf.py
server/requirements.txt

DEFAULT_TIMEZONE from settings is now used, so admin can choose if she
wants to use local timezone (if not set) or any other one.
SDNTB-285

[NITF] [FORMATTER] use DEFAULT_TIMEZONE for localized date elements

---

docker/docker-compose-dev.yml

Missing elasticsearch port for docker-compose-dev

Missing elasticsearch port for docker-compose-dev

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py
server/requirements.txt

this commit add pubdata with date.publication attribute.
SDNTB-286

[NITF] [FORMATTER] added pubdata element

---

server/data/validators.json

fix(validators): set slugline not required for embedded pictures

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

[NITF] [FORMATTER] fixed dateline element

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

previously NTB NITF formatter was encoding unicode XML to requested
iso-8859-1 format, replacing invalid characters in this format by "?",
because XML was supposedly not wanted.
It seems that XML encoding is accepted at the end, so this commit
change this behaviour to encode directly in iso-8859-1, and XML escape invalid chars.
A unicode version is kept in formatted_item, as it may be useful for
previewing.
SDNTB-280

[NITF] [FORMATTER] escape non unicode characters

---

client/package.json
client/superdesk.config.js
server/.travis.yml
server/data/validators.json
server/pa/pa_img/pa_img_datalayer_tests.py
server/requirements.txt

validators fixes, translation fixes

SDPA-512, SDPA-514, SDPA-498

---

docker/start.sh

Replace ws address with Superdesk ws for 0.0.0.0 IP address

fix docker start script

---

docker/docker-compose-e2e.yml
docker/start-e2e.sh

This file is adding a docker specific configuration for e2e tests.
I've update my gist accordingly: https://gist.github.com/lnogues/09e6f1161d853b3523286c8774d42ffc

Added e2e docker-compose specific configuration

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py
server/requirements.txt

SDNTB-280
/!\ this P.R. can't validate tests before https://github.com/superdesk/superdesk-core/pull/580 is merged

[NITF] [FORMATTER] use the new HTML to NITF converter

---

server/requirements.txt
server/settings.py

removed planning and coverages apps which don't exist anymore in

---

client/package.json
server/settings.py

- there is a fix for publishing of packages with pictures

update client version

---

server/requirements.txt

update server core

---

server/ntb/macros/extract_html.py
server/ntb/macros/extract_html_tests.py

fix(macro): Fix extract HTML macro

---

client/package.json

This was causing `grunt server` to fail with latest commit.

Added missing preset to package.json

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py
server/requirements.txt

use the new attr_reset from html2nitf to remove "style" attributes
SDNTB-311

[NITF] [FORMATTER] remove styles

---

server/data/content_types.json
server/ntb/macros/extract_html.py
server/ntb/macros/extract_html_tests.py

The result html should be a list of paragraphs.

fix(macro): Fix the extract html macro

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

NITF Formatter was failing when prefixed elements were present in
body_html (can happen in case of copy/paste).
This commit work around this.
fix SDNTB-313

[NITF] [FORMATTER] fixed parsing of prefixed elements

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

body_footer now use "txt" class
SDNTB-317

[NITF] [FORMATTER] changed class of body footer

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

characater count is added to item-length attribute of pubdata element
SDNTB-310

[NITF] [FORMATTER] added character count to pubdata element

---

client/superdesk.config.js

[SDESK-288]
- This change will enable swimlane view in master instance with four columns

(swimlane) - swimlane view config

---

server/ntb/scanpix/scanpix_datalayer.py

fix issues with using timeLimit and archived date
fix issue with incorrect timeLimit values (remove space after value)

SDESK-200: FILTERS in advanced search do not work for Search Providers

---

server/requirements.txt

- there is fix for email publishing

update server core to 1.4rc2

---

docker/common.yml
docker/docker-compose-dev.yml
docker/docker-compose-e2e.yml
docker/docker-compose-prebuilt.yml
docker/docker-compose.yml
docker/superdesk_vhost.conf

This reverts commit a1aac9ff2887b8e225fab3d19cd67d6d8b3be207.

Revert "remove pubapi docker service"

---

server/data/validators.json
server/requirements.txt

- add validators to data
- use 1.4.1 server core version

fix validators

---

client/package.json

superdesk/superdesk-client-core@a4a5e34

Update client to 1.6.0-rc2

---

docker/common.yml
docker/docker-compose-prebuilt.yml
docker/requirements.txt
docker/superdesk_vhost.conf
scripts/docker-local-create-user.sh
scripts/docker-local-demo.sh

docker config cleanup

---

client/package.json

to superdesk/superdesk-client-core@90762a7

Update core 

---

server/requirements.txt

updated requirements to get HTML void elements fix

---

client/package.json

Update to superdesk/superdesk-client-core@dd674f510

Update client core to dd674f5

---

client/package.json
server/requirements.txt

found the issue, we can upgrade again to 1.7rc1
This reverts commit 144e098c983a7f61fc87ba75294bc6275092c212.

Revert "Revert "updated to v1.7rc1""

---

client/package.json

Push to superdesk/superdesk-client-core@927b626

bump(client): update client to 927b626

---

client/package.json
client/superdesk.config.js

Bump to superdesk/superdesk-client-core@bff38c4

Bump client core to bff38c4

---

client/package.json
client/superdesk.config.js
server/data/vocabularies.json
server/requirements.txt
server/settings.py

keywords come from The Source's WordPress WXR archives.
SDTS-15

[vocabularies] added keywords vocabularies

---

client/package.json
server/requirements.txt

updated core to fix issue with rendition

---

server/requirements.txt

updated core to get rendition fix

---

server/data/vocabularies.json

[DATA] added missing values in vocabularies for data initialization

---

client/superdesk.config.js

[CLIENT] set italicAbstract to false

---

client/package.json
client/superdesk.config.js
server/requirements.txt

and disable analytics for now, it needs some fixes in packages.json

update core, planning

---

server/requirements.txt

Packages are stored in env/src directory, so easier to find them

Use "-e" in req.txt for "superdesk-*" repos

---

server/requirements.txt

Packages are stored in `env/src` directory, so easier to find them

Use "-e" in req.txt for "superdesk-*" repos (planning-mvp branch)

---

server/data/content_types.json
server/data/vocabularies.json

fix content profile editing for story

---

docker/start.sh
scripts/docker-local-create-user.sh

it didn't detect mongo as running anymore
fix #2762

avoid using fig wrapper script in docker

---

client/ansa/index.js
client/ansa/widgets/ansa-related-widget.html

add video filter to related items widget

---

server/data/vocabularies.json
server/scripts/parse_products.sh

with a script that parsers csv and generates json with items
SDANSA-126

import products

---

server/ansa/analysis/__init__.py
server/settings.py

- there are new fields missing in the schema

fix semantics mapping

---

client/package.json

So we always get the latest changes from the Publisher component master branch without a need to change the commit every time.

Update package.json - use Publisher master branch

---

server/settings.py

- needed for language filtering testing

enable apps.languages on master

---

server/data/vocabularies.json
server/scripts/parse_products.sh

add codes to products vocabularies

fix product codes

---

client/ansa/closed-desk/index.js
client/ansa/closed-desk/styles.scss
client/ansa/closed-desk/views/close-desk-widget.html
client/ansa/index.js
server/ansa/macros/__init__.py
server/ansa/macros/desk_routing.py
server/ansa/routing/__init__.py
server/requirements.txt
server/settings.py

implement desk routing widget plus macro

---

client/ansa/closed-desk/index.js
client/ansa/closed-desk/views/close-desk-widget.html
server/ansa/macros/desk_routing.py
server/ansa/routing/__init__.py

- introduce new privilege for desk routing management
- make resolving open desk recursive
SDANSA-39 SDANSA-153

update desk routing

---

client/package.json

Reverts superdesk/superdesk#2835

Revert "Update package.json - use Publisher master branch"

---

client/package.json
server/requirements.txt
server/settings.py

add missing languages to settings

---

client/ansa/closed-desk/index.js

- update state on route change
SDANSA-162

fix desk routing notifications out of sync

---

server/ansa/routing/__init__.py

this patch modify previous one by removing all marks of items in a desk,
not only the one of closed destination, because destination can change
in case of chaining, and user expect to see all mark for the desk
removed.
SDANSA-154

[ROUTING] remove all marks when closing desk

---

server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py

- add sign off
- add authors
- adjust located handling
- use output codes for products cv
- add subtitle
SDANSA-163

fix ansa newsml g2 formatter

---

server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py
server/settings.py

export with urls to superdesk upload api

fix newsmlg2 media output

---

server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py

fix sign_off/authors in ansa newsmlg2

---

client/ansa/index.js
client/package.json
server/ansa/analysis/analysis.py
server/ansa/macros/semantics.py
server/requirements.txt
server/settings.py

- use .51 service by default
- populate abstract using main sentences
SDANSA-173

update semantics service

---

server/ansa/parser/parser.py
server/ansa/parser/parser_test.py
server/ansa/parser/semantics.xml
server/requirements.txt

fix(parser): parse copyright info

---

client/package.json
client/superdesk.config.js
server/requirements.txt

and add copyright field to grid view

update cores to 1.22

---

client/superdesk.config.js

add usageterms to lists/grid view

---

server/ansa/parser/parser.py
server/ansa/parser/parser_test.py
server/ansa/parser/semantics_missing_rights_info.xml

when there is an item in cv matching copyright holder

populate copyright and usage terms using cv

---

server/ansa/tests/vfs_test.py
server/ansa/vfs.py
server/app.py
server/dev-requirements.txt
server/settings.py

implement vfs media storage

---

server/Procfile
server/settings.py

NOTE: Requires PR from analytics (https://github.com/superdesk/superdesk-analytics/pull/47)

config(analytics): Enable Highcharts export server in Procfile

---

client/package.json
server/ansa/formatters/ansa_newsml_g2_formatter_test.py
server/requirements.txt

Reverts superdesk/superdesk#2961

Revert "update cores to 1.25"

---

server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py
server/ansa/parser/parser.py
server/ansa/parser/parser_test.py
server/ansa/search.py
server/picture-profile.json
server/settings.py

- update picture schema
- keep original ansa id for ingested/fetched content and use it in the newsml output

ansa update

---

client/ansa/AnsaRelatedCtrl.js
client/ansa/index.js
client/ansa/widgets/ansa-related-widget.html

- from related items widget
- from metasearch
SDANSA-209 SDANSA-210

fix dropping items to editor3

---

client/superdesk.config.js

- set swimlane columns limit to 99
- disable publishing from authoring desk
SDESK-3540 SDESK-3544

update client config

---

server/data/vocabularies.json

Related to https://github.com/superdesk/superdesk-core/pull/1423

SDESK-3549 Minor corrections to labels

---

server/ansa/analysis/analysis.py
server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py
server/ansa/geonames.py
server/ansa/parser/located.xml
server/ansa/parser/parser.py
server/ansa/parser/parser_test.py

handle located using geonames in input and outout

---

server/settings.py

setup media metadata validation

---

client/package.json
server/ansa/analysis/analysis.py
server/requirements.txt

and populate products using semantics

update cores to 1.27

---

client/ansa/closed-desk/styles.scss
client/ansa/widgets/AnsaStagesAutoPublish.ts
client/ansa/widgets/index.js
client/ansa/widgets/stages-auto-publish.html
server/ansa/stage_auto_publishing.py
server/settings.py

feat: auto publishing via signals

---

client/ansa/styles.scss
client/ansa/views/ansa-live-suggestions.html

fix missing back button in live assistant

---

client/package.json
server/requirements.txt

Reverts superdesk/superdesk#3048

Revert "chore(macros): Update chores in order to get new macros (SDANSA-222)"

---

server/ansa/tests/update_signal_test.py
server/ansa/update_signal.py
server/settings.py

SDANSA-239
requires https://github.com/superdesk/superdesk-core/pull/1563

add version number to headline on update

---

client/ansa/index.js
client/ansa/views/ansa-map.html
client/ansa/views/menu-map.html

fix ansa map menu item

---

client/ansa/index.js

add AND operator to metasearch query

---

client/ansa/index.js

alt+m - metasearch
alt+l - live assistant
alt+a - aiNews
SDANSA-233

add missing workspace menu shortcuts

---

client/ansa/index.js
client/ansa/widgets/AnsaStagesAutoPublish.ts
client/package.json
server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py
server/requirements.txt

update headline according to priority/genre

---

server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py

add desk name prefix to output as signal

---

server/ansa/macros/__init__.py
server/ansa/macros/auto_publish.py

add auto publish macro

---

.travis.yml
server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py

so on update it will keep guid in newsml
SDANSA-237

keep original item guid in the output

---

client/ansa/index.js
server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py

- fix ansa formatter when output is empty
- handle bulletin and genre name on client
- use dateline text in output

ansa updates

---

server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py

- remove genre
- remove located
- fix creditline
SDANSA-274 SDANSA-275 SDANSA-276

fix newsml output for pictures

---

server/ansa/search.py
server/ansa/search_test.py

fix photo search when using quotes

---

client/ansa/AnsaRelatedCtrl.js
client/package.json
server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py
server/ansa/parser/parser.py
server/ansa/parser/parser_test.py
server/ansa/parser/photo.xml
server/picture-profile.json

update ansa photo handling

---

server/ansa/tests/validate_test.py
server/ansa/validate.py
server/settings.py

implement custom validation based on products

---

server/ansa/formatters/ansa_newsml_g2_formatter.py
server/ansa/formatters/ansa_newsml_g2_formatter_test.py

add original desk to output

---

client/package.json
server/requirements.txt

use latest version of cores

---

client/ansa/AnsaRelatedCtrl.js
client/ansa/widgets/ansa-related-widget.html
client/extensions/imageShortcuts/src/extension.ts

do not show buttons for adding media to article if article does not have specified fields it its content profile

---

client/superdesk.config.js
docker/common.yml

https://github.com/superdesk/superdesk-client-core/pull/3162

enable extensions for testing on sd-master

---

client/index.js
client/superdesk.config.js

DEPENDS ON: https://github.com/superdesk/superdesk-client-core/pull/3188

improve extension setup

---

server/data/vocabularies.json

This PR adds `vocabularies.json` file with the translations in order to enable the translations feature

added vocabularies.json with translations

---

.travis.yml
client/index.js

enable date time field extension

---

client/package.json
server/data/vocabularies.json
server/requirements.txt

Superdesk version will be the latest stable.
Superdesk Publisher version will be the latest one from `master` branch

Set SD stable version & added vocabularies.json

---

server/ansa/__init__.py

if original is not yet published
SDANSA-385

unlink update on auto publish

---

server/data/vocabularies.json

merge vocabularies from core and planning

---

.travis.yml
client/Gruntfile.js
client/ansa/index.js
client/package.json
client/po/it.po
server/requirements.txt

- override translations to disable non-en UI
- fix travis build

update cores to 1.33

---

client/superdesk.config.js

Show seconds on time picker

---

client/ansa/AnsaRelatedCtrl.js

will hide images already used on the same day
SDANSA-395

filter out used images in related widget

---

server/ansa/remove_expired_media.py
server/settings.py

SDANSA-401
uses https://github.com/superdesk/superdesk-core/pull/1877

remove media from items expiring in archived

---

client/superdesk.config.js
server/ansa/search.py
server/ansa/search_test.py

show usage info on media items

---

server/ansa/commands/remove_expired_media.py
server/ansa/remove_expired_media.py
server/manage.py

only keep viewImage and only if that item is no longer in archived

process legal archive items and remove its media

---

server/ansa/tests/validate_test.py
server/ansa/validate.py

:warning: this pr was not tested manually

Fix broken images links

---

client/ansa/package-manager/views/package-manager-widget.html

[SDANSA-405] - Restore the package manager

feat(package-manager): Fixed issue with dropdown on package manager

---

server/ansa/save_iptc.py
server/settings.py

update iptc metadata for associations

---

client/extensions/ansaIptc/src/extension.ts

Since I can't reproduce this issue, so I don't know the actual source of the issue.

Ninjs formatter - DateCreated field is not populated with data. [SDANSA-423]

---

server/data_updates/00005_20181114-090110_vocabularies.py

SDESK-5445
This migration was making usageterms to be multiselection

Fix migration for single selection vocabularies

---

server/ansa/macros/__init__.py
server/ansa/macros/schedule.py
server/ansa/macros/schedule_0100.py
server/ansa/macros/schedule_0700.py
server/ansa/macros/schedule_0730.py
server/ansa/stage_auto_publishing.py

it will schedule publishing at predefined times
SDANSA-478

add macros for publishing schedule

---

.github/workflows/tests.yml
docker-compose.yml

add missing env var to docker compose

---

.github/workflows/ci.yml
server/Dockerfile
server/ansa/macros/process_html.py
server/ansa/macros/translate_text.py
server/requirements.txt

- update content state
- handle subtitle
SDANSA-488

fix translate macro

---

.gitignore
.travis.yml
Dockerfile
client/index.js
client/package.json

required for https://github.com/superdesk/superdesk-planning/pull/1585

use build tools

---

.github/workflows/tests.yml
server/Dockerfile
server/docker/start.sh
server/requirements.txt

update server requirements

---

client/package-lock.json
client/package.json

it fixed some build issues back then, but might not be needed anymore

remove types/node package

---

client/.dockerignore
client/Dockerfile
docker-compose.yml

fix client docker build

---

.github/workflows/behave.yml
.github/workflows/pytest.yml
.github/workflows/server.yml
.github/workflows/tests.yml
server/tests/test_placeholder.py

- add python-version param to pytest/behave
- run those workflows on main repo

improve github workflows reusability
