superdesk/superdesk

server/apps/groups.py, server/features/desks.feature, server/features/groups.feature, server/features/stages.feature, server/superdesk/validator.py
=> (fix) Modified the code so that group/stage/desk name are unique.

server/features/ingest_provider.feature, server/features/steps/steps.py, server/superdesk/io/ingest_provider_model.py
=> (fix)[ingest] Fixing ingest provider so that update notification is generated

client/app/scripts/superdesk-desks/directives.js, client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-ingest/views/settings/ingest-routing-content.html, client/app/scripts/superdesk-ingest/views/settings/settings.html, client/app/scripts/superdesk/ui/ui.js
=> feat(ingest): Routing UI.

server/superdesk/io/rss.py, server/superdesk/io/rss_tests.py
=> Add item type 'text' to items generated from RSS feeds

client/app/scripts/superdesk-archive/views/item-rendition.html, client/app/scripts/superdesk-archive/views/media-box-grid.html, client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk/filters.js, client/run.sh.save
=> fix(archive): Headline and container values for images in grid view

client/app/scripts/superdesk-archive/views/media-box-grid.html, client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk-archive/views/media-box.html, client/app/scripts/superdesk-archive/views/preview.html, client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk/activity/activity-list-directive.js, client/app/scripts/superdesk/services/keyboardManager.js, client/app/scripts/superdesk/services/keyboardManager_spec.js
=> feat(ingest): implement shortcuts for ingest

scripts/sd-update
It updates your local SD repo with one single command:
- stashes your local changes
- pulls latest updates (with rebase)
- pushes latest updates to your git repo
- npm update && bower update
- updates backend requirements (pip install)
- restores your local changes
You can specify which branch to use with: -b 'branch'
-h for help
=> script for updating local superdesk repository

server/superdesk/__init__.py
@actionless This should do the trick...
=> SD-1611 Fix command return value on success

client/app/scripts/superdesk-search/views/search-results.html
=> fix(archive): Enabled related items tab.

client/app/scripts/superdesk-desks/directives.js, client/app/scripts/superdesk/ui/ui.js, server/apps/archive/__init__.py, server/apps/archive/archive.py, server/apps/archive/archive_media.py, server/apps/archive/archive_publish.py, server/apps/archive/common.py, server/apps/publish/__init__.py, server/apps/publish/archive_publish.py, server/features/content_publish.feature, server/features/routing_rules.feature, server/features/steps/steps.py, server/settings.py
Also a user shouldn't be allowed to update after publishing.
[SD-1545] Added a scenario for testing uniqueness of routing scheme names
=> feat(publish) [SD-1549] Backend: Create a publish endpoint for publishing items.

client/app/scripts/superdesk/api/api-service.js
useful for liveblog team to keep using `underscore` beside
=> lodash in api-service imports

bower.json
it implements shortcuts in firefox
=> fix(editor): update editor to version with shortcuts

client/app/scripts/superdesk-archive/controllers/list.js
Fixed the filter of content by desk
=> SD-1570: Move personal option on the desk combobox

client/app/scripts/superdesk-archive/views/list.html, client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk-archive/views/preview.html, client/app/scripts/superdesk-authoring/views/authoring.html, client/app/scripts/superdesk-authoring/views/sd-content-create.html, client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/styles/highlights.less, client/app/scripts/superdesk-highlights/views/highlights_title_directive.html, client/app/scripts/superdesk-highlights/views/mark_highlights_dropdown_directive.html, client/app/scripts/superdesk-highlights/views/package_highlights_dropdown_directive.html, client/app/scripts/superdesk-highlights/views/settings.html, client/app/scripts/superdesk-items-common/styles/archive-preview.less, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk/activity/views/activity-list.html, client/app/scripts/superdesk/ui/ui.js, client/app/styles/less/dropdowns.less, client/app/styles/less/layouts.less
SD-1244
+ Add ui for managing highlights configurations
+ Fix styling issues with highlight dropdowns
+ Improve hilight inclusion list directive for content items
=> Highlights: Fixes and Improvements

client/app/scripts/superdesk-archive/controllers/list.js, client/app/scripts/superdesk-dashboard/module.js, client/app/scripts/superdesk-dashboard/views/desk-dropdown.html, client/app/scripts/superdesk-dashboard/views/workspace-topnav.html, client/app/scripts/superdesk-desks/module.js, client/app/scripts/superdesk-desks/tests/desks-spec.js, client/app/scripts/superdesk-users/users.js, client/app/scripts/superdesk-users/views/edit-form.html, client/app/scripts/superdesk/menu/styles/menu.less, client/spec/content_spec.js, client/spec/ingest_spec.js, server/apps/desks.py, server/apps/preferences.py, server/apps/users/users.py
fixing the tests for both firefox and chrome. locator works different for button texts. more info in the commit msg
@sivakuna-aap 
includes #56
=> e2e tests fix

client/app/scripts/superdesk/auth/auth.js
Creating e2e tests as well, we should merge this as it's a blocker.
=> fix reset password token check

server/features/routing_rules.feature, server/superdesk/io/ingest_provider_model.py
=> (feat)[Ingest Providers] Adding the routing scheme to the ingest provider.

client/app/scripts/superdesk-dashboard/views/workspace-topnav.html
Ingest nav bar option is hide on personal
=> SD-1620 : Wrong error message when ingesting to personal

LICENSE, README.md
- Replaces gplv3 with agplv3
- First draft of the README
=> [WIP] Repo info

.travis.yml, client/Gruntfile.js, client/spec/content_spec.js, client/spec/helpers/pages.js, client/spec/ingest_spec.js, client/tasks/options/connect.js, client/tasks/options/template.js, server/gunicorn_config.py, server/scripts/fig_wrapper.sh, server/settings.py
there is time to time port conflict with livereload on travis
=> fix(travis): avoid using livereload on travis

README.md
add info about installing docker.io, virtualenv and docker-composer
=> doc(install): add details about installation

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/authoring.html
=> fix(authoring): Fixed unlock button being displayed when item is sent.

server/apps/archive/archive_ingest.py, server/features/steps/steps.py
=> (fix) Routing: Fixing the issue where package items state was not correctly marked.

.travis.yml, README.md, client/app/scripts/superdesk-users/users.js, client/app/scripts/superdesk/menu/notifications/notifications.js, client/package.json, client/protractor-conf.js, client/scripts/test_e2e.sh, client/spec/content_spec.js, client/spec/helpers/pages.js, client/spec/helpers/utils.js, client/spec/login_spec.js, client/spec/setup.js, client/spec/users_spec.js, docker/container_build.sh, docker/run_e2e_tests.sh, scripts/docker-local-demo.sh, server/scripts/fig_wrapper.sh
creating a branch so that I can see it on bamboo..
=> improve e2e tests

client/app/scripts/superdesk-authoring/multiedit/views/sd-multiedit-inner-dropdown.html, client/app/scripts/superdesk-authoring/styles/article-edit.less, client/app/scripts/superdesk-packaging/packaging.js
=> Minor bug fixies

client/app/scripts/superdesk-archive/module.js, client/app/scripts/superdesk-dashboard/views/desk-dropdown.html, client/spec/fetch_spec.js, client/spec/helpers/pages.js, client/spec/spike_spec.js
- add a fallback for reloading for the user making the changes
SD-1571 SD-1677
=> fix(archive): reload items after fetch/spike

client/app/scripts/superdesk-dashboard/views/desk-dropdown.html, client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/views/mark_highlights_dropdown_directive.html, client/app/scripts/superdesk/activity/views/activity-list.html, client/spec/content_spec.js, client/spec/fetch_spec.js, client/spec/helpers/pages.js, client/spec/highlights_spec.js, client/spec/spike_spec.js, client/spec/users_spec.js, server/apps/highlights/resource.py, server/apps/prepopulate/app_prepopulate_data.json, server/features/highlights.feature, server/features/prepopulate.feature
Added e2e tests for highlights configurations
Changed the prepopulation script
Added unicity on highlight configuration name
=> feat(highlights configuration) - Add e2e tests for highlight configuration

server/superdesk/io/aap.py, server/superdesk/io/commands/update_ingest.py, server/superdesk/io/fixtures/aap.xml, server/superdesk/io/ftp.py, server/superdesk/io/nitf.py, server/superdesk/io/nitf_tests.py
=> (fix) Fixing ftp ingest service

client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-archive/views/media-box-grid.html, client/app/scripts/superdesk-archive/views/media-box-list.html
when item is fetched update list of desks without reloading the page
=> fix(fetch): update list of desks in ingest

client/app/scripts/superdesk-archive/views/preview.html, client/app/scripts/superdesk-authoring/styles/themes.less, client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-items-common/styles/archive-preview.less, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-packaging/views/packaging.html
=> feat(highlights): Generate text item from highlight package

client/app/scripts/superdesk-archive/archive-widget/baseWidget.js, client/app/scripts/superdesk/itemList/itemList.js, client/app/scripts/superdesk/itemList/views/item-list-widget.html
=> fix(widgets): Fixed similar items feature in content/ingest widgets.

client/app/scripts/superdesk-dashboard/workspace-tasks/styles/tasks.less
=> fix(style): Fix stages list

client/app/scripts/superdesk-highlights/views/mark_highlights_dropdown_directive.html, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk/ui/ui.js
=> fix(highlights): Fix UI issues

server/features/environment.py, server/macros/currency.py
there is another test using the real rate so there is no need
to test it there, where it's harder to make greaterThan asserts
=> fix(behave): use predefined USD/AUD rate

client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-packaging/packaging.less, client/app/scripts/superdesk-packaging/views/sd-package-items-edit.html
=> fix(packages): Improve package items reordering

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring-sidebar.html, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-authoring/views/authoring.html, client/app/scripts/superdesk-authoring/views/send-item.html, client/app/scripts/superdesk-desks/module.js, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-packaging/views/packaging.html, client/app/scripts/superdesk/activity/activity.js, client/spec/send_spec.js
=> fix send to func

client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-ingest/views/settings/ingest-routing-content.html
=> fix(routing): Fixed a bug when adding new rules.

client/app/scripts/superdesk-archive/views/list.html, client/app/scripts/superdesk-dashboard/workspace-tasks/views/desk-stages.html
=> fix(content): Fixed spiked button not being displayed on personal.

client/app/scripts/superdesk-dashboard/views/desk-dropdown.html, server/apps/archive/archive_composite.py, server/features/packages.feature, server/features/steps/steps.py, server/superdesk/eve_backend.py, server/superdesk/io/commands/update_ingest.py, server/superdesk/services.py
keep original etag/last_updated when setting linked_in_packages
=> fix(authoring): fix saving of packages

client/app/scripts/superdesk-archive/views/preview.html, client/app/scripts/superdesk-items-common/styles/archive-preview.less
=> fix(content): Fixed preformatted preview.

client/app/scripts/superdesk-archive/views/metadata-view.html, client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk/filters.js
=> (fix) Metadata: Fixing the category and genre.

client/app/scripts/superdesk-archive/views/media-box-grid.html, client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk-highlights/styles/highlights.less, client/app/scripts/superdesk-items-common/styles/media-archive.less
=> fix(highlights): Add * on grid view

server/app.py
cherry-pick https://github.com/superdesk/liveblog/pull/23
=> multiprocessing removed from backend server

client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-archive/views/media-view.html, client/app/scripts/superdesk-archive/views/single-item-preview.html, client/app/scripts/superdesk-items-common/styles/archive-preview.less, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-packaging/packaging.less, client/app/scripts/superdesk-packaging/views/sd-package-item-preview.html, client/app/scripts/superdesk-packaging/views/sd-package-item.html, client/app/scripts/superdesk-packaging/views/sd-package-ref.html, client/app/scripts/superdesk-packaging/views/sd-package.html
=> fix(lightbox): Fix lightbox preview

server/settings.py
otherwise it doesn't work within docker
=> fix(ws): make it listen on 0.0.0.0

server/superdesk/io/email.py, server/superdesk/io/fixtures/charset_in_subject_email.txt, server/superdesk/io/fixtures/odd_charset_email.txt, server/superdesk/io/rfc822.py, server/superdesk/io/rfc822_parser_test.py
Have also re-factored the exception handling so that the exception is caught and reported in the parser and swallowed by the ingest provider.
=> fix(email ingest) handle variations of charsets in headers

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/spec/helpers/utils.js, client/spec/package_spec.js
it was missing orig param needed to compute the diff
=> fix(authoring): fix save when closing item

client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-archive/views/media-view.html, client/app/scripts/superdesk-items-common/styles/archive-preview.less
=> Fix(lightbox): Fix items preview in lightbox

client/app/scripts/superdesk-archive/controllers/baseList.js, client/app/scripts/superdesk-archive/controllers/list.js, client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-archive/module.js, client/app/scripts/superdesk-archive/views/fetch.html, client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-search/views/search-results.html
=> feat(fetchAs): Initial groundwork for fetch-as.

server/app.py
Reverts superdesk/superdesk#179
=> Revert "multiprocessing removed from backend server"

client/spec/helpers/pages.js, client/spec/helpers/utils.js, client/spec/login_spec.js, client/spec/package_spec.js, server/app.py, server/gunicorn_config.py
Reverts superdesk/superdesk#202
=> Revert "Revert "multiprocessing removed from backend server""

client/app/scripts/superdesk-archive/controllers/list.js
=> fix(content): Fixed previewing unspiked item.

client/app/scripts/superdesk-ingest/ingest-widget/widget-ingest.less, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk/itemList/views/item-list-widget.html, client/app/scripts/superdesk/list/views/sdPaginationAlt.html
=> fix(widgets): Fix archive/ingest widget styling

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html, client/app/scripts/superdesk-authoring/metadata/views/metadata-words-list.html
=> feat(authoring) Adding keywords field to metadata in authoring page.

client/app/scripts/superdesk-groups/views/settings.html, client/app/scripts/superdesk/ui/ui.js, client/app/scripts/superdesk/ui/views/wizard.html
=> fix(groups): Fixed group create after tab switching.

client/app/scripts/superdesk/itemList/itemList.js
=> fix(widgets): Fixed similar items.

server/macros/abstract_populator.py, server/macros/abstract_populator_test.py
Fixed the issue with the empty body throwing an error..
=> fix(routing) - Handling empty body in the macro

server/superdesk/io/ingest_service.py, server/superdesk/io/rss.py
Looks like we get last_updated but not _created for some RSS feeds.
@superdesk/developers @sivakuna-aap @akintolga @marwoodandrew
=> Handle missing dates on RSS

client/protractor-conf.js, client/spec/content_spec.js, client/spec/fetch_spec.js, client/spec/helpers/pages.js, client/spec/helpers/utils.js, client/spec/helpers/waitReady.js, client/spec/login_spec.js, client/spec/package_spec.js, client/spec/send_spec.js, client/spec/setup.js, client/spec/spike_spec.js, client/spec/users_spec.js
- reporting was broken
- animations happens slower/faster
=> fix e2e failures in bamboo

server/apps/archive/archive_composite.py, server/apps/archive/commands.py, server/superdesk/io/commands/remove_expired_content.py, server/superdesk/io/commands/update_ingest_tests.py, server/superdesk/io/rss.py, server/superdesk/io/rss_test.py
SD- 1858 Remove orphaned content from ingest
=> SD-1855 Fix package removal on archive purge

client/app/scripts/superdesk-dashboard/workspace-tasks/tasks.js, client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/styles/desks.less, client/app/scripts/superdesk-desks/views/desk-tasks.html, client/app/scripts/superdesk-desks/views/desk.html, client/app/scripts/superdesk-desks/views/main.html, client/app/scripts/superdesk-desks/views/task-status-items.html
=> feat(desks): Master desk - Add Tasks tab

client/package.json, client/protractor-conf.js, client/spec/fetch_spec.js, client/spec/helpers/pages.js, client/spec/helpers/utils.js, client/spec/helpers/waitReady.js, client/spec/send_spec.js
still some testcases are executed non-sequentially and sometimes that became noticeable when io is slow
TODO: use request-promise and make helpers with callbacks to return promises
=> continue e2e fixing for bamboo

client/app/scripts/superdesk-packaging/packaging.js
=> fix(pakcages): Change 'read only' icon on package items

server/superdesk/errors.py, server/superdesk/io/commands/update_ingest.py, server/superdesk/io/reuters.py, server/superdesk/media/media_operations.py, server/superdesk/storage/desk_media_storage.py
SD-1869 - skip metadata load if we can't parse it
SD-1856 Investigate reuters image download triggering soft timeout
=> fix(ingest) - don't restart the ingest if an item fails.

client/app/scripts/superdesk-desks/desks.js
=> fix(desks): fixed desks service to handle 200+ desks/stages.

client/app/scripts/superdesk-ingest/module.js
=> fix(ingest): Fixed adding multiple routing rules.

server/apps/highlights/service.py
Reverts superdesk/superdesk#255
=> Revert "fix(highlights): Fix mark for highlights"

.travis.yml, client/spec/helpers/pages.js
=> Travis firefox

client/app/scripts/superdesk-desks/views/desk_users.html, client/app/scripts/superdesk-desks/views/user-role-items.html
=> fix(desks): Fix 'Users' tab styling on master desk

client/app/scripts/superdesk-archive/views/list.html, client/app/scripts/superdesk-items-common/styles/archive-filtering.less, client/app/scripts/superdesk-items-common/styles/archive-preview.less, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/styles/search.less, client/app/scripts/superdesk-search/tests/tags_spec.js, client/app/scripts/superdesk-search/views/item-search.html, client/app/scripts/superdesk-search/views/item-searchbar.html, client/app/scripts/superdesk-search/views/item-sortbar.html, client/app/scripts/superdesk-search/views/search-facets.html, client/app/scripts/superdesk-search/views/search-results.html, client/app/scripts/superdesk-search/views/search-tags.html, client/app/scripts/superdesk-search/views/search-within.html, client/app/scripts/superdesk-search/views/search.html, client/app/scripts/superdesk/itemList/itemList.js, client/app/scripts/superdesk/itemList/itemList_spec.js, client/app/scripts/superdesk/ui/ui.js, client/app/scripts/superdesk/ui/views/toggle-box.html, client/app/styles/less/sf-additional.less, client/spec/search_spec.js
=> [SD-1801] - Implementing filters for the search

client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-ingest/views/dashboard/ingest-dashboard-widget.html, server/superdesk/errors.py
- navigating from dashboard to ingest provider then modal dialog was not closing.
- Channel message should not displayed if channel is closed or default idle time is set.
- adding provider information to the errors in activity.
=> fix(ingest dashboard): Fixed bugs related to ingest dashboard

client/app/scripts/superdesk-items-common/styles/archive-preview.less
=> fix(package): Fix package item styling

client/app/scripts/superdesk-archive/controllers/list.js, client/app/scripts/superdesk-desks/views/desk_users.html, client/app/scripts/superdesk-desks/views/main.html, client/app/scripts/superdesk/itemList/itemList.js, client/spec/authoring_spec.js, client/spec/helpers/authoring.js, client/spec/helpers/content.js, client/spec/helpers/pages.js, client/spec/helpers/workspace.js, client/spec/master_desk_spec.js, client/spec/send_spec.js, client/spec/users_spec.js, server/apps/prepopulate/app_prepopulate_data.json, server/features/prepopulate.feature
based on #281 and includes some refactorings where helpers page objects are put into separate files
=> e2e test for multi content view

client/app/scripts/superdesk/list/list-directives_spec.js, client/app/scripts/superdesk/list/searchbar-directive.js, client/app/scripts/superdesk/list/views/searchbar.html
it has issues when testing via protractor.
=> fix(list): avoid _.debounce in searchbar directive

client/app/scripts/superdesk-archive/archive-widget/archive.js, client/app/scripts/superdesk/itemList/views/item-list-widget.html
=> fix(content): Fixed open behaviour in widgets.

server/apps/duplication/archive_move.py, server/features/content_move.feature
=> (fix) Archive: Fixed the content move endpoint to allow move between stages within same desk.

client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/styles/highlights.less, client/app/scripts/superdesk-highlights/views/package_highlights_dropdown_directive.html, client/app/scripts/superdesk-highlights/views/settings.html, client/spec/highlights_spec.js, server/apps/archive/archive_composite.py, server/apps/highlights/resource.py, server/apps/highlights/service.py, server/features/highlights.feature, server/features/steps/highlights_steps.py, server/superdesk/__init__.py
=> highlights: populate highlights package when creating it

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-highlights/views/highlights_title_directive.html, client/app/styles/less/variables.less
=> fix(highlights): Fix tooltip display

.gitignore, docker/docker-compose.yml.sh, server/apps/macros.py, server/settings.py
=> remove print_macros call.

client/app/scripts/superdesk-desks/views/aggregate-widget.html
=> fix(desks): Fix desk/stages list ordering

client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/views/highlights_title_directive.html, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk-users/styles/users.less
=> Highlights new

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/spec/authoring_spec.js, client/spec/helpers/workspace.js
on click open content view for that stage
=> feat(authoring): make stage label clickable

client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/views/user-role-items.html, client/app/scripts/superdesk-users/directives_spec.js, client/app/scripts/superdesk-users/tests/users_spec.js, client/app/scripts/superdesk-users/users.js, client/app/scripts/superdesk-users/views/user-list-item.html, server/apps/preferences.py, server/features/preferences.feature, server/features/steps/steps.py
1. Session_Preferences were not deleted from users collection on logout
2. Clear distinction between logged-in and not logged-in users
=> (fix) Hot Fixes

.gitignore, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/article-edit.html, client/app/scripts/superdesk-search/views/item-search.html
=> Show picture and description in authoring screen

client/app/scripts/superdesk-dictionaries/dictionaries.js, client/app/scripts/superdesk-dictionaries/views/settings.html, client/spec/dictionaries_spec.js, client/spec/helpers/dictionaries.js, server/apps/prepopulate/app_prepopulate_data.json
SD-1825 Implement e2e tests for dictionary management
=> e2e tests for dictionary management

client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/tests/desks-spec.js, client/app/scripts/superdesk-desks/views/aggregate-widget.html, client/app/scripts/superdesk/services/preferencesService.js, client/spec/authoring_spec.js, server/apps/preferences.py
use can select which desks/stages should be there
=> feat(authoring): implement multi content view config

client/app/scripts/superdesk-items-common/styles/media-archive.less
- SD-2010 : Styles issues in grid view.
- SD-2009 : Layout issues in search (tags were hidden behind search results.)
=> (fix) Style fixes for search.

client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-archive/family_spec.js, client/app/scripts/superdesk-items-common/styles/media-archive.less
content family_id equals to ingest item _id when its fetched
=> fix(fetch): use item._id as family_id in ingest

client/app/scripts/superdesk-archive/views/media-box-grid.html, client/app/scripts/superdesk/activity/views/activity-list.html
=> fix(archive): Fix styling issues in archive

client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-users/users.js
SD-2017  Add user to desk does not take
=> Fix loading of all users, only the first 200 users were loaded

client/app/scripts/superdesk-archive/views/media-box-grid.html, client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/views/item-search.html, server/apps/aap_mm/__init__.py, server/apps/aap_mm/resource.py, server/apps/aap_mm/service.py, server/apps/search/__init__.py, server/features/aap_mm.feature, server/settings.py, server/superdesk/aap_mm_datalayer.py, server/superdesk/datalayer.py, server/superdesk/io/__init__.py
This PR is for discussion. 
It allows the AAP multimedia archive to be searched in from the global search. It has an additional check that if checked will search  the AAP multimedia archive only!
There is no attempt to merge the results from the elastic search and the multimedia archive as  a) this is hard, b) There is a suggestion that they should not be merged but displayed separately.
It sort of implements a DataLayer and returns a fabricated Eve elastic cursor.
Is this the correct way to architect this?
Should it be a separate end point?
Videos don't work, the item view doesn't work and there is no facility to fetch.
=> [SD-1655] Federated Search

client/app/scripts/superdesk-archive/views/media-box-grid.html, client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk-archive/views/preview.html, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/styles/highlights.less, client/app/scripts/superdesk-highlights/views/highlights_title_directive.html, client/bower.json, client/protractor-conf.js, client/spec/helpers/authoring.js, client/spec/helpers/content.js, client/spec/helpers/setup.js, server/apps/highlights/service.py, server/features/highlights.feature
it has some workarounds for tooltip, once there is new angular bootstrap it can use `tooltip-template` directive
=> feat(highlights): add unmark to highlights tooltip

client/app/scripts/superdesk-highlights/highlights.js
there is a difference in event target
=> fix(highlights): fix unmarking in firefox

server/apps/publish/__init__.py, server/apps/publish/output_channels.py, server/apps/publish/subscribers.py, server/features/output_channels.feature, server/features/steps/steps.py, server/features/subscribers.feature
[SD-2048] - Subscribers end point created
[SD-2047] - Output channels are changed to have list of subscribers
=> Subscribers end point

client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/styles/highlights.less, client/app/scripts/superdesk-highlights/views/settings.html, client/app/styles/less/sf-additional.less
=> fix(highlights): Fix UI for highlights config window

client/app/scripts/superdesk-dashboard/workspace-tasks/styles/tasks.less, client/app/scripts/superdesk-dashboard/workspace-tasks/views/kanban-board.html, client/app/scripts/superdesk-dashboard/workspace-tasks/views/task-preview.html, client/app/styles/less/sf-additional.less
=> fix(tasks): Fix actions on task list and preview

client/app/scripts/superdesk-archive/views/preview.html
SD-2068
Was just duplicated code.
=> fix(preview): Fix right pane preview

client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-publish/styles/publish.less, client/app/scripts/superdesk-publish/views/destination.html, client/app/scripts/superdesk-publish/views/settings.html, client/app/scripts/superdesk-publish/views/subscribers.html
=> feat(publish): Added subscribers settings.

client/app/scripts/superdesk-authoring/views/authoring.html
=> fix(authoring): Fixed big image preview

client/.gitignore, client/app/scripts/superdesk/directives/sdUserAvatar.js, client/app/styles/less/sf-additional.less
=> fix(avatar): Fixed png avatar background problem

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring-sidebar.html, client/app/scripts/superdesk-authoring/views/send-item.html
There was no ticket releated to this issue.
=> fix(authoring): Fix send-to-pane opening / closing

client/app/scripts/superdesk-authoring/styles/authoring.less
=> fix(styles): 'Send to' - fix disabled button style

client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-publish/styles/publish.less, client/app/scripts/superdesk-publish/views/destination-groups.html, client/app/scripts/superdesk-publish/views/output-channels.html, client/app/scripts/superdesk-publish/views/subscribers.html
=> feat(publish): Added subscribers to output channels.

client/app/scripts/superdesk-dictionaries/dictionaries.js, client/app/scripts/superdesk-dictionaries/styles/dictionaries.less, client/app/scripts/superdesk-dictionaries/tests/dictionaries.spec.js, client/app/scripts/superdesk-dictionaries/views/dictionary-config-modal.html, client/app/scripts/superdesk-dictionaries/views/settings.html, client/app/scripts/superdesk/upload/styles/upload.less, client/app/scripts/superdesk/upload/upload.js, client/app/styles/less/forms.less, client/spec/dictionaries_spec.js, client/spec/helpers/dictionaries.js, client/test-main.js, server/apps/dictionaries/resource.py, server/apps/dictionaries/service.py, server/superdesk/validator.py
user can add/remove words from dictionary.
=> feat(dictionary): let user modify existing dictionary

server/requirements.txt, server/superdesk/datalayer.py, server/superdesk/eve_backend.py, server/superdesk/io/commands/remove_expired_content.py, server/superdesk/io/commands/update_ingest_tests.py
If this gets merged, I will update the dependencies: https://github.com/petrjasek/eve-elastic/pull/31
=> Optimize cleaning of expired items by fetching them from mongo, do less elastic calls

server/apps/archive/ingest.py, server/requirements.txt, server/superdesk/eve_backend.py, server/superdesk/io/commands/update_ingest.py
https://dev.sourcefabric.org/browse/SD-2091
=> Use bulk insert for ingesting items to elastic

client/app/docs/styles/main.less, client/app/docs/views/main.html, client/app/styles/less/dropdowns.less
And creating additional structure for n+ nested menus.
=> update(documentation): Updating documentation with nested dropdown menus

server/publicapi/__init__.py, server/publicapi/errors.py, server/publicapi/tests/__init__.py, server/publicapi/tests/errors_test.py
Add a first few public API Error classes.
=> Define a first few public API errors

client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-publish/views/destination.html, client/app/scripts/superdesk-publish/views/ftp-config.html, server/apps/archive/archive.py, server/apps/publish/archive_publish.py, server/apps/publish/publish_queue.py, server/settings.py, server/superdesk/celery_task_utils.py, server/superdesk/errors.py, server/superdesk/io/commands/update_ingest.py, server/superdesk/io/commands/update_ingest_tests.py, server/superdesk/publish/__init__.py, server/superdesk/publish/ftp.py, server/superdesk/publish/ftp_tests.py, server/superdesk/publish/publish_content.py, server/superdesk/publish/publish_service.py
[SD-2092] FTP transmission 
[SD-2089] Celery tasks for publishing
Also:
- Refactoring of the celery tasks locking
- Added FTP transmission type to UI dropdown
- Archive Auto-save schema change to accept destination groups
- First few publish errors are created
=> Celery tasks for publishing (transmitting)

client/app/docs/views/main.html, client/app/styles/less/dropdowns.less
There is no task in JIRA, this is just improvement for dropdown menu.
=> update(documentation): Added arrows on nasted dropdown elements

client/app/scripts/superdesk-authoring/widgets/views/authoring-widgets.html, client/app/styles/less/layouts.less, client/spec/helpers/authoring.js
=> feat(tooltips): Custom tooltips on side-tabs in Editor screen

client/app/scripts/superdesk-authoring/views/authoring-topbar.html
=> fix(tooltips): Added custom tooltips on subnav buttons

client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/views/aggregate-widget.html, client/app/scripts/superdesk-desks/views/stage-item-list.html, client/spec/authoring_spec.js, client/spec/users_spec.js
implement search field in aggregate widget
=> feat(authoring): simple search in aggregate view

client/app/scripts/superdesk-desks/desks.js
in case an item is send to a different stage, both previous and new stage lists will refresh
requires https://github.com/superdesk/eve/pull/19
=> feat(content): sync multi content view

client/app/scripts/superdesk-desks/styles/desks.less, client/app/scripts/superdesk-desks/views/main.html, client/app/scripts/superdesk-users/views/list.html, client/app/styles/less/sf-additional.less
=> fix(online users): Styled checkbox for online users

client/app/scripts/superdesk-dashboard/workspace-tasks/tasks.js, server/apps/tasks.py, server/requirements.txt
it will reload content for both previous and next stage
includes required eve update
=> feat(multi-content): refresh stages when item is sent

client/app/scripts/superdesk-packaging/views/search-widget-preview.html, client/spec/authoring_spec.js
it was broken after using `controller as`
=> fix(multi-content): fix item preview in multi content widget

client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html, client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/views/actionpicker.html, client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-publish/styles/publish.less, client/app/scripts/superdesk-publish/views/destination-groups.html, client/app/scripts/superdesk-publish/views/ftp-config.html, client/app/scripts/superdesk-publish/views/output-channels-selectors.html, client/app/scripts/superdesk-publish/views/output-channels.html, client/app/scripts/superdesk/views/sdSearchList.html, client/app/styles/less/bootstrap.less, client/app/styles/less/search-list.less
=> fix(publish): Fixed publish styling and various minor problems.

client/app/scripts/superdesk-users/users.js, client/app/scripts/superdesk-users/views/user-preferences.html, client/app/scripts/superdesk/api/api-service.js, client/app/scripts/superdesk/services/preferencesService.js, client/app/scripts/superdesk/services/preferences_spec.js, server/apps/preferences.py, server/features/preferences.feature, server/superdesk/activity.py
and make sure we use defined label/category not what gets saved into
db so this change will work also for existing users
=> fix(preferences): hide preferences without label from ui

server/apps/preferences.py
=> fix(preferences): fix typeerror when getting preferences

client/app/scripts/superdesk-desks/views/user-role-items.html, client/app/scripts/superdesk-users/views/edit-form.html, client/app/styles/less/dropdowns.less, client/app/styles/less/modals.less
=> fix(style issue): Fixed styled issue on user tab in master desk.

server/publicapi/items/__init__.py, server/publicapi/items/resource.py, server/publicapi/items/service.py, server/publicapi/tests/items_resource_test.py
This PR slightly improves a few tests, does some cleanup and adds some docstring comments.
=> Do some minor improvements of the /items API endpoint code.

server/publicapi/__init__.py, server/publicapi/items/service.py, server/publicapi/packages/__init__.py, server/publicapi/packages/resource.py, server/publicapi/packages/service.py, server/publicapi/tests/packages_init_app_test.py, server/publicapi/tests/packages_resource_test.py, server/publicapi/tests/packages_service_test.py
Please have a closer look at the `package` schema definition and verify it, thanks!
=> Add /packages endpoint to public API

server/superdesk/io/commands/update_ingest.py
eg search providers have no service to update
sentry 11609
=> fix(ingest): check if provider has service to update

client/app/scripts/superdesk-dictionaries/dictionaries.js, client/app/scripts/superdesk-dictionaries/tests/dictionaries.spec.js, client/app/scripts/superdesk-dictionaries/views/dictionary-config-modal.html, client/app/scripts/superdesk/upload/upload.js, client/app/scripts/superdesk/upload/upload.spec.js, client/app/styles/less/forms.less
and set form as invalid in case it's not plain text
=> fix(dictionaries): validate dictionary file type

server/apps/preferences.py, server/apps/preferences_test.py
there was an error for preference which were a list of items
=> fix(preferences): fix fetching preferences

client/app/scripts/superdesk-archive/views/list.html, client/app/scripts/superdesk-highlights/views/package_highlights_dropdown_directive.html, client/app/scripts/superdesk-search/views/search-results.html, client/app/styles/less/dropdowns.less, client/spec/helpers/content.js
=> fix(tooltip): Added custom tooltip on list/grid button

client/app/scripts/superdesk/editor/views/editor.html
There is no task in JIRA for this.
=> fix(spell check): Fixed text uppercase on dropdown suggestion tooltip

client/app/scripts/superdesk/activity/views/activity-list.html, client/app/styles/less/dropdowns.less
=> fix(nested menu): Fixed nested dropdown menu in sidebar

client/app/scripts/superdesk/itemList/views/item-list-widget.html
There is no taks in JIRA for this.
=> fix(icons): Change icon on widget for opening to edit mode

client/app/scripts/superdesk-authoring/versioning/versions.js, client/app/scripts/superdesk-authoring/versioning/views/versions.html, client/app/scripts/superdesk-workspace/content/content.js, server/apps/archive/archive.py, server/apps/archive/common.py, server/apps/archive/user_content.py, server/apps/item_lock/components/item_lock.py, server/apps/tasks.py, server/features/archive.feature, server/features/content_lock.feature, server/features/user_content.feature, server/requirements.txt
when creating an item set its revision to 0
and filter those from content list and versions list
=> fix(archive): remove empty revisions

server/apps/preferences.py, server/features/preferences.feature, server/features/steps/steps.py
it should used predefined label and category, not the one from db
=> fix(preferences): force preference label/category on update

client/app/scripts/superdesk-ingest/views/settings/ingest-routing-filter.html
=> fix(tooltip): Added tooltips in filter section of the routing schemes.

client/app/scripts/superdesk-authoring/multiedit/tests/multiedit_spec.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.spec.js, client/test-main.js, server/apps/dictionaries/dictionaries_test.py, server/apps/dictionaries/service.py
=> fix(spellcheck): allow words with numbers in dictionary

client/app/scripts/superdesk-dashboard/styles/dashboard.less
=> fix(widget): Widget dropdown partly cut

client/app/scripts/superdesk-authoring/styles/authoring.less
=> fix(text formating): Bottom part of edit area is not reachable

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/send-item.html
=> fix(fetch): Fixed fetch-as panel header.

client/app/scripts/superdesk-search/styles/search.less, client/app/scripts/superdesk-search/views/multi-action-bar.html, client/spec/content_spec.js, client/test-main.js
=> fix(tooltip): Added custom tooltip on multi edit icon

README.md
=> added steps to install newest docker

client/app/scripts/superdesk/itemList/itemList.js, client/app/scripts/superdesk/itemList/itemList_spec.js
=> fix(widget): Fixed content widget search.

client/app/scripts/superdesk-archive/controllers/list.js, client/app/scripts/superdesk-authoring/authoring.js, server/apps/publish/archive_publish.py, server/features/content_publish.feature, server/superdesk/publish/publish_content.py
Supposed to use `updates` branch. But there were some issues and big pending PR, that's the reason used `master` branch for this feature.
=> (feat) [SD-1989] Content can be queued to a publishing channel that is closed

client/app/scripts/superdesk/analytics/analytics.js, client/app/scripts/superdesk/analytics/analytics_spec.js, client/app/scripts/superdesk/filters.js
Because using the label to generate the link is not always relevant
=> Use route.href to build the link of the `main link`

client/app/scripts/superdesk-highlights/views/settings.html, client/app/scripts/superdesk-ingest/views/settings/ingest-sources-content.html, client/app/styles/less/modals.less
=> Fix (mozilla scroll): Fixed problem with min-height n mozilla browser

client/app/scripts/superdesk-highlights/views/package_highlights_dropdown_directive.html
=> fix(rename label): Rename label for highlight items

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/send-item.html
=> fix(send-to-pane): Fixed structure in send to pane on ingest dashboard.

client/app/scripts/superdesk-ingest/styles/dashboard.less
=> Fix (error word break): Fixed word break on ingest dashboard error

client/app/scripts/superdesk-archive/views/metadata-view.html, client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html
=> Fix (Label change): Label First created changed to created

client/app/scripts/superdesk-authoring/views/article-edit.html, client/app/scripts/superdesk-items-common/styles/archive-preview.less, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-packaging/views/sd-package-item-preview.html
there is a red border for locked and green for published items
in package authoring
=> feat(package): show lock/publish status of items in package

client/app/scripts/superdesk-items-common/styles/archive-preview.less
=> Fix (edit package style): Fixed close icon position on package edit

client/app/scripts/superdesk-authoring/metadata/metadata.less, client/app/scripts/superdesk-authoring/metadata/views/metadata-terms.html, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/widgets/widgets-article.less, client/app/scripts/superdesk-desks/styles/desks.less, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/styles/less/sf-additional.less
There is no task in JIRA for this, this are just small bugs and updates of current styles in whole project, not specific section.
=> fix(style issues): Fixed small css issues

client/tasks/options/files.js, client/tasks/options/nggettext_extract.js, client/tasks/options/watch.js
- it will skip watching bower component files
=> fix(grunt): fix grunt config for watch

client/app/scripts/superdesk-authoring/styles/themes.less
there was firefox specific issue with img max-width: 100%, added a workaround
=> fix(multiedit): fix image size in multiedit

server/apps/archive/commands.py, server/apps/prepopulate/app_initialize.py, server/apps/publish/__init__.py, server/apps/publish/archive_publish_tests.py, server/apps/publish/commands.py, server/apps/publish/published_item.py, server/apps/text_archive/text_archive.py, server/settings.py
=> Publish expired items and move item to text archive.

client/app/scripts/superdesk/editor/editor.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.js
there were some changes going on keydown, not it only happens on input
=> fix(authoring): fix backspace/delete behaviour

client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/views/desk-config-modal.html
=> fix(macros navigation): Added navigation for Macros tab on Desk dialog

server/apps/archive/__init__.py, server/apps/archive/archive_composite.py, server/apps/archive/archive_link.py, server/apps/content.py, server/features/content_link.feature, server/features/steps/steps.py
Please ignore all the logging, it's going to be removed before creating the PR to master.
=> Initial support for takes packaging

server/apps/archive/archive_composite.py, server/apps/archive/archive_link.py, server/features/content_link.feature, server/features/steps/steps.py
@mdhaman @akintolga This is to be able to integrate.
=> Save and continue in succession.

client/app/scripts/superdesk-archive/views/fetched-desks.html, client/app/scripts/superdesk-items-common/styles/media-archive.less
=> fix(fetched item): FIxed overlaping text when someone fetch item

client/app/scripts/superdesk/activity/activity.js
SD-1877
I'm not sure if there is better way to check if previousRoute is packaging
=> Fix (package item close): On item close, return to package

server/apps/prepopulate/app_initialize.py, server/apps/prepopulate/data_initialization/validators.json, server/apps/publish/archive_publish.py, server/apps/validate/__init__.py, server/apps/validate/validate.py, server/apps/validators/__init__.py, server/apps/validators/command.py, server/apps/validators/tests.py, server/apps/validators/validators.py, server/features/auto_routing.feature, server/features/content_link.feature, server/features/content_publish.feature, server/features/publish_queue.feature, server/features/validate.feature, server/settings.py
The validators will need to be loaded after or as part of the deployment
=> [SD-2166] Validate mandatory fields before publishing

client/app/scripts/superdesk-packaging/packaging.js
=> Fix(create empty package)

client/app/scripts/superdesk-desks/styles/desks.less, client/app/scripts/superdesk-desks/views/stage-item-list.html, client/spec/authoring_spec.js
=> feat(authoring): Added timestamp to aggregate widget items.

client/app/scripts/superdesk/editor/editor.js
=> fix(authoring): fixed find/replace widget.

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-packaging/packaging.js, server/apps/publish/archive_publish.py, server/apps/publish/archive_publish_tests.py, server/apps/publish/formatters/__init__.py, server/apps/publish/formatters/nitf_formatter.py, server/features/auto_routing.feature, server/features/content_link.feature, server/features/content_publish.feature, server/superdesk/errors.py
With this PR:
- If nothing is queued after publishing an error will be thrown
- If the output channel can't format the story then a warning will be displayed on client
=> [SD-2205] - Formatter compatibility

client/app/scripts/superdesk-desks/styles/desks.less
=> fix(overlapping text): Fixed problem with overlapping text in Firefox

client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-publish/views/publish-queue.html, client/app/scripts/superdesk/filters.js
1. Timestamps should be resolved/displayed to seconds.
2. Items are not being displayed in sequence number order
=> (imp) [SD-2318] Minor fixes for publish queue display:

client/app/scripts/superdesk-archive/tests/archive_spec.js, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/sd-content-create.html, client/app/scripts/superdesk-workspace/content/content.js
=> feat(content): Added creating content item from template.

client/app/scripts/superdesk-authoring/metadata/metadata.js, server/apps/archive/archive.py, server/apps/prepopulate/data_initialization/validators.json
- Formatting issue in date picker
- Descheduling was not working
- Urgency validation allowed values are added
=> [SD-2337][SD-2346] - Scheduled publish fixes

client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-templates/templates.js, client/app/scripts/superdesk/editor/editor.js, client/app/scripts/superdesk/editor/editor.spec.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.spec.js, client/app/styles/less/bootstrap.less, client/bower.json, server/apps/archive/archive.py
there is a new submenu where you can toggle it on/off and in case
it's off you can run it from there too.
=> feat(spellcheck): let user turn spellcheck on and off

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/sd-content-create.html, client/app/scripts/superdesk-authoring/views/sd-template-select.html
=> feat(content): Added template list modal.

server/publicapi/features/items.feature, server/publicapi/items/__init__.py, server/publicapi/items/resource.py, server/publicapi/items/service.py, server/publicapi/packages/resource.py, server/publicapi/tests/items_service_test.py, server/publicapi/tests/packages_resource_test.py
Resolves [SD-2253](https://dev.sourcefabric.org/browse/SD-2253).
=> Public API: Allow excluding content fields from the result ("projection")

client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-items-common/styles/archive-filtering.less, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/views/item-search.html
=> feat(iptc search): Integrate structure on search panel

client/app/scripts/superdesk-templates/views/templates.html
=> fix(settings): Fixed creating templates.

client/app/scripts/superdesk/list/list.js, client/app/scripts/superdesk/services/asset.js
Please take care of using `asset` to link templates
=> list.js: Use asset to make links to templates

server/publicapi/items/service.py, server/publicapi/tests/items_service_test.py
When retrieving collections of items/packages, `Eve` builds the "self" link from the actual query sent to MongoDB behind the scenes instead of using the actual request URL. This PR fixes this.
Resolves [SD-2331](https://dev.sourcefabric.org/browse/SD-2331).
=> public API: fix "self" HATEOAS link for collections

client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk/editor/editor.js, client/app/scripts/superdesk/keyboard/keyboard.js, client/app/scripts/superdesk/keyboard/tests/keyboard.spec.js, client/app/styles/less/navs.less
it can be triggered via ctrl+shift+s
=> feat(spellcheck): add keyboard shortcut for spellcheck

client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-desks/styles/aggregate-widget.less, client/app/scripts/superdesk-desks/views/aggregate-widget-production.html, client/app/scripts/superdesk-production/production.js, client/app/scripts/superdesk-production/production.spec.js, client/app/scripts/superdesk-production/styles/production.less, client/app/scripts/superdesk-production/views/production.html, client/app/scripts/superdesk/menu/views/menu.html
splitting the screen on top (to have 2 subnavs)
=> implement compact switch

server/apps/desks.py, server/apps/stages.py, server/apps/users/services.py, server/apps/users/users_test.py, server/features/desks.feature, server/features/role.feature, server/features/stages.feature, server/features/user.feature
=> [SD-2025] - Notifications on setting changes

client/app/scripts/superdesk-dashboard/workspace-tasks/tasks.js
seems like a bug in jshint, after moving the function it's ok
=> fix(ci): fix jshint error

client/app/scripts/superdesk/editor/editor.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.js
=> Fix (backspace on edit): Fix for chrome

client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk/activity/activity-list-directive.js, client/app/scripts/superdesk/activity/views/activity-list.html, client/app/styles/less/dropdowns.less, client/spec/fetch_spec.js
=> fix(media icons): Icons appearing outside of items frame

client/spec/search_spec.js
=> feat(e2e test): Added e2e test for subject codes

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/sd-content-create.html, client/app/scripts/superdesk-templates/templates.js, client/app/scripts/superdesk-templates/templates.spec.js, client/app/scripts/superdesk-templates/views/templates.html
=> feat(templates): Separated templates by desks.

client/app/scripts/superdesk-desks/styles/desks.less, client/app/scripts/superdesk-desks/views/stage-item-list.html
=> Fix (Search list scroll)

client/app/scripts/superdesk-archive/views/media-box-grid.html, client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk-archive/views/metadata-view.html, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html, client/app/scripts/superdesk-authoring/multiedit/multiedit.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-dashboard/workspace-tasks/views/desk-stages.html, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk-packaging/packaging.js, client/app/styles/less/sf-additional.less
- Fixing the not for publication flag.
- Strip html from the headline and abstract
- Fixing the unit test.
=> (fix) Authoring: Minor fixes

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-items-common/styles/media-archive.less
[SD-2474] [SD-2263] [SD-2305] [SD-2357]
=> (fix) Authoring: Fixes related to authoring for actions and not for publication.

client/app/scripts/superdesk-authoring/styles/themes.less
=> Fix(fixed style for Headline and Abstract for firefox)

client/app/scripts/main.js, client/app/scripts/superdesk-archive/controllers/baseList.js, client/app/scripts/superdesk-archive/controllers/list.js, client/app/scripts/superdesk-archive/module.js, client/app/scripts/superdesk-archive/tests/archive_spec.js, client/app/scripts/superdesk-archive/views/media-box-grid.html, client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/macros/macros.js, client/app/scripts/superdesk-authoring/views/send-item.html, client/app/scripts/superdesk-ingest/ingest.spec.js, client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/views/multi-action-bar.html, client/app/scripts/superdesk-search/views/search-results.html, client/spec/fetch_spec.js, client/spec/helpers/content.js, client/spec/helpers/workspace.js, server/apps/duplication/archive_fetch.py, server/apps/macros.py, server/features/macros.feature
implementing multi fetch + fetchAs
=> Feat multi fetch

client/app/scripts/superdesk-desks/aggregate.js, client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/tests/aggregate-spec.js, client/app/scripts/superdesk-desks/tests/desks-spec.js, client/app/scripts/superdesk-desks/views/aggregate.html, client/test-main.js
=> feat(authoring): Implemented saving/loading state to aggregate widget.

client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk-authoring/authoring.js
=> (fix) Authoring: Fixing the bug where activity icons were not displayed for published content in list view

client/app/scripts/superdesk-desks/views/desk-config-modal.html
[SD-2496] - Revert the changes for Published Stage
=> fix(expiry) - Publish expiry had been removed mistakenly

server/apps/templates/content_templates.py, server/features/templates.feature
so that template can be set from desk template to personal
=> fix(templates): let client send template desk=null

client/app/scripts/superdesk-dashboard/sd-widget-directive.js, client/app/scripts/superdesk-dashboard/views/configuration.html, client/app/scripts/superdesk-desks/aggregate-widget/configuration.html, client/app/scripts/superdesk-desks/aggregate.js, client/app/scripts/superdesk-desks/views/aggregate-settings-configuration.html, client/app/scripts/superdesk-desks/views/aggregate-settings.html, client/app/styles/less/modals.less
=> fix(multi content config): Fixed problem on closing multi content configuration modal

client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-archive/views/fetched-desks.html, client/app/scripts/superdesk-dashboard/module.js, client/app/scripts/superdesk-items-common/styles/media-archive.less
=> Fix (item fetched by multiple desks looks)

client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-publish/styles/publish.less, client/app/scripts/superdesk-publish/tests/publish_spec.js, client/app/scripts/superdesk-publish/views/publish-queue.html, client/app/styles/less/tables.less
=> feat(publish queue page): Design implementation for publish queue page

server/superdesk/io/rss.py, server/superdesk/io/rss_test.py
I would like to get feedback on handling the image download errors - should we silently ignore them and simply exclude these images from the result, or should we perhaps raise an error and completely abort the ingesting of an RSS entry as a content package?
=> RSS ingest: add a method for fetching remote images from given URLs

client/app/scripts/superdesk-desks/aggregate-widget/configuration.html, client/app/scripts/superdesk-desks/aggregate.js
There is no task in Jira for, this is update for task releated to workspace multi content modal
=> fix(multi content config close): Fix closing button on multi content config modal

client/app/scripts/superdesk-archive/views/metadata-view.html, client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html, client/app/scripts/superdesk-authoring/views/article-edit.html
=> fix(authoring): Moved signoff to metadata.

server/superdesk/io/rss.py, server/superdesk/io/rss_test.py
This PR creates the actual content package from the RSS item and the images it references.
I would need to know though if the dictionary created in the `_wrap_into_package` method is correct, as well as how to resolve several TODOs I placed in it (hence the missing unit tests for this method).
Thanks for all the feedback in advance!
SD-2482
=> [WIP] RSS ingest: create a package if RSS entry contains links to images

client/app/docs.html
@pavlovicnemanja92 that should do the trick
=> fix(docs): fix docs page

client/app/scripts/superdesk-authoring/styles/themes.less, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/styles/less/layouts.less
=> Fix (metadata scroll and long abstract overlapping)

server/apps/messaging/__init__.py, server/apps/messaging/chat_session.py, server/apps/messaging/commands.py, server/apps/messaging/messages.py, server/apps/messaging/messages_test.py, server/features/messaging.feature, server/settings.py, server/superdesk/services.py
=> (feat) SD-1637 - Messaging (Backend)

client/app/scripts/superdesk-archive/controllers/baseList.js, client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/send-item.html
SD-2526 and small css fix for SD-2419
=> fix(duplicate): Closing modal after duplicate action

client/app/scripts/superdesk/editor/editor.js
make editor listen to blur events and not only input
=> fix(editor): after find/replace trigger model update

server/apps/messaging/chat_session.py, server/features/messaging.feature
This adds capability to find chat sessions which a user is participating.
=> [SD-2426] De-normalizing recipients on every create and update.

client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk/list/list.js
=> Search delete

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/sd-content-create.html, client/app/scripts/superdesk-templates/templates.js, client/app/scripts/superdesk-templates/templates.spec.js, client/app/scripts/superdesk-workspace/content/content.js, server/apps/preferences.py
Tests and fix for broken tests coming soon.
=> Recent templates

client/app/scripts/superdesk-archive/views/fetched-desks.html
=> Fix (improved fethed items looks)

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/metadata/views/metadata-dropdown.html, client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html, client/app/styles/less/sf-additional.less, server/apps/archive/archive.py
1. Auto-Save fails when user changes Urgency or Priority or ANPA Category fields in the Metadata Widget
2. User can't de-select the Subject or Place or Genre in the Metadata Widget
3. Article in Auto-save isn't deleted  when user clicks on 'Ignore' button in authoring screen
4. In large preview, for publishable articles it shows as 'Not for Publication' in Metadata Widget
=> (fix) [SD-2592] Issues in Authoring

client/app/scripts/superdesk-archive/views/preview.html, client/app/scripts/superdesk-items-common/styles/archive-preview.less, client/app/scripts/superdesk/activity/activity-list-directive.js, client/app/scripts/superdesk/activity/views/activity-list.html
=> fix(search): Empty dropdown on preview pane on search page

client/app/scripts/superdesk-authoring/views/article-edit.html, client/app/scripts/superdesk-dictionaries/dictionaries.js, client/app/scripts/superdesk-dictionaries/tests/dictionaries.spec.js, client/app/scripts/superdesk-dictionaries/views/dictionary-config-modal.html, client/app/scripts/superdesk-dictionaries/views/settings.html, client/app/scripts/superdesk/editor/editor.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.spec.js, client/app/scripts/superdesk/editor/views/editor.html, client/app/styles/less/sf-additional.less, client/bower.json, server/apps/dictionaries/resource.py, server/apps/dictionaries/service.py, server/apps/spellcheck/spellcheck.py, server/features/dictionaries.feature, server/features/spellcheck.feature, server/features/stages.feature, server/features/steps/steps.py, server/features/user.feature, server/superdesk/notification_mock.py
user can add word that is not part of global dictionaries
into their personal dictionaries. there can be one dictionary
per user and language.
=> feat(dictionary): add word to user dict in authoring

client/app/scripts/superdesk-search/styles/search.less
=> fix(search page): Fixed leak of left menu on search and legal archive

client/app/scripts/superdesk-desks/aggregate-widget/configuration.html
=> fix(monitoring close button): Closing modal on monitoring widget not working

client/app/scripts/superdesk-users/users.js, client/app/styles/less/modals.less, client/app/styles/less/sf-additional.less
=> Fix (mentioned users scroll and modal window hide animation)

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/send-item.html, client/app/scripts/superdesk/editor/spellcheck/spellcheck.js, client/spec/helpers/authoring.js, client/spec/send_spec.js
SD-2154
Closed previous pull request because of error while making synchronization.
https://github.com/superdesk/superdesk/pull/764
=> feat(spelling): Warning message if there are spelling mistakes when sending item

server/apps/prepopulate/data_initialization/validators.json, server/apps/publish/archive_publish.py, server/apps/publish/archive_publish_tests.py, server/apps/validate/validate.py, server/apps/validators/validators.py, server/features/auto_routing.feature, server/features/content_link.feature, server/features/content_publish.feature, server/features/publish_publicapi.feature, server/features/publish_queue.feature, server/features/validate.feature
This PR will require that the validators collection be deleted and re-created using the command 
python manage.py app:initialize_data -n validators
=> [SD-2614] Add validators for picture and video items

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/authoring-topbar.html
=> Fix (on click unlock button is disabled)

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring-container.html, client/app/scripts/superdesk-authoring/views/authoring.html, client/app/scripts/superdesk-desks/aggregate.js, client/app/scripts/superdesk-monitoring/monitoring.js, client/app/scripts/superdesk-monitoring/monitoring.spec.js, client/app/scripts/superdesk-monitoring/views/monitoring-group.html, client/app/scripts/superdesk-monitoring/views/monitoring.html, client/app/scripts/superdesk-packaging/packaging.js
you can activate it via dbl clicking an item in the list
=> feat(monitoring): add authoring sidebar

client/app/styles/less/sf-additional.less
=> fix(routing scheme): Fix issue for pills list on routing scheme

server/superdesk/aap_mm_datalayer.py
=> [SD-2615] keep the original download link to to multimedia item in the renditions

client/app/scripts/superdesk-ingest/module.js
=> fix(ingest widget): Fix label overlapping on ingest widget

client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-publish/views/publish-queue.html
=> feat(publish): Implemented publish queue preview sidebar.

client/app/scripts/superdesk-archive/archive-widget/archive.js, client/app/scripts/superdesk-archive/related-item-widget/relatedItem.js, client/app/scripts/superdesk-authoring/comments/comments.js, client/app/scripts/superdesk-authoring/editor/find-replace.js, client/app/scripts/superdesk-authoring/macros/macros.js, client/app/scripts/superdesk-authoring/packages/packages.js, client/app/scripts/superdesk-authoring/versioning/versions.js, client/app/scripts/superdesk-desks/aggregate.js, client/app/scripts/superdesk-ingest/ingest-widget/ingest.js, client/app/scripts/superdesk-packaging/packaging.js
=> Fix (order of right and left items is fixed)

client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-archive/views/related-view.html, client/app/scripts/superdesk-items-common/styles/archive-preview.less
=> fix(related items): Added links for related items

client/app/scripts/superdesk-items-common/styles/archive-preview.less, client/app/scripts/superdesk-packaging/views/sd-package-item-preview.html
=> fix(media items): Fix link for preview of media icons from package

client/app/styles/less/layouts.less
=> fix(menu bar): Fix displace of top bar after opening menu bar

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/metadata/metadata.less, client/app/scripts/superdesk-authoring/metadata/views/metadata-dropdown.html, client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html, client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-publish/views/subscribers.html, server/apps/archive/common.py, server/apps/content.py, server/apps/prepopulate/data_initialization/vocabularies.json, server/apps/publish/archive_publish.py, server/apps/publish/archive_publish_tests.py, server/apps/publish/subscribers.py, server/apps/vocabularies/vocabularies.py, server/features/content_link.feature, server/features/content_publish.feature, server/features/publish_publicapi.feature, server/features/publish_queue.feature, server/features/subscribers.feature, server/settings.py, server/superdesk/emails/__init__.py, server/superdesk/templates/article_killed.html, server/superdesk/templates/article_killed.txt
[SD-2579] SPIKE - Investigate output channels and subscriber design
[SD-2608] Modify the Subscriber Endpoint and Management Screen to meet new business requirement
[SD-2609] Changes to Authoring UI	 Technical task
[SD-2611] Modify the publishing workflow
[SD-2643] Error 400 thrown on adding new subscriber when SEQUENCE NUMBER SETTINGS are not specified
`Need to run vocabularies command after the PR is merged`
=> (imp) SD-2579

client/app/scripts/superdesk-desks/aggregate.js, client/app/scripts/superdesk-desks/tests/aggregate-spec.js, client/app/scripts/superdesk-desks/views/aggregate.html, client/app/scripts/superdesk-desks/views/stage-header.html
=> feat(authoring): Implemented solo mode for monitoring widget.

client/app/scripts/superdesk-archive/archive-widget/archive.js, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk/activity/activity.js, client/spec/multicontent_spec.js
SD-2022 AND SD-2087
Open for suggestions!
=> fix(closing items): Closing item that was opened from left search panel should return to initial state

client/app/scripts/superdesk-publish/filters/publish-filters.js, server/apps/publish/publish_filters/__init__.py, server/apps/publish/publish_filters/publish_filter.py, server/features/publish_filter.feature, server/features/publish_filter_tests.feature
- Also refactored the unique name check in publish filter
=> [SD-2665] - Testing publish filters against production stories

client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/spec/helpers/authoring.js, client/spec/package_spec.js, docker-compose.yml, docker/docker-compose.yml, server/fig.yml, server/settings.py
mongolab was used long time ago. no need to have 2 envs for mongo. error prone..
=> fix(bamboo): use MONGO_URI env and not MONGOLAB for config

.travis.yml, docker/docker-compose.yml, scripts/get-chrome-url, server/apps/publicapi_publish/items.py, server/apps/publicapi_publish/packages.py, server/publicapi/settings.py, server/settings.py, server/superdesk/tests.py
instead of hardcoded version use devel channel to stay up to date
=> test(travis): use beta chrome for testing

client/app/scripts/superdesk-archive/views/metadata-view.html, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/metadata/metadata.less, client/app/scripts/superdesk-authoring/metadata/views/metadata-dropdown.html, client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html, client/app/scripts/superdesk-publish/views/subscribers.html, client/app/scripts/superdesk/filters.js, server/apps/archive/common.py, server/apps/prepopulate/data_initialization/vocabularies.json, server/apps/publish/archive_publish.py, server/apps/publish/archive_publish_tests.py, server/apps/publish/formatters/aap_bulletinbuilder_formatter_tests.py, server/apps/publish/formatters/aap_ipnews_formatter_test.py, server/apps/publish/formatters/anpa_formatter_test.py, server/apps/publish/subscribers.py, server/features/content_link.feature, server/features/content_publish.feature, server/features/publish_publicapi.feature, server/features/publish_queue.feature, server/features/subscribers.feature, server/superdesk/publish/file_output_tests.py, server/superdesk/publish/odbc_test.py, server/superdesk/publish/publish_service_tests.py
Need to update vocabularies after this ticket it merged.
=> (feat) [SD-2573] Restricting content delivery based on subscriber metadata

server/apps/packages/takes_package_service.py, server/apps/publish/archive_publish.py, server/apps/publish/archive_publish_tests.py, server/features/content_link.feature, server/features/content_publish.feature, server/features/publish_publicapi.feature, server/features/publish_queue.feature, server/features/steps/steps.py, server/superdesk/tests.py
=> Package story as a take when sending to digital subscribers

client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/tests/desks-spec.js
Resolves [SD-2702](https://dev.sourcefabric.org/browse/SD-2702).
=> Fix error in desks.getCurrentDeskId() on empty user desks list

server/superdesk/io/rfc822.py, server/superdesk/io/rfc822_parser_test.py
https://dev.sourcefabric.org/browse/VRFPXL-23
=> Fix parsing 'from' field in e-mail ingest

client/app/scripts/superdesk-dictionaries/dictionaries.js, client/app/scripts/superdesk-dictionaries/tests/dictionaries.spec.js, client/app/scripts/superdesk-workspace/workspace.js, client/app/scripts/superdesk/editor/editor.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.spec.js
instead of keeping it in memory it's reloaded when opening authoring.
=> fix(spellcheck): reload dicts when editing

server/apps/publish/archive_publish.py, server/apps/publish/archive_publish_tests.py, server/features/content_publish.feature
Killing a takes package kills all takes
- Send kill transmission for individual takes
- One broadcast email to all subscribers per kill
- Send kill transmission for takes package
=> [SD-2676] Killing a takes package kills all takes

client/app/scripts/superdesk-publish/publish.js, server/apps/publish/archive_publish.py, server/apps/publish/publish_filters/filter_condition.py, server/apps/publish/subscribers.py
1. Checking for Multiple Categories in Publish Filters. 
2. Allowing None when user deselects publish filter in Subscribers.
=> (fix) [SD-2626] 

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/widgets/views/authoring-widgets.html, client/app/scripts/superdesk-authoring/widgets/widgets.js, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-search/views/search-results.html, client/spec/fetch_spec.js, client/spec/highlights_spec.js, client/spec/package_spec.js, client/spec/search_spec.js
but only on the right side.
+ re-enable e2e tests and fix a few issues there
=> fix(authoring): show widgets in embedded authoring

client/app/scripts/superdesk-users/users.js, client/app/scripts/superdesk/activity/activity-list-directive.js
there was recursive watch on each user in list plus it was fetching
users multiple times at the same time.
=> fix(users): fix user list performance

client/app/scripts/superdesk/services/modalService.js
Continues https://github.com/superdesk/superdesk/pull/648
=> Closing a modal with the overlay: use the model variable

client/app/scripts/superdesk/auth/auth.js
seems working with asset now @vied12
=> fix(auth): use asset for reset password template

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/metadata/views/metadata-terms.html, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring.html, client/app/scripts/superdesk-authoring/views/header-info.html, client/app/scripts/superdesk-authoring/widgets/widgets.js, client/app/scripts/superdesk/directives/all.js, client/app/scripts/superdesk/directives/sdSlider.js, client/app/scripts/superdesk/directives/sdTypeahead.js, client/app/scripts/superdesk/menu/styles/menu.less, client/app/scripts/superdesk/views/sdSlider.html, client/app/scripts/superdesk/views/sdTypeahead.html, client/app/styles/less/forms.less
=> feat (header): Improve the header information

client/app/scripts/superdesk-archive/module.js, client/app/scripts/superdesk-dashboard/views/workspace-sidenav.html, client/app/scripts/superdesk-dashboard/views/workspace-topnav.html, client/app/scripts/superdesk-dashboard/views/workspace.html, client/app/scripts/superdesk-dashboard/workspace-tasks/views/workspace-tasks.html, client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-legal-archive/views/legal_archive.html, client/app/scripts/superdesk-monitoring/views/monitoring-view.html, client/app/scripts/superdesk-search/views/search.html, client/app/scripts/superdesk-workspace/workspace.js, client/app/scripts/superdesk/menu/menu.js, client/app/scripts/superdesk/menu/styles/menu.less, client/app/styles/less/layouts.less
there are no icons for ingest/content, it's rotated text atm.
also changed css so when there is route with sidebar it handles
main container position instead of positioning ng-view contents.
SD-2788
=> fix(workspace): move links from top bar to side bar

client/app/scripts/superdesk-archive/tests/archive_spec.js, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-authoring/workqueue/workqueue.js, client/app/scripts/superdesk-workspace/content/content.js
=> Fix (saving previous before opening new item)

client/app/scripts/superdesk-archive/views/list.html, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/multiedit/views/multiedit.html, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring.html, client/app/scripts/superdesk-authoring/views/dashboard.html, client/app/scripts/superdesk-authoring/workqueue/tests/workqueue_spec.js, client/app/scripts/superdesk-authoring/workqueue/workqueue.js, client/app/scripts/superdesk-dashboard/views/workspace-sidenav.html, client/app/scripts/superdesk-dashboard/views/workspace.html, client/app/scripts/superdesk-dashboard/workspace-tasks/tasks.js, client/app/scripts/superdesk-dashboard/workspace-tasks/views/workspace-tasks.html, client/app/scripts/superdesk-monitoring/views/monitoring-view.html, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-packaging/views/packaging.html, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/styles/search.less, client/app/scripts/superdesk-search/tests/search_spec.js, client/app/scripts/superdesk-stream/views/workspace-stream.html, client/app/scripts/superdesk/menu/menu.js, client/app/scripts/superdesk/menu/views/superdesk-view.html, client/app/styles/less/layouts.less
=> workspace updates

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk/views/sdSlider.html, client/app/styles/less/forms.less
Added slider state indicator and hover effect for buttons
SD-2742
=> feat (slider indicator): Added indicators below the slider

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-authoring/views/authoring-topbar.html
=> feat (desk name): Added desk name in top of authoring screen

server/apps/prepopulate/data_initialization/validators.json, server/apps/publish/archive_publish.py, server/apps/publish/archive_publish_tests.py, server/apps/publish/formatters/ninjs_formatter.py, server/apps/publish/formatters/ninjs_formatter_test.py, server/features/content_publish.feature, server/features/publish_publicapi.feature
Publish a simple package of an article and a picture to the API.
There is a known issue in that the package reference is to the actual text article, it should be to the digital package.
=> [SD-2740],[SD-2753] Simple package publishing to the public API

client/app/scripts/superdesk-dashboard/views/workspace-sidenav.html
=> fix (content ingest icon): Added icons for content and ingest in side bar

server/Dockerfile, server/requirements.txt
use hachoir fork with fixed packages info
not sure it will work, but travis should tell us
=> chore(server): avoid mercurial dependency

server/superdesk/locators/__init__.py
SD-2858 sd-test server is not working
=> (blocker) Fix locators reading on ubuntu

client/app/scripts/superdesk-desks/aggregate.js, client/app/scripts/superdesk-monitoring/monitoring.js, client/app/scripts/superdesk-monitoring/monitoring.spec.js, client/app/scripts/superdesk-monitoring/styles/monitoring.less, client/app/scripts/superdesk-monitoring/views/monitoring-view.html, client/app/styles/less/navs.less, client/app/styles/less/sf-additional.less, client/spec/helpers/monitoring.js
=> Monitoring filter

client/app/scripts/superdesk-dashboard/views/workspace-topnav.html, client/app/scripts/superdesk-workspace/views/edit-workspace-modal.html, client/app/scripts/superdesk-workspace/views/workspace-dropdown.html, client/app/scripts/superdesk-workspace/workspace.js, client/app/scripts/superdesk-workspace/workspace.spec.js, client/app/scripts/superdesk/menu/styles/menu.less, client/app/styles/less/variables.less
=> feat(desk dropdown): Improvements for desk and workspace dropdowns

client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-stream/views/activity-stream.html, client/app/scripts/superdesk-users/activity/activity.js, client/app/scripts/superdesk-users/profile.js, client/app/scripts/superdesk-users/profile.spec.js, client/app/scripts/superdesk/datetime/datetime.js, server/superdesk/__init__.py, server/superdesk/eve_backend.py, server/superdesk/logging.py
and other system messages. it will only show activity of users
related to content.
=> fix(activity): filter activity to not contain erros

client/app/scripts/superdesk-monitoring/views/monitoring-view.html, client/app/styles/less/sf-additional.less
Fixed all button and search on open/close
SD-2713 SD-2831
=> Fix (all button fixed)

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-monitoring/monitoring.js, client/app/scripts/superdesk-monitoring/styles/monitoring.less, client/app/scripts/superdesk-monitoring/views/monitoring-view.html, client/app/scripts/superdesk-monitoring/views/monitoring.html, client/app/styles/less/navs.less
=> fix(monitoring): Added + button on monitoring view

server/apps/users/users.py, server/features/steps/steps_users.py, server/features/user.feature
=> fix(users): set default order for users

client/app/scripts/superdesk-desks/aggregate-widget/aggregate-widget.html, client/app/scripts/superdesk-desks/styles/aggregate.less, client/app/scripts/superdesk-desks/views/stage-header.html
=> fix(monitoring widget): Fixed HTML/CSS for monitoring widget

server/apps/archive/__init__.py, server/apps/archive/archive_crop.py, server/apps/archive/archive_crop_tests.py, server/apps/prepopulate/data_initialization/validators.json, server/apps/prepopulate/data_initialization/vocabularies.json, server/features/content_crop.feature, server/features/steps/fixtures/vocabularies.json, server/superdesk/media/media_operations.py, server/superdesk/metadata/item.py, server/superdesk/publish/publicapi.py, server/superdesk/upload.py
[SD-2838] - Validator for picture publishing
[SD-2839] - Public API: Copy all renditions to public API
=> [SD-2837] - Creating crops for picture stories

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk-monitoring/styles/monitoring.less, client/app/styles/less/buttons.less, client/app/styles/less/navs.less, client/app/styles/less/variables.less
Panel behavior & style improvements in the in the Monitoring view
=> fix(styles): Panel behavior & style improvements

server/apps/packages/takes_package_service.py, server/apps/publish/archive_publish.py, server/apps/publish/archive_publish_tests.py, server/features/content_link.feature, server/features/content_publish.feature
- refactor for takes publishing.
- Fix the bug where correction of a takes combines the body html from all takes and uses the metadata from the last take.
=> [SD-2852] Takes correction

client/app/scripts/superdesk-archive/archive-widget/archive.js, client/app/scripts/superdesk-desks/aggregate.js, client/app/scripts/superdesk-ingest/ingest-widget/ingest.js
Removed configurations for authoring widgest.
I left code, because the same code is used for widgets on dashboard.
SD-2826
=> fix(authoring): Removed monitoring, ingest and content icons from right sidebar 

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk/menu/styles/menu.less, client/app/styles/less/navs.less, client/app/styles/less/variables.less, client/spec/helpers/authoring.js
=> fix(authoring topbar): Improved topbar in authoring

client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/styles/highlights.less, client/app/styles/less/dropdowns.less
[SD-2765](https://dev.sourcefabric.org/browse/SD-2765)
=> fix(highlights): Removing highlights does not work

server/apps/aap_mm/__init__.py, server/apps/archive/archive.py, server/apps/archive/archive_media.py, server/apps/highlights/generate.py, server/apps/packages/package_service.py, server/apps/publish/archive_publish.py, server/apps/publish/archive_publish_tests.py, server/apps/publish/formatters/aap_ipnews_formatter.py, server/apps/publish/formatters/aap_sms_formatter.py, server/apps/publish/formatters/anpa_formatter.py, server/apps/publish/formatters/newsml_1_2_formatter.py, server/apps/publish/formatters/newsml_g2_formatter.py, server/apps/publish/formatters/ninjs_formatter.py, server/apps/publish/formatters/nitf_formatter.py, server/apps/publish/published_item.py, server/apps/tasks.py, server/apps/text_archive/import_text_archive/import_command.py, server/apps/validate/validate.py, server/superdesk/aap_mm_datalayer.py, server/superdesk/io/anpa.py, server/superdesk/io/commands/update_ingest.py, server/superdesk/io/iptc7901.py, server/superdesk/io/newsml_1_2.py, server/superdesk/io/newsml_2_0.py, server/superdesk/io/rfc822.py, server/superdesk/io/rss.py, server/superdesk/io/wenn_parser.py, server/superdesk/io/zczc.py, server/superdesk/metadata/item.py
- Ignored changing content type to namedtuple is tests (for setup data) and publicapi related files. 
If I have missed anything else please let me know.
=> Using namedtuple for content type.

client/app/scripts/superdesk-dictionaries/dictionaries.js, client/app/scripts/superdesk/editor/editor.js, client/app/scripts/superdesk/editor/spellcheck/spellcheck.js
=> Fix (dictionary check all sections on adding word)

client/app/scripts/superdesk-monitoring/views/monitoring-view.html
[SD-2877](https://dev.sourcefabric.org/browse/SD-2877)
=> feat(monitoring): Added tooltips for filter buttons

client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/styles/search.less, client/app/scripts/superdesk-search/views/item-searchbar.html
=> Fix (on x button reset search)

client/app/scripts/superdesk-templates/templates.js
The are no e2e tests at all for templates so they will come in a future
PR. For now just edit fix.
=> fix(templates): Fix edit templates

client/app/scripts/superdesk-dashboard/views/workspace.html
=> fix(workspace): Fixed displaying workspace menu for desks.

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk-monitoring/styles/monitoring.less, client/spec/monitoring_spec.js
Changed the behaviour of panels on smaller screens:
- preview overlaps the editor
- aspect ratio of editor and list is changed in favor of the editor
=> fix(styles): Responsive behaviour

client/app/scripts/superdesk/menu/notifications/notifications.js, client/app/scripts/superdesk/menu/notifications/notifications_spec.js
for non admin users it will only get content notifications related
to current user, admins will get everything based on settings.
=> fix(notifications): filter notifications for non-admin users

client/app/scripts/superdesk-dashboard/styles/dashboard.less
=> Fix (widget allignement)

client/app/scripts/superdesk-dashboard/views/workspace.html
=> fix(workspace): Various fixes.

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-monitoring/monitoring.js, client/app/scripts/superdesk-monitoring/views/monitoring-group.html, client/spec/helpers/authoring.js, client/spec/monitoring_spec.js
=> Fix (edit mode on double click)

client/app/scripts/superdesk-dashboard/grid/grid.js, client/app/scripts/superdesk-dashboard/module.js
=> Fix (all widgets can be added)

client/app/scripts/superdesk-archive/module.js, client/app/scripts/superdesk-archive/tests/archive_spec.js, client/app/scripts/superdesk-legal-archive/legal_archive.js
[SD-2848] Improvements and Test Coverage
[SD-2849] Improvements and Test Coverage
=> (imp) PR#972

client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/metadata/tests/metadata_spec.js, client/app/scripts/superdesk-dashboard/workspace-tasks/tasks.js, client/app/scripts/superdesk-dashboard/workspace-tasks/tests/tasks_spec.js, client/app/scripts/superdesk/filters.js
[SD-2935] - Scheduler is causing faulty behaviour
=> (fix) Fixing publish schedule error.

client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-publish/views/destination.html, client/app/scripts/superdesk-publish/views/subscribers.html, server/apps/prepopulate/data_initialization/vocabularies.json
Changes the `vocabularies` collection. Please make sure to update the `vocabularies` collection after merging this PR. Otherwise, __formats will not be displayed in Subscribers management__.
=> (imp) [SD-2964] Modify the Subscribers so that Subscriber Type and Format are dependent

client/app/scripts/superdesk-dashboard/sd-widget-directive.js
=> fix(workspace): Fixed creating workspace after deleting one.

client/app/scripts/superdesk-authoring/authoring.js, server/apps/archive/common.py, server/apps/prepopulate/data_initialization/validators.json
__Please update the validators collection after merging this PR.__
=> (fix) [SD-2981] Dateline not saved when publishing without initial save

client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-search/views/multi-action-bar.html
=> Fix (small fixes)

client/app/scripts/superdesk-workspace/views/workspace-dropdown.html
This is just a small DOM refactoring, there is no task in JIRA for this.
=> fix(workspace dropdown): Fixed color changes for workspace dropdowns.

client/app/scripts/superdesk-dashboard/grid/grid.js, client/app/scripts/superdesk-dashboard/module.js
=> Fix (widgets can be deleted)

client/app/scripts/superdesk-archive/module.js, client/app/scripts/superdesk-dashboard/views/workspace-sidenav.html, client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/views/mark_highlights_dropdown_directive.html, client/app/scripts/superdesk-highlights/views/package_highlights_dropdown_directive.html, client/app/scripts/superdesk-highlights/views/search_highlights_dropdown_directive.html, client/app/scripts/superdesk/menu/styles/menu.less, client/app/styles/less/sprites.less, client/protractor-conf.js, client/spec/helpers/highlights.js, client/spec/highlights_spec.js
SD-2918 and also fixed dropdown menu for highlights in left submenu
=> feat(highlights): Grouped highlights in action menu

client/app/scripts/superdesk-templates/templates.js, client/app/scripts/superdesk-workspace/content/content.js
This list of fields applied when creating the template has been unified with the list that is used when creating the template.
=> [SD-3014] Modify list of fields applied with templates

client/app/scripts/superdesk-authoring/versioning/history/history.js, client/app/scripts/superdesk-authoring/versioning/history/history.less, client/app/scripts/superdesk-authoring/versioning/history/views/history.html, client/spec/authoring_spec.js, client/spec/helpers/authoring.js
SD-2462
As a user I want to see the publish history for an item as part of item
history
=> SD-2462 As a user I want to see the publish history for an item as part of item history

client/app/scripts/superdesk-authoring/widgets/widgets.js, client/app/scripts/superdesk-packaging/packaging.js, client/spec/highlights_spec.js, server/apps/prepopulate/data_initialization/validators.json
Also added initial set of validations for package publishing...
=> [SD-3028] - Disable packaging widget for read-only packages

client/app/scripts/superdesk-authoring/multiedit/multiedit.js
=> fix(multiedti): SD-2915 Fixed lower bar and sidebar on multiedit screen

client/app/scripts/superdesk-monitoring/monitoring.js, client/app/scripts/superdesk-monitoring/styles/monitoring.less, client/spec/monitoring_spec.js
=> Fix (on edit close preview)

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/styles/themes.less, client/app/scripts/superdesk-authoring/views/authoring.html, client/app/scripts/superdesk-authoring/views/header-info.html, client/app/scripts/superdesk-authoring/views/theme-select.html
=> fix(header improve): Improve authoring header

client/app/scripts/superdesk-authoring/views/header-info.html, client/app/scripts/superdesk-dashboard/workspace-tasks/views/workspace-tasks.html, client/app/scripts/superdesk-ingest/views/settings/ingest-routing-filter.html, client/app/scripts/superdesk-ingest/views/settings/ingest-routing-general.html, client/app/scripts/superdesk-legal-archive/legal_archive.js, client/app/scripts/superdesk-legal-archive/views/legal_archive.html, client/app/scripts/superdesk-packaging/views/sd-package-edit.html, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/views/item-search.html
=> [SD-3046] Change the label for slugline to slugline rather than keyword

client/app/scripts/superdesk-authoring/workqueue/workqueue.js, client/app/scripts/superdesk-monitoring/monitoring.js, client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-stream/stream.js, client/app/scripts/superdesk-users/users.js, client/spec/monitoring_spec.js, server/apps/prepopulate/app_prepopulate_data.json
For the following features status has been changed:
hamburger-> authoring - deleted
hamburger -> settings -> data consistency - delete (we deleted only
the menu option because probably it will be needed to be reactivated)
activity and workspace stream - stable
user-> change avatar: upload from url and take a picture - stable
=> chore(preview features): Update the beta status for a few features

client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/styles/highlights.less, client/app/scripts/superdesk-monitoring/views/item-actions-menu.html, client/app/scripts/superdesk/activity/views/activity-item.html, client/app/scripts/superdesk/ui/ui.js, client/app/styles/less/dropdowns.less, client/spec/helpers/content.js, client/spec/helpers/highlights.js, client/spec/helpers/monitoring.js
and function for calculating future position of dropdown
SD-3041
=> fix(action dropdown): SD-3041 Added nested dropdown for highlights

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/authoring-container.html, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-packaging/views/packaging.html, client/spec/authoring_spec.js, client/spec/content_spec.js, client/spec/helpers/authoring.js, client/spec/helpers/setup.js
fix(authoring): Fixed close button for embedded mode.
SD-2889
=> fix(monitoring): Fixed editing packages in monitoring.

client/app/scripts/superdesk-archive/module.js, client/app/scripts/superdesk-archive/tests/archive_spec.js, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-authoring/workqueue/workqueue.js, client/app/scripts/superdesk-dashboard/sd-widget-directive.js, client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-monitoring/monitoring.js, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-search/views/item-preview.html, client/app/scripts/superdesk-workspace/content/content.js, client/app/scripts/superdesk/editor/editor.js, client/app/scripts/superdesk/menu/menu.js, client/app/scripts/superdesk/menu/menu.spec.js, client/app/scripts/superdesk/menu/views/superdesk-view.html, client/spec/authoring_spec.js, client/spec/helpers/authoring.js, client/spec/helpers/content.js, client/spec/helpers/monitoring.js, client/spec/helpers/utils.js, client/spec/highlights_spec.js, client/spec/package_spec.js, client/spec/send_spec.js
refactor authoringWorkspace from controller into a service
so that it can be used also from activities and not only directives.
SD-2885
=> fix(workspace): make item actions menu use sidebar authoring

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-highlights/highlights.js, client/app/scripts/superdesk-highlights/highlights.spec.js, client/app/scripts/superdesk-packaging/packaging.js
instead close authoring sidebar
=> fix(highlights): stop redirecting on highlights export

server/apps/io/update_ingest_tests.py
Remove the use of context from tests in this file as well.
=> Try to fix docker build

client/app/scripts/superdesk-authoring/comments/comments.less, client/app/scripts/superdesk-authoring/styles/authoring.less
=> Fix (comment and resize layout on locked items)

client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/metadata/views/metadata-terms.html, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/tests/search_spec.js, client/app/scripts/superdesk-search/tests/tags_spec.js, client/app/scripts/superdesk-search/views/item-search.html, client/app/scripts/superdesk-search/views/search-facets.html, client/app/scripts/superdesk/directives/sdTypeahead.js, client/spec/search_spec.js
=> Fix (global search fixed)

client/app/scripts/superdesk-packaging/packaging.js
=> fix(publishing) - Previewing ingested package problem

client/docs/superdesk.md
The indentation of the code snippets is made consistent (4 spaces), and the
javascript highlighting is applied to them.
=> Improve readability of the Superdesk client docs.

client/app/scripts/main.js, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-highlights/highlights.spec.js, client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-packaging/views/sd-package-edit.html, client/app/scripts/superdesk-packaging/views/sd-package-items-edit.html, client/app/scripts/superdesk/activity/activity.js, client/package.json, client/spec/package_spec.js
=> feat(packaging): Added adding items to packages in monitoring.

server/apps/prepopulate/app_initialize.py
- Fix to update the master.dev with new vocaburlaries.
=> (fix) Fixing code where the app_initialize allows to insert new documents.

client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-archive/views/list.html, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/tests/search_spec.js, client/app/scripts/superdesk-search/views/search-results.html
=> feat(search): SD-2986 Added infinite scroll for grid and list view

client/app/scripts/superdesk/directives/sdTypeahead.js
=> fix(authoring): SD-3115 Fix adding item from ANPA category

client/app/scripts/superdesk-highlights/views/package_highlights_dropdown_directive.html
=> fix(monitoring): Fix show/hide monitoring list on highlights

client/app/index.html, client/app/scripts/main.js, client/app/scripts/superdesk-archive/directives.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk/activity/activity.js, client/app/scripts/superdesk/auth/auth.js, client/app/scripts/superdesk/menu/views/superdesk-view.html, client/app/scripts/superdesk/services/preferencesService.js, client/app/scripts/superdesk/superdesk.js
this will prevent rendering incomplete pages to users
=> fix(client): only enable ng-view when we get user preferences

client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/styles/authoring.less
=> fix(authoring): SD-3156 Fixed non-displayed category items on opening item

server/features/ingest_provider.feature, server/requirements.txt
These are the test for the following in the superdesk-core
https://github.com/superdesk/superdesk-core/pull/7
Will need the superdesk-core to be merged
=> (fix) Fixng the ingest provider create and update.

client/app/scripts/superdesk-archive/archive-widget/archive-widget.spec.js, client/app/scripts/superdesk-archive/archive-widget/archive.js, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-dashboard/module.js, client/app/scripts/superdesk-desks/desks.js
it's now opening the item in authoring sidebar
SD-3141
=> fix(dashboard): fix edit action in content/monitoring widgets

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-highlights/styles/highlights.less, client/app/scripts/superdesk-highlights/views/highlights_title_directive.html, client/app/scripts/superdesk-monitoring/styles/monitoring.less, client/app/scripts/superdesk-monitoring/views/monitoring-group.html
And also added label when there are no items in monitoring group
SD-3105
=> fix(highlights): SD-3105 Fixed layout issue for highlights

client/app/scripts/superdesk-archive/controllers/list.js, client/app/scripts/superdesk-workspace/content/content.js, client/app/scripts/superdesk-workspace/content/views/sd-content-create.html, client/spec/helpers/monitoring.js, client/spec/monitoring_spec.js
it was only available in content view, now it should be everywhere
SD-2940
=> feat(monitoring): add upload btn to create content dropdown

client/app/scripts/superdesk-items-common/styles/archive-preview.less
=> Fix locked item text in preview

client/app/scripts/superdesk-authoring/metadata/views/metadata-terms.html, client/app/scripts/superdesk-authoring/views/header-info.html, client/app/scripts/superdesk-highlights/views/package_highlights_dropdown_directive.html, client/app/scripts/superdesk-workspace/views/workspace-sidenav-items.html, client/app/scripts/superdesk/menu/styles/menu.less, client/app/scripts/superdesk/ui/ui.js, client/app/styles/less/dropdowns.less
=> fix(authoring): SD-3179 Fixed layout issue on category dropdown

client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-monitoring/monitoring.js
First fetch than open fetched item
SD-3111
=> feat(monitoring): SD-3111 Action for double click on ingest item

client/app/scripts/superdesk/ui/ui.js
=> fix(monitoring): SD-3134 Fixed layout issue on action menu dropdown

client/app/scripts/superdesk-authoring/styles/themes.less
=> Fix dateline and desciption

client/app/styles/less/dropdowns.less
=> fix(monitoring): SD-3189 Fixed layout issue on action dropdown for highlights

client/app/scripts/superdesk-authoring/authoring.js, client/spec/helpers/content.js, client/spec/helpers/workspace.js, client/spec/highlights_spec.js
there was 'edit item' and 'edit package', now it's only 'edit'
SD-3188
=> fix(monitoring): change edit item label to "Edit"

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/send-item.html
=> (fix) [SD-3203] Cannot change the "send to/publish" destination

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-authoring/views/send-item.html
=> Fix publish pane scroll and remove double create button

README.md
update info using `common.yml` file instead of missing `docker-compose.yml.sh`
fix #1103
=> fix(readme): update link to docker config

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/styles/themes.less, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-authoring/views/article-edit.html, client/app/scripts/superdesk-authoring/views/authoring.html, client/app/scripts/superdesk-authoring/views/theme-select.html, client/app/scripts/superdesk-workspace/workspace.js
=> fix(authoring): SD-3127 Added tooltips and improved icons and their behavior for theme chooser

client/app/scripts/superdesk-dashboard/module.js, client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-legal-archive/legal_archive.js, client/app/scripts/superdesk-planning/module.js, client/app/scripts/superdesk-publish/publish.js, client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-settings/module.js, client/app/scripts/superdesk-users/users.js, client/app/scripts/superdesk/menu/views/menu.html
=> Fix hamburger menu

client/spec/authoring_spec.js, client/spec/helpers/authoring.js, client/spec/monitoring_spec.js
Tests for SD-3111, PR: #1102 and for SD-3127, PR #1116
=> fix(tests): Added e2e tests for monitoring and authoring

client/app/scripts/superdesk-authoring/multiedit/multiedit.js
=> fix(multipanel): SD-2979 Close authoring when opening multiedit items

server/apps/archive/archive_crop.py, server/apps/archive/archive_crop_tests.py
This PR depends on https://github.com/superdesk/superdesk-core/pull/13
=> (fix) Fix the saving of crop to show user friendly error.

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-authoring/views/header-info.html
=> fix(authoring): SD-3103 Fixed unlock button on authoring

client/app/scripts/superdesk-packaging/packaging.js, client/app/scripts/superdesk-packaging/packaging.spec.js
it should open item in view mode
SD-3167
=> fix(packaging): fix open item from package button

client/app/scripts/superdesk-authoring/views/header-info.html
in authoring header. also fixed some missing translations.
SD-3156
=> fix(authoring): hide word count for non-text items

client/app/scripts/superdesk-ingest/views/settings/emailConfig.html, server/apps/archive/common.py, server/apps/io/fixtures/json-email-bad-user.txt, server/apps/io/fixtures/json-email.txt, server/apps/io/formatted_email_test.py
This PR is dependent on the pr superdesk/superdesk-core#15
=> [SD-3211],[SD-3210] Tests and UI change to allow ingest of email from google forms

client/app/scripts/superdesk/editor/editor.js, client/app/scripts/superdesk/editor/editor.spec.js
this should work now also in firefox etc.
SD-3228
=> fix(spellcheck): prevent browser action on ctrl+shift+s

client/app/scripts/superdesk-authoring/multiedit/multiedit.js
=> fix(multiedit): SD-2979 Fixed extra panel on multiedit

client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/header-info.html, client/app/scripts/superdesk-ingest/styles/dashboard.less, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk-monitoring/styles/monitoring.less, client/app/scripts/superdesk-search/views/search-results.html, client/app/styles/less/layouts.less, client/app/styles/less/variables.less
=> Fix (ingest dashboard and ingest layout issue)

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-ingest/module.js, client/app/scripts/superdesk-ingest/styles/settings.less, client/app/scripts/superdesk-ingest/views/settings/ingest-routing-schedule.html, client/app/scripts/superdesk-settings/styles/settings.less, client/app/scripts/superdesk-templates/templates.js, client/app/scripts/superdesk-templates/views/templates.html, client/app/scripts/superdesk/datetime/datetime.js, client/app/scripts/superdesk/ui/tests/ui_spec.js, client/app/scripts/superdesk/ui/ui.js, client/app/scripts/superdesk/ui/views/sd-timepicker-alt.html, client/app/scripts/superdesk/ui/views/sd-timepicker.html, client/app/scripts/superdesk/ui/views/weekday-picker.html, server/apps/rules/routing_rules.py, server/apps/rules/routing_rules_tests.py, server/apps/templates/__init__.py, server/apps/templates/content_templates.py, server/apps/templates/content_templates_test.py, server/features/steps/steps.py, server/features/steps/template_steps.py, server/features/templates.feature, server/settings.py
=> auto create content based on templates

client/app/scripts/superdesk-authoring/multiedit/views/sd-multiedit-dropdown.html, client/app/scripts/superdesk-authoring/styles/themes.less
=> Fix(theme box width and empty multiedit)

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/spec/authoring_spec.js, client/spec/helpers/authoring.js, server/apps/prepopulate/app_prepopulate_data.json, server/apps/publish/archive_publish.py
[SD-3256] Embargoed items of a package have a digital and story present
[SD-3298] Corrected embargo's old copy still has correct and kill options
=> (fix) [SD-3256] [SD-3298]

client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/views/main.html, client/app/scripts/superdesk/menu/views/superdesk-view.html
preview component was missing in dashboard, not it is present
in all workspace views.
SD-3287
=> fix(monitoring): fix preview in monitoring widget

client/app/scripts/superdesk-authoring/authoring.js
Navigation is not needed anymore...
=> [SD-3262] - Unlocking an item throws the other user out of monitoring

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/send-item.html
Attempts to publish anything in a draft state fails the state transition checks, this should avoid that.
=> [SD-3163] Dont show the publish button if the item state is draft

client/app/scripts/superdesk-authoring/authoring.js
=> Fix (all types of items can be multiedited)

client/app/scripts/superdesk-authoring/multiedit/multiedit.js, client/app/scripts/superdesk-authoring/multiedit/views/multiedit.html, client/app/scripts/superdesk-authoring/styles/multiedit.less, client/app/scripts/superdesk-authoring/views/opened-articles.html, client/app/scripts/superdesk-authoring/workqueue/tests/workqueue_spec.js, client/app/scripts/superdesk-authoring/workqueue/workqueue.js
=> Fix (multiedit closing fixed)

client/app/scripts/superdesk-search/search.js, client/app/scripts/superdesk-search/views/multi-action-bar.html
=> feat(monitoring): Implemented "add to current package" multi action.

client/app/scripts/superdesk-ingest/styles/settings.less, client/app/scripts/superdesk-ingest/views/settings/ingest-routing-content.html, client/bower/styles/css/bootstrap.css
Resolves [SD-2434](https://dev.sourcefabric.org/browse/SD-2434).
Please see the attached screenshot for an idea how the change looks like. The currently selected filter has a dark gray background.
P.S.: We keep `client/bower/styles/css/bootstrap.css` under source control, right?
=> Make the currently edited routing scheme rule highlighted

client/app/scripts/superdesk-archive/module.js, client/app/scripts/superdesk-authoring/authoring.js, server/apps/archive/archive_link.py, server/apps/packages/takes_package_service.py, server/apps/publish/archive_publish.py, server/apps/publish/formatters/newsml_1_2_formatter.py, server/apps/publish/formatters/newsml_g2_formatter.py, server/apps/publish/formatters/newsml_g2_formatter_test.py, server/features/content_link.feature
- [SD-3275] New takes are being created with missing header info
- [SD-3038] Takes of an item in workspace get placed in another desk
=> (fix) Fixing takes related issues.

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/metadata/views/metadata-locators.html, client/app/scripts/superdesk-authoring/styles/themes.less, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, client/app/scripts/superdesk-authoring/views/article-edit.html, client/app/scripts/superdesk/directives/sdTypeahead.js, client/app/scripts/superdesk/filters.js, server/apps/archive/common.py, server/apps/packages/takes_package_service.py, server/apps/publish/archive_publish.py, server/apps/publish/formatters/ninjs_formatter.py, server/apps/publish/formatters/nitf_formatter.py, server/requirements.txt
Requires [Superdesk-Core's PR#26](https://github.com/superdesk/superdesk-core/pull/26)
=> (imp) [SD-3033] Dateline value should update with edits to the point of publishing

client/app/scripts/superdesk-items-common/styles/archive-preview.less
=> Fix (unlock button position)

client/app/scripts/superdesk-authoring/multiedit/multiedit.js, client/app/scripts/superdesk-authoring/workqueue/workqueue.js
SD-3270: Related to @fritzSF comment
=> Fix (multiedit): On multiedit close the open items should not be closed

client/app/scripts/superdesk-dashboard/workspace-tasks/styles/tasks.less, client/app/scripts/superdesk-dashboard/workspace-tasks/tasks.js, client/app/scripts/superdesk-dashboard/workspace-tasks/tests/tasks_spec.js, client/app/scripts/superdesk-dashboard/workspace-tasks/views/kanban-board.html, client/app/scripts/superdesk-dashboard/workspace-tasks/views/workspace-tasks.html, client/app/scripts/superdesk-desks/desks.js, client/app/scripts/superdesk-desks/tests/desks-spec.js, client/app/scripts/superdesk-desks/views/desk-config-modal.html, client/app/scripts/superdesk/datetime/datetime.js, client/test-main.js, server/apps/stages.py, server/features/stages.feature
=> tasks refactoring

client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/spec/helpers/content.js
Needs fix for the Highlights pop-over, this will be covered by SD-3105
=> fix(list item): Markup and style clean-up

client/app/scripts/superdesk-vocabularies/styles/vocabularies.less, client/app/scripts/superdesk-vocabularies/views/vocabulary-config-modal.html, client/spec/monitoring_spec.js
SD-3371
Also I enabled test, now it should pass!
=> fix(vocabularies): SD-3371 Fixed modals width issue

client/app/docs/module.js, client/app/scripts/superdesk-archive/views/media-box-list.html, client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/metadata/metadata.js, client/app/scripts/superdesk-authoring/metadata/views/metadata-dropdown.html, client/app/scripts/superdesk-authoring/metadata/views/metadata-terms.html, client/app/scripts/superdesk-authoring/styles/authoring.less, client/app/scripts/superdesk-authoring/views/article-edit.html, client/app/scripts/superdesk-authoring/views/authoring.html, client/app/scripts/superdesk-authoring/views/header-info.html, client/app/scripts/superdesk-authoring/views/send-item.html, client/app/scripts/superdesk-items-common/styles/media-archive.less, client/app/scripts/superdesk/ui/ui.js, client/app/styles/less/dropdowns.less, client/app/styles/less/forms.less, client/app/styles/less/layouts.less, client/spec/content_spec.js
- SD-3168 Added tab index for input fields in authoring screen and improved UI for header in authoring
- SD-3000 Added focus for `slugline` field on opening
- SD-3333 If publish option in slide pane is not allowed, rename it to 'Send To'
- SD-3240 Added default news value (urgency) icon
- SD-3344 , SD-3341 Fixed layout issue for slide pane
=> feat(authoring): Improved header and slide panel

client/app/scripts/superdesk-monitoring/styles/monitoring.less, client/app/styles/less/layouts.less
=> Fix (preview trace on close removed)

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/tests/authoring_spec.js, server/settings.py
[SD-3274](https://dev.sourcefabric.org/browse/SD-3274)
=> (fix) Removing confirmation dialog and allowing certain settings to be configured via environment variables.

client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/app/scripts/superdesk-desks/desks.js
And on desk - adding people, people are added on top (discussed with
Fritz, no issue for this)
=> [SD-3334] - On send or send and continue unlock isn't showing

client/app/scripts/superdesk-authoring/authoring.js, client/app/scripts/superdesk-authoring/views/authoring-topbar.html, client/spec/content_spec.js, client/spec/helpers/authoring.js
=> fix(authoring): Fixed minor double-click save issue.
