superdesk/superdesk

client/app/scripts/superdesk-ingest/views/settings/ftp-config.html
server/superdesk/io/ftp.py

@petrjasek ftp code change did not work expected. I was getting error as "200 Type is Image (Binary)" on line https://github.com/superdesk/superdesk/blob/2bca01c2999b01da03a9c32a764a90a2e9d73e95/server/superdesk/io/ftp.py#L88.
The ftp.retrbinary command does the following in passive mode:
- send "Type I"
- send PASV 
The response of the PASV command is "200 Type is Image (Binary)" instead of "227 Entering Passive Mode" Hence response validation of PASV fails. FTP download in active mode work fine. 
Moreover, I have modified the client and server so that the FTP connection type is configurable.

(Fix)[Ingest] Added FTP passive switch for connection to the server.

---

server/superdesk/emails/__init__.py

without configured mail server celery workers get stuck with email
sending tasks. this will make such tasks fail after 10s

fix(celery): make sure workers won't hang with emails

---

server/Procfile
server/apps/archive/__init__.py
server/apps/auth/__init__.py
server/settings.py
server/superdesk/io/__init__.py
server/superdesk/io/commands/update_ingest.py
server/superdesk/io/reuters.py
server/superdesk/io/reuters_token.py
server/superdesk/media/media_operations.py

but keep it 10s for emails, and make it 30m for ingest.update_provider
+ set timeouts for reuters api requests

fix(ingest): set 5m soft time limit for all tasks

---

.travis.yml
client/package.json
docker/container_build.sh

should speed-up client build (not installing protractor from git) and hopefully should fix e2e on bamboo (it seems chromedriver 2.13 works there better than 2.12 on bamboo)

chore(travis, client): install patched protractor for travis on-demand

---

.gitignore
docker/container_build.sh
server/Procfile
server/gunicorn_config.py
server/requirements.txt
server/settings.py
server/ws.py

if there was a file with space in name it would split it
for xargs and touch every part of that filename, creating new files,
and not touching the original file at all
but not sure why it's there @actionless ?

fix(docker): prevent creation of new files via touch

---

client/app/scripts/superdesk-archive/controllers/list.js
client/app/scripts/superdesk-dashboard/module.js
client/app/scripts/superdesk-desks/directives.js
client/app/scripts/superdesk-desks/module.js

Fixed the issues below from SD-1598:
1. Even though the user is on a desk when clicked on Content tab the list displays personal items instead of desk items.
2. Navigate back to Ingest tab from Content tab and observe that the user is switched to personal work space from a desk.
SD-1425: Confirmation upon deleting a desk

(improvement) SD-1425: Confirmation upon deleting a desk

---

server/features/steps/steps.py
server/superdesk/io/commands/remove_expired_content.py
server/superdesk/io/commands/update_ingest.py
server/superdesk/io/commands/update_ingest_tests.py

Changes:
- Started using the 'expiry' field in ingested items
- Elastic filter in remove_expired_content has changed to use 'expiry' field (it should also be backward compatible)

[SD-1682] - Display the expiry field in metadata tab for ingest items

---

client/app/scripts/superdesk-search/search.js
client/app/scripts/superdesk-search/views/search-facets.html
client/app/scripts/superdesk-users/users.js
client/app/scripts/superdesk-users/views/edit-form.html

[SD-1721] User with no save search permission gets improper error.
Modified edit-form.html and users.js:
1. To display the "Default Desk" field only if the user is member of some desk.
2. Fixed error thrown while creating a new user.

(fix) SD-1721 and errors in console while creating a new user

---

client/app/scripts/superdesk-authoring/authoring.js
server/features/packages.feature
server/features/user.feature
server/superdesk/errors.py

[SD-1723] A combination of privileges gives unclear error.
Modified SuperdeskAPIError.__str__() in errors.py module to return error code and message, which is sometimes sent to client as part of response. This will enhance the user experience to see what exactly went wrong. To put it in simple words the error message is changed from "Error:403" to "Error: 403: Unauthorized to modify unique name".

(fix) SD-1723

---

server/superdesk/io/rfc822.py
server/superdesk/io/rfc822_parser_test.py
server/superdesk/io/zczc.py
server/superdesk/io/zczc_parser_test.py

The changes to the ingest expiry requires that all items are created with the versioncreated key in the item dictionary.

fix(ingest expiry) Email and Teletype parsers to include version created in all items

---

.travis.yml

we don't want to spend too much time fixing firefox webdriver issues, so if build fails on firefox we still merge.
@superdesk/developers 
@marwoodandrew @akintolga @sivakuna-aap @mdhaman @sjunaid

fix(travis): ignore firefox build results

---

client/app/scripts/superdesk-archive/module.js
client/app/scripts/superdesk-authoring/views/authoring.html
server/apps/archive/__init__.py
server/apps/tasks.py

[SD-1651] Spiked item should not be editable from authoring
[SD-1718] Locked item being spiked
[SD-1719] Fetching a locked item creates another locked item
[SD-1724] User with no task management privilege is not able to send item to another desk
[SD-1728] It should not be possible to spike a locked item

(fix) Issues related lock

---

client/app/scripts/superdesk-dashboard/module.js
client/app/scripts/superdesk-dashboard/views/desk-dropdown.html

[SD-1598] Reopened because of the below scenario:
Go to any desk and click on the ingest tab.
*The page is populated with the ingest items
Now click on personal
*The page still gets poplulated with ingest items, instead it should switch to the content tab and show the personal items.

(fix) SD-1598

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/tests/authoring_spec.js
client/app/scripts/superdesk-packaging/packaging.js
client/app/scripts/superdesk-packaging/packaging.less
client/app/scripts/superdesk-packaging/views/sd-package-edit.html
client/app/scripts/superdesk-packaging/views/search.html

after autosave call it was extending the original item,
but later if you save it would compare again with original
and there were no changes. so now autosaving is only updating
$scope.item, also on load autosave is applied only to $scope.item
and not to $scope.origItem.

fix(authoring): fix saving after autosave

---

server/superdesk/io/commands/update_ingest.py
server/superdesk/io/ingest_service.py
server/superdesk/io/reuters.py

- instead of stopping on item failure, it will skip this very item
- removed catch all exception to get more info on sentry (temporary)

refactor(ingest): keep ingesting on single item error

---

server/superdesk/io/ftp.py
server/superdesk/io/wenn_parser.py
server/superdesk/io/wenn_parser_test.py

Two problems, the subject codes parsed by the WENN parser where not in a list. Also the NITF parser can be used either by a File Ingestor or FTP, it returns a dictionary not a list.

[SD-1853] WENN/FTP Ingest errors

---

server/apps/highlights/service.py

There are cases when the document has the list of highlights but the
value is null

fix(highlights): Fix mark for highlights

---

client/app/scripts/superdesk-archive/controllers/list.js
client/app/scripts/superdesk-dashboard/module.js
client/app/scripts/superdesk-dashboard/views/desk-dropdown.html
client/app/scripts/superdesk-dashboard/workspace-tasks/tasks.js
client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/tests/desks-spec.js
client/app/scripts/superdesk/api/url-resolver-service.js
client/app/scripts/superdesk/services/preferencesService.js
client/app/scripts/superdesk/services/preferences_spec.js
server/apps/preferences.py

there were multiple calls to update preferences at the same time,
both using same etag, so the later had to fail. that was happening
on desk/stage change which are 2 settings. now those 2 should be
updated together, and also there is no update if the new value
matches the old one.
SD-1867

fix(workspace): prevent preferences update errors

---

server/apps/highlights/generate.py
server/apps/highlights/generate_test.py
server/features/highlights.feature

in case there is no `body_html` in item it will not output `None`

fix(generate): ignore content for non-text items

---

client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/tests/desks-spec.js

we get user default desk via preferences, but this desk might not
exist anymore when using it, so it will check if that desk is there
when fetching user desks and if not it will set 1st desk as current.

fix(desks): check if user current desk exists

---

client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/tests/desks-spec.js

there is no need for this, and also it was a side effect doing updates
in fetch current user desks.

fix(desks): avoid updating preferences when fetching desks

---

server/apps/archive/common.py
server/apps/duplication/archive_fetch.py
server/apps/rules/routing_rules.py
server/features/auto_routing.feature
server/features/content_duplication.feature
server/features/content_fetch.feature
server/features/content_publish.feature
server/features/ingest.feature
server/features/steps/steps.py
server/requirements.txt
server/superdesk/io/commands/update_ingest.py

SD-1946 Fetching operation fails on recently ingested items with Post 404 not found code
This is a big change in how the system works, summary of changes:
- all the items will have an `_id` generated that is going to be different from `guid`, this is because `guid` is not always suited to be used inside URL's
- we won't be able to use `_id` and `guid` interchangeably which is a good thing IMO, we shouldn't rely on this at all, I've updated the obvious situations, hopefully I fixed all of them
@petrjasek @superdesk/developers @sivakuna-aap @akintolga @marwoodandrew @mdhaman

fix(ingest) - always generated an _id, guid is going to point to the ID in the provider system

---

client/app/scripts/superdesk/auth/auth.js

When `$location.path` contains variables (id or parameters),
requiresLogin() can't return the `auth` status.
So here I am using the regex provided by `$route` to test if a route match the `$location.path`.
Then we retrieve the `auth` status or `false` if not found.

auth.js: use regex instead of comparing location path and route path

---

client/app/scripts/superdesk-ingest/module.js
client/app/scripts/superdesk-users/users.js
server/superdesk/validator.py

1. Email Validation fails for valid email id's, for example: user@aap.com.au
2. When there is an error reported by API while saving user the client says the user is saved although it's not saved
3. Javascript Error reported on console for "field_aliases" while adding/modifying Ingest Provider

(fix) Hot Fixes

---

server/superdesk/io/reuters.py

instead of fetching items up to 7 days old only fetch items
that will pass expiry check from reuters api.

fix(reuters): only fetch items that are not expired

---

client/app/scripts/superdesk-ingest/module.js
client/app/scripts/superdesk-ingest/views/settings/ingest-sources-content.html
server/features/ingest_errors.feature
server/features/ingest_provider.feature
server/superdesk/errors.py
server/superdesk/io/__init__.py
server/superdesk/io/aap.py
server/superdesk/io/afp.py
server/superdesk/io/commands/update_ingest_tests.py
server/superdesk/io/dpa.py
server/superdesk/io/email.py
server/superdesk/io/ftp.py
server/superdesk/io/ingest_errors.py
server/superdesk/io/ingest_provider_model.py
server/superdesk/io/ingest_service.py
server/superdesk/io/reuters.py
server/superdesk/io/rss.py
server/superdesk/io/teletype.py
server/superdesk/io/tests.py

List of changes for this task:
- A new end point "ingest_errors" to get the list of errors per provider
- Change in provider end point to save the selected critcal errors for that provider
- UI change to have a "critical errors" tab to select the errors that supposed to close the channel
- provider_service catches all SuperdeskIngestErrors and closes the channel if the error code is in the list of critical errors

[SD-1328] - Automatically close ingest channel after critical error

---

server/apps/archive/archive.py
server/apps/duplication/archive_fetch.py
server/apps/publish/__init__.py
server/apps/publish/archive_publish.py
server/apps/publish/archive_publish_tests.py
server/apps/publish/destination_groups.py
server/apps/publish/formatters/__init__.py
server/apps/publish/formatters/nitf_formatter.py
server/apps/publish/publish_queue.py
server/apps/rules/routing_rules.py
server/features/auto_routing.feature
server/features/destination_groups.feature
server/features/publish_queue.feature
server/features/routing_rules.feature
server/features/steps/steps.py
server/superdesk/errors.py

[SD-2052] Publish endpoint
[SD-2053] Publish queue
[SD-2051] NITF Formatter
- Destinations group schema has been re-factored
- Publish endpoint resolves output channels out of destination groups
- When published there are publish queue entries created per destination (transmission)
- There's transformations place holder (yet to be implemented)
- Publish queue end point created
- A basic structure for output formatters
- NITF formatter is implemented
- Initial publish errors are created
- All the tests are in place

Publish endpoint, publish queue and formatters

---

client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/views/desk-config-modal.html
server/apps/desks.py
server/apps/stages.py
server/features/stages.feature

This change allows you to nominate a (only one) stage in a desk as a published stage. The intention is that when an item is published it will be moved to this stage.
I thought it would be nice to be able to change which stage is the default incoming stage as well!

[SD-2046] Allow a stage to be marked as a published stage one per desk

---

client/app/scripts/superdesk-publish/publish.js
client/app/scripts/superdesk-publish/views/email-config.html
client/app/scripts/superdesk-publish/views/publish-queue.html
client/app/scripts/superdesk/filters.js
server/apps/duplication/archive_move.py
server/apps/publish/__init__.py
server/apps/publish/archive_publish.py
server/apps/publish/archive_publish_tests.py
server/apps/publish/formatted_item.py
server/apps/publish/publish_queue.py
server/features/content_move.feature
server/features/content_publish.feature
server/features/formatted_item.feature
server/features/publish_queue.feature
server/superdesk/errors.py
server/superdesk/io/ftp_tests.py
server/superdesk/publish/__init__.py
server/superdesk/publish/email.py
server/superdesk/publish/ftp.py
server/superdesk/publish/publish_content.py
server/superdesk/publish/publish_service.py

Changes for this PR:
- Archive items are formatted per output channel. The same formatted item will be used for many transmissions because output channels usually contains many destinations (transmission). So created a separate end point for formatted items.
- Selector codes are now resolved as per output channel and added to the queue. 
- Created a simple publish queue page to monitor the status of the transmissions.
- Published items will be moved to designated publish stage on the same desk if there's any
- Created an Email transmission

Improvements on publishing

---

client/app/scripts/superdesk-archive/controllers/upload.js
client/app/scripts/superdesk-archive/controllers/upload_spec.js
server/apps/archive/archive_lock.py
server/apps/item_lock/components/item_lock.py
server/apps/tasks.py
server/apps/users/services.py
server/features/auth.feature
server/features/content_lock.feature

- When a new content item is created, there's an empty record in the archive collection. If that content item is closed by user without making any change (that is still version 1) then the item sits there with no information in it.
- Now if the user closes the newly created item without making any change, system will delete the empty record.
- These type of items will also be deleted on session recycle and log out events as well.
- This PR also addresses the problem in image upload: When user selects an image but then presses cancel button we are left with the empty item. Now when an image is loaded we don't save it until user presses the save button.
- This also solves the issue [SD-2140]

[SD-1670] New archive item is deleted if it is closed before it is saved

---

server/apps/publish/archive_publish.py
server/apps/publish/formatters/nitf_formatter.py

Used get_resource_service() instead of MoveService()

(fix) NITF Formatter fails to format when subject doesn't have 'qcode'

---

server/publicapi/demo_data/README.md
server/publicapi/demo_data/data.json

The file contains data with more variety (item types, authors, creation dates, etc.) for easier testing and development of the public API.
Resolves SD-2198
P.S.: The items' and packages schema differs a bit from the current format we use, because it closely follows the NINJS specification.
P.P.S.: The packages in demo data contain full items, not just the references to them. We might need to change them to only contain links to the contained items (i.e. the `uri` field of each object in the package's `associations` list).

Add a file with sample NINJS data

---

client/app/scripts/superdesk/auth/login-modal-directive.js
client/app/scripts/superdesk/auth/tests/auth_spec.js

after session expiry it would stop without an active route so after
login it would continue nowhere.

fix(auth): reload route when it's a redirect

---

server/README.md

Fix create an administrator user command example

---

server/superdesk/errors.py
server/superdesk/errors_test.py

This is needed in cases when the static pre-defined exception error messages by themselves are not descriptive enough.
Resolves [SD-2262](https://dev.sourcefabric.org/browse/SD-2262).

Add an option to provide a detailed description to all custom exceptions

---

server/publicapi/__init__.py
server/publicapi/errors.py
server/publicapi/items/service.py
server/publicapi/tests/errors_test.py
server/publicapi/tests/items_service_test.py

Resolves [SD-2242](https://dev.sourcefabric.org/browse/SD-2242).
NOTE: the behave tests will be updated under a [separate ticket](https://dev.sourcefabric.org/browse/SD-2171) that we've opened.

public API: return HTTP 422 if request contains unexpected parameters

---

server/publicapi/features/returning_errors.feature

Resolves [SD-2171](https://dev.sourcefabric.org/browse/SD-2171).
Edit: it seems that we have a [broken test](https://travis-ci.org/superdesk/superdesk/jobs/62370645#L1034) in master, something about the desks service (client).
Update: the failing tests do not fail locally and they seem to have been automagically fixed without even touching the relevant code. This build can thus be considered as successful IMO.

Public API: add behave tests for returning an error on invalid request parameters

---

server/publicapi/__init__.py
server/publicapi/demo_data/README.md
server/publicapi/features/prepopulate.feature
server/publicapi/items/service.py
server/publicapi/prepopulate/prepopulate-data/app_prepopulate_data.json
server/publicapi/tests/items_service_test.py

Also did refactored parameter parsing out into helper methods to keep the `ItemsService.get()` method clean and readable.
Resolves [SD-2252](https://dev.sourcefabric.org/browse/SD-2252)

Content API: Allow filtering items/packages by creation date

---

server/publicapi/items/service.py
server/publicapi/tests/items_service_test.py

Resolves [SD-2330](https://dev.sourcefabric.org/browse/SD-2330).

Public API: return more descriptive msg when date range filtering is disallowed

---

setup.py

In order to allow this application to be used as a library, dependencies need to be defined with setuptool in `install_requires`.
Then I read `server/requirements.txt` and set the content (except urls) in `install_requires`.
Regarding urls, it would be nice at the end to use only packages registered on Pypi.

Server: dependencies defined in setup.py

---

server/publicapi/features/items.feature
server/publicapi/items/service.py
server/publicapi/settings.py
server/publicapi/tests/items_service_test.py

NOTE: the HATEOAS `_links` object is left intact.
Resolves [SD-2241](https://dev.sourcefabric.org/browse/SD-2241).

Public API: remove non-NINJS content fields from fetched items/packages

---

client/app/styles/less/modals.less

I removed these lines to fix this issue we have on Liveblog:

modals.less: style issue with flex positioning fixed

---

client/bower.json
docker-compose.yml

it runs in dev mode, including livereload, via docker.
if you have docker-compose installed, you can test this via:
```
$ docker-compose build
$ docker-compose up
```
to create admin user, while having it up, run:
```
$ docker-compose run backend python3 manage.py users:create ...
```
client is on localhost:9000, server on localhost:5000/api
let me know if this works for anyone..
fyi bower.json is back in client (and kept in root) because you can't add/copy symlink in dockerfile

feat(docker): add docker compose config for development

---

server/publicapi/items/service.py
server/publicapi/tests/items_service_test.py

I added a word "valid" to the error message to make it more clear that a date like 2015-04-31 is rejected not because of its format, but because it is does not represent a _valid_ date (due to the incorrect number of days in this case).

public API: slightly improve the invalid date error message

---

docker/.gitignore
docker/container_build.sh
docker/docker-compose.yml

that needed to ease inheritance of this doker-compose config from sd-dev docker-compose config (not to repeat all the settings there and not change them in both places every time)
after this PR will be merged changes should be made in stash `qa/superdesk-deploy` repo

chore(docker): remove hack for liveblog

---

server/settings.py

it's using too much memory atm which makes oom-killer stop either mongo or
elasticsearch when running this.

fix(storage): disable task to check consistency

---

server/superdesk/io/rss.py
server/superdesk/io/rss_test.py

Resolves [SD-2484](https://dev.sourcefabric.org/browse/SD-2482).
NOTE: For some reason I was not able to see any ingested content under the CONTENT tab in my local Superdesk instance, but when debugging the ingest process, it seemed to me that items _have_ been ingested successfully.
For example, peeking into the _all_items_ list [here](https://github.com/superdesk/superdesk/blob/master/server/superdesk/io/commands/update_ingest.py#L320) showed that all items' `state` attribute was set to `'ingested'`, there were no errors, the images have been successfully downloaded (was able to fetch them via the local URL, e.g. `http://localhost:5000/api/upload/.../raw?_schema=http`) etc.

Add suport for ingesting images linked in RSS entries

---

docker/docker-compose.yml
server/publicapi/tests/items_service_test.py
server/settings.py

it was missing config with prefix which works fine on localhost,
but not when mongo is running in a container

fix(docker): fix unittests for publicapi in docker

---

client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/views/desk-config-modal.html

Issues fixed:
1. No message is shown indicating why the desk containing sages has not been deleted. There can be no desk without a stage as incoming stage is mandatory. Originally, as per the requirement user should be able to delete if the desk doesn't have any content.
2. When there are more users in the system and desk as well the system takes time in loading the list. While loading if user clicks on Next the system will send request payload as members: [] resulting in 0 members in the desk although there were users in the desk initially. Same case can occur in case of stages as well.

(fix) [SD-2542]

---

server/superdesk/io/rss.py
server/superdesk/io/rss_test.py

It turned out that RSS packages lacked metadata and were filtered out because they were recognized as expired, and they also lacked the `guid` attribute. This PR fixes that.

Add more metadata to RSS-ingested package (versioncreated, guid, etc.)

---

server/app.py
server/superdesk/io/aap.py
server/superdesk/io/afp.py
server/superdesk/io/dpa.py
server/superdesk/io/email.py
server/superdesk/io/ftp.py
server/superdesk/io/ingest_service.py
server/superdesk/io/ingest_service_tests.py
server/superdesk/io/reuters.py
server/superdesk/io/reuters_tests.py
server/superdesk/io/rss.py
server/superdesk/io/teletype.py

This is now handled by a metaclass, which also checks across all ingest classes for any duplicate `PROVIDER˙ names defined. The behavior of this metaclass is described in more details in its docstring.
Resolves [SD 2535](https://dev.sourcefabric.org/browse/SD-2535).

Automate the registration of the ingest classes as providers

---

server/superdesk/tests.py

on bamboo there is no db on localhost, it's configured via environment.
refactored #804 
@sivakuna-aap

fix(bamboo): use environment for db config

---

server/superdesk/tests.py

it's only for test setup so no info should be visible in production.
previous commit didn't fix the issue..

test(bamboo): show mongo config in case test fails to connect

---

client/app/scripts/superdesk-authoring/authoring.js
server/apps/tasks.py

Fixed:
1. Avoiding API Call to archive when there are no updates
2. When article is submitted to a desk the version is incremented but the version isn't inserted into archive_versions

(fix) Fixed Issues related to Tasks

---

client/.jshintrc
client/app/scripts/superdesk-ingest/ingest.spec.js
client/app/scripts/superdesk-ingest/module.js

As @sivakuna-aap explained in the chat, fetching ingested items to the `'personal'` desk is not allowed. This PR removes the "Fetch" and "Fetch As..." action buttons from the ingested items listed on the search results pane.
Resolves [SD-2601](https://dev.sourcefabric.org/browse/SD-2601).

Do not show Fetch buttons in search results if current desk is 'personal'

---

client/.eslintignore
client/.eslintrc

so far there are too many errors to enable it,
but at some point it could replace jshint+jscs

chore(ci): add eslint config for client

---

server/publicapi/demo_data/data.json
server/publicapi/items/service.py
server/publicapi/packages/service.py
server/publicapi/tests/items_service_test.py
server/publicapi/tests/packages_service_test.py

Resolves [SD-2720](https://dev.sourcefabric.org/browse/SD-2720).
Things changed:
* Change demo data so that composite items only contain references to associated objects and not the objects themselves.
* Fix an issue with `uri` field generation for associated objects.
* Add/update docstrings, add quite a few tests that were missing.

Fix fetching packages from public API using demo data

---

client/app/scripts/superdesk-authoring/metadata/metadata.js
client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html
client/app/scripts/superdesk-authoring/views/header-info.html
client/app/scripts/superdesk-publish/filters/view/production-test-view.html
server/apps/publish/archive_publish.py
server/apps/publish/archive_publish_tests.py

[SD-2633] ANPA Category and Targeted For was overwritten. ANPA Category should be multiple.
[SD-2730] Problems with correcting published items that have non-empty "Targeted For" field.
production-test-view.html was referring to anpa-category which is renamed to anpa_category

(fix) [SD-2633] [SD-2730]

---

server/apps/publish/archive_publish.py
server/apps/publish/archive_publish_tests.py

Fails to filter Subscribers when "Geographical Restrictions" and "Target For" values are different. For ex, a article which has "Victoria" as "Targeted For" is being transmitted to Subscribers with Geographical Restrictions as "Queensland", which shouldn't be case as the article is targeted for Victoria Subscribers only.

(fix) [SD-2573] 

---

server/apps/archive/__init__.py
server/apps/content.py
server/apps/packages/takes_package_service.py
server/apps/publish/__init__.py
server/apps/publish/archive_publish.py
server/features/content_publish.feature
server/superdesk/publish/publicapi.py

- If wire: the subsequent publishes should go to the same subscribers
- If digital: the subsequent publishes should go at least to the same subscribers

[SD-2750] Takes Publishing

---

client/app/scripts/superdesk/auth/session-service.js
client/app/scripts/superdesk/auth/session-service_spec.js
client/app/scripts/superdesk/menu/views/superdesk-view.html
client/app/scripts/superdesk/services/preferencesService.js
client/app/scripts/superdesk/services/preferences_spec.js

it stops using storage as user preferences cache altogether,
because after making a change storage prefs were not complete
and on page reload it would result in empty privileges.

fix(menu): fix case when privileges are not in storage

---

client/app/scripts/superdesk-packaging/packaging.js
client/app/scripts/superdesk-packaging/views/sd-package-item-preview.html
server/superdesk/io/rss.py
server/superdesk/io/rss_test.py

Resolves [SD-2581](https://dev.sourcefabric.org/browse/SD-2581).
The preview template seemed to display an incorrect object - some `item` way up the scope hierarchy, instead of `data`, the actual item contained in a package fetched from the server.
I also removed one-time bindings at a few places that were causing incorrect behavior, e.g. picture preview not shown etc.

Fix package preview in the sidebar.

---

client/app/scripts/superdesk/directives/sdSlider.js
client/app/styles/less/forms.less

https://github.com/superdesk/superdesk/pull/877
According to @petrjasek comment, updated sdSlider and removed `replace`.

fix (slider replace): Removed replace from sd slider, because it is deprecated

---

client/app/scripts/superdesk/auth/session-service.js
client/app/scripts/superdesk/services/preferencesService.js

it should keep promises around until user authenticates. and only
reset preferences if user was already authenticated and then lost
token.
SD-2768

fix(preferences): make sure we have identity before loading

---

server/requirements.txt

there is a fork now on pypi - hachoir3-superdesk

chore(server): use pypi to install hachoir

---

server/publicapi/items/service.py
server/publicapi/tests/items_service_test.py

Although useful, the "filter" parameter is not (yet) ready for a production use - we would need to implement at least the parameter syntax validation, make sure it is not tied to a specific backend and probably also limit its features (we might not want to give users the full filtering power the backend provides).
Since this filtering functionality is not required for the API v1 and would require non-trivial amount of additional work, we removed it for now.
Resolves [SD-2859](https://dev.sourcefabric.org/browse/SD-2859).
P.S.: I also did a minor optimization of checking the allowed parameters along the way (used `set` instead of a `tuple`).

Remove the "filter" parameter from Content API

---

server/app.py
server/apps/aap_mm/service.py
server/apps/archive/archive.py
server/apps/archive/archive_media.py
server/apps/archive/archive_rewrite.py
server/apps/archive/archive_spike.py
server/apps/archive/common.py
server/apps/duplication/archive_fetch.py
server/apps/duplication/archive_move.py
server/apps/packages/takes_package_service.py
server/apps/publish/archive_publish.py
server/apps/publish/archive_publish_tests.py
server/apps/tasks.py
server/superdesk/metadata/item.py
server/superdesk/workflow.py

This improvement extracts the values of item state to a Named Tuple and moves `config.CONTENT_STATE` to `ITEM_STATE`.
Reason for moving `config.CONTENT_STATE` is, few modules doesn't need context and those modules fail to get the key from config.
This improvement doesn't replaces the string literals across all the modules. At the project level it will be implemented as part of [SD-2856](https://dev.sourcefabric.org/browse/SD-2856).

(imp) Extracted item state to namedtuple and constant

---

client/app/scripts/superdesk-authoring/editor/find-replace.js
client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/editor.spec.js
client/app/scripts/superdesk/editor/spellcheck/spellcheck.js
client/app/scripts/superdesk/editor/spellcheck/spellcheck.spec.js
client/spec/authoring_spec.js
client/spec/helpers/authoring.js

instead of kind of stand alone those functions are now integrated
in the editor, so you can switch between those.
you can trigger those via editor service on all registered scopes.
instead of using input event it's now using keydown/up to detect
changes on items which can be only triggered by user.
SD-2793

refactor(editor): integrate findreplace and spellcheck

---

client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-search/search.js
client/app/scripts/superdesk-search/views/multi-action-bar.html
client/spec/helpers/monitoring.js
client/spec/monitoring_spec.js

SD-2873
Dynamic spike/unspike and duplicate for items in monitoring and spike
SD-2830
The screen does not reload on spiking multiple selection of items

SD-2873, SD-2830 fixed item list refresh on item spike/unspike

---

client/app/scripts/superdesk-authoring/metadata/metadata.js
client/app/scripts/superdesk-search/search.js
client/app/scripts/superdesk-search/tests/search_spec.js

Resolves [SD-2797](https://dev.sourcefabric.org/browse/SD-2797).
This PR includes the following:
* Fix the console error on the Search page if a desk is not found in desk lookup (this can happen if there are inconsistencies between Mongo and Elastic),
* Small fix in the `MetadataListEditingDirective` (potential error if the `items` Array is empty),
* Rewrite an `if` statement in `sdSearchFacets` directive's `items` change handler to outdent the function body for better readability (the indentation level was already pretty high).

Fix an error in console on "Search" page if a desk in not found in lookup

---

client/app/scripts/superdesk-packaging/views/sd-package-item-preview.html

Resolves [SD-3029](https://dev.sourcefabric.org/browse/SD-3029).
I also replaced some tabs with spaces (to fix the indentation), sorry for a bit less readable diff.
**Note:** No tests for this one, because the European team will soon start refactoring this (as per @akintolga) and the template, links, etc. are very likely to change in the process. We thus viewed this more as a light fix.

Fix links for viewing a contained item/package in the package preview side bar

---

server/superdesk/commands/clean_images.py
server/superdesk/io/commands/remove_expired_content.py
server/superdesk/io/commands/update_ingest_tests.py

It seems that the clean images routine was broken.
Also the images are not getting purged as the cursor had been traversed already when attempting to construct the list of file id's

[SD-3031] Removal of images when expiring from ingest

---

client/app/scripts/superdesk-authoring/tests/authoring_spec.js
client/app/scripts/superdesk-authoring/workqueue/tests/workqueue_spec.js
client/app/scripts/superdesk-desks/tests/desks-spec.js
client/app/scripts/superdesk-ingest/ingest.spec.js
client/app/scripts/superdesk-publish/tests/publish_spec.js
client/app/scripts/superdesk-search/tests/tags_spec.js
client/app/scripts/superdesk-templates/templates.spec.js
client/app/scripts/superdesk/itemList/itemList_spec.js
client/app/scripts/superdesk/notification/tests/notification_spec.js

Not sure if loading the `'templates'` module could be done at a single central place, suggestions welcome, but at least this fixes the tests in builds, allowing us to merge the PRs again.

Fix unit tests failing because of the unexpected GET .../workspace.html

---

server/apps/aap_mm/aap_mm_datalayer.py

The idea of serving aap images and videos from the AAP DC system is defunct, this pull request removes the additional link from renditions.

fix(aap image) remove the link to the aap one system in renditions

---

server/apps/io/update_ingest_tests.py
server/requirements.txt

This PR is dependent on superdesk/superdesk-core#5

(refactor) Modified ingest expiry to use the 'expiry' field to expire items.

---

client/app/scripts/superdesk-archive/module.js
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-monitoring/monitoring.spec.js
server/apps/duplication/archive_duplication.py

it was not updating list, not it sends a singal with desk/stage
ids and groups in monitoring listen to it and refresh itself if
appropriate
SD-2883

fix(monitoring): fix duplicate action not doing anything

---

client/app/scripts/superdesk/superdesk.js

once user logs in and preferences promise is resolved we're updating
routes to disable those that should not be available because of
permissions or beta flag. to make sure route reload is triggered only
after it's called via `$applyAsync`.

fix(loading): reload route in next digest

---

server/apps/aap_mm/aap_mm_datalayer.py
server/requirements.txt

https://github.com/superdesk/superdesk-core/pull/9
This only affects the AWS storage.  
Maybe change the code https://github.com/superdesk/superdesk/blob/master/server/apps/storage/amazon/amazon_media_storage.py#L118
`self.client.put_object(Key=filename, Body=content, Bucket=self.container_name,
ContentType=content_type, Metadata=None)`

(fix) Fixing the problem of AWS Storage 'Metadata too Large' exception.

---

client/app/scripts/superdesk-desks/desks.js
server/apps/stages.py
server/features/stages.feature

- Report delete validation exceptions on UI
- Allow stages to be deleted even if they have spiked items (unspike will revert them to the incoming stage, this was existing behavior)
- Implement a validation check on any ingest routing schemes referencing the stage

[SD-2540] Validation on stage delete

---

server/apps/archive/archive.py
server/apps/archive/common.py
server/apps/templates/content_templates.py
server/apps/templates/content_templates_test.py

which was failing after first run, because it was using id from
template for item. now this field is removed.
SD-2099

fix(templates): fix template auto creation

---

client/app/scripts/superdesk-archive/controllers/list.js
client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-monitoring/monitoring.spec.js
client/protractor-conf.js
server/apps/archive/archive.py
server/apps/archive/common.py
server/apps/auth/__init__.py
server/apps/content/__init__.py
server/apps/content/content_tests.py
server/apps/duplication/archive_move.py

there is single event `content:update` with info about item, desk
and stage which client can use to figure out what to update in monitoring.
SD-3204 SD-3213

fix(monitoring): refresh monitoring on content changes

---

client/app/scripts/superdesk-archive/views/metadata-view.html
client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-packaging/packaging.js
client/spec/content_spec.js
client/spec/helpers/content.js
server/apps/archive/archive.py
server/apps/publish/archive_publish.py
server/features/embargo.feature

1. [SD-3252](https://dev.sourcefabric.org/browse/SD-3252) - Correct and kill are ineffective in embargo
2. [SD-3247](https://dev.sourcefabric.org/browse/SD-3247) - Add embargo values to metadata info
3. [SD-3254](https://dev.sourcefabric.org/browse/SD-3254) - A duplicate of an embargo carries the same state color
4. [SD-3255](https://dev.sourcefabric.org/browse/SD-3255) - Inconsistency in color when choosing items for a package [embargo]

(imp) (fix) Embargo Related

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-packaging/packaging.js
client/app/scripts/superdesk-packaging/packaging.spec.js

in case you have the lock for an item you can not open it readonly.
so in such case it will now try to open it in edit mode.
SD-3167

fix(packaging): fix open item link in package

---

server/apps/archive/__init__.py
server/apps/archive/archive.py
server/apps/archive/archive_test.py
server/apps/archive/commands.py
server/apps/publish/commands.py
server/settings.py

This issue happens when:
- There is no queue entries for an scheduled item so a transmission never takes place so the item always stays in "scheduled" state.
- A text story is scheduled but wire clients didn't get the text but digital clients did get the take pckg. So text version of the story always stays in "scheduled" state.
This is a clean-up task to update the scheduled stories to "Published" once the "publish_schedule" field is overdue and the story is still in scheduled state. Even if there are problems in transmitting the story the state needs to change to "Published" as per users publish queue state doesn't matter much.

[SD-3236] - Scheduled items stay in "scheduled" state if they don't get queued

---

client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/styles/authoring.less
client/app/scripts/superdesk-authoring/views/send-item.html
client/app/scripts/superdesk-ingest/module.js
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-monitoring/styles/monitoring.less
client/app/scripts/superdesk-monitoring/views/monitoring-view.html
client/app/scripts/superdesk-search/views/multi-action-bar.html
client/app/scripts/superdesk-search/views/search-results.html
client/spec/fetch_spec.js
client/spec/helpers/monitoring.js
client/spec/monitoring_spec.js

feat(monitoring): SD-3123 Added fetch as panel on monitoring view

---

client/app/scripts/superdesk-ingest/module.js
server/apps/archive/archive.py
server/apps/duplication/archive_fetch.py
server/apps/packages/package_service.py
server/apps/packages/takes_package_service.py
server/apps/publish/archive_publish_tests.py
server/requirements.txt

This wouldn't happen normally, there are few examples of packages coming from Reuters having Empty ResidRef fields in the groups in ingest collection. Handles this problem gracefully.

[SD-2472] - Error handling in fetching empty package

---

client/app/scripts/superdesk-workspace/views/workspace-dropdown.html

There was some cases when workspace name is empty. This is a fix for it.

fix(desk dropdown): Added Untitled for workspace where name is not specified

---

client/.eslintrc
client/app/scripts/superdesk-archive/module.js
client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/views/send-item.html
client/spec/content_spec.js
client/spec/helpers/authoring.js

1. [SD-3313](https://dev.sourcefabric.org/browse/SD-3313) Disable "send and continue" for embargo items. Also, modified send.fetchStage() to select the stage of the item instead of selecting Incoming Stage always.
2. [SD-3311](https://dev.sourcefabric.org/browse/SD-3311) Update function is not working
3. Fixed the button Label is being displayed as "Save and Edit" when user tries to publish an item without saving changes.

Fixed Issues

---

client/spec/highlights_spec.js
server/apps/common/models/io/base_proxy.py
server/apps/common/models/io/base_proxy_tests.py
server/apps/item_lock/components/item_lock.py

when item is saved it gets populated, but before it's not set
and unlocking it fails with KeyError. there is also some bc fix
for items using objectId and not uuid

fix(lock): fix unlocking of auto generated items

---

client/app/scripts/superdesk-desks/aggregate.js
client/app/scripts/superdesk-monitoring/styles/monitoring.less
client/app/scripts/superdesk-monitoring/views/monitoring-view.html
client/app/scripts/superdesk-search/views/multi-action-bar.html
client/app/styles/less/layouts.less
client/app/styles/less/sf-additional.less

SD-2094
And couple of small fixes that I saw and there is no issue for that:
- On monitoring sorting with searching looks is fixed
- User management looks fixed
- Settings dropdown shown only on monitoring, on other pages not visible (3 dots)
- On monitoring on filtering by filetype checked items are unchecked

Fix (multiedit disabled for spiked items)

---

client/app/index.html
client/app/scripts/superdesk-vocabularies/styles/vocabularies.less
client/app/scripts/superdesk-vocabularies/tests/vocabularies.spec.js
client/app/scripts/superdesk-vocabularies/views/settings.html
client/app/scripts/superdesk-vocabularies/views/vocabulary-config-modal.html
client/app/scripts/superdesk-vocabularies/views/vocabulary-config.html
client/app/scripts/superdesk-vocabularies/vocabularies.js
client/spec/monitoring_spec.js
client/tasks/options/watch.js
client/test-main.js
server/apps/prepopulate/data_initialization/roles.json
server/apps/vocabularies/vocabularies.py

feat: vocabularies' settings

---

client/.eslintrc
client/.jshintrc
client/app/scripts/superdesk-desks/views/actionpicker.html
client/spec/helpers/pages.js
client/spec/helpers/utils.js
client/spec/ingest_settings_spec.js

Resolves [SD-2348](https://dev.sourcefabric.org/browse/SD-2348).
This fix simply adds a blank option to all relevant dropdown lists. On top of that, it uses `ng-options` instead of `ng-repeat` to create their options, improving the speed and reducing the memory usage (because `ng-repeat` creates a new scope for every element in the collection, but `ng-options` does not).

Fix: unable to deselect a macro in routing scheme rule w/o reloading th page

---

client/app/scripts/superdesk/services/preferencesService.js
client/app/scripts/superdesk/services/preferences_spec.js

in case fetching preferences fails with auth error it will try
to refetch those using old session id, but that does not exist
anymore.. so now on 404 it will fetch again using new session id.

fix(preferences): reload preferences on session expiry

---

client/app/scripts/superdesk-authoring/metadata/metadata.js
client/app/scripts/superdesk-authoring/views/article-edit.html
client/app/scripts/superdesk/filters.js

1. Values for all the options in Dateline Day are same. Because of this, the selected day is always the last day in the month although the current date is before last day of the month.
2. Timezone of a city selected from locators vocabulary is overwritten by UTC timezone by onblur event of the directive.

(fix) Dateline

---

client/spec/authoring_spec.js
client/spec/helpers/highlights.js
client/spec/helpers/monitoring.js
client/spec/helpers/search.js
client/spec/helpers/workspace.js
client/spec/highlights_spec.js

Rewrite tests in order to use monitoring view instead content view
Compose tests in larger suites in order to reduce the number of database
reset and prepopulation

chore(e2e): Refactor highlights e2e tests

---

client/app/scripts/superdesk-authoring/metadata/metadata.js
client/app/scripts/superdesk-authoring/metadata/views/metadata-widget.html
client/app/scripts/superdesk-authoring/metadata/views/metadata-words-list.html
client/app/scripts/superdesk-vocabularies/styles/vocabularies.less
client/app/scripts/superdesk-vocabularies/tests/vocabularies.spec.js
client/app/scripts/superdesk-vocabularies/views/vocabulary-config-modal.html
client/app/scripts/superdesk-vocabularies/views/vocabulary-config.html
client/app/scripts/superdesk-vocabularies/vocabularies.js
server/apps/prepopulate/app_prepopulate_data.json
server/apps/prepopulate/data_initialization/vocabularies.json
server/features/steps/fixtures/vocabularies.json
server/features/vocabularies.feature
server/requirements.txt

1. [SD-3183](https://dev.sourcefabric.org/browse/SD-3183) Using keywords as labels to group content arbitrarily
2. Adding following features to Vocabularies:
1. Adding "type" to each vocabulary which defines whether a vocabulary is system driven or manageable by user.
2. Adding "display_name" to each vocabulary which is used in UI.
3. Vocabulary UI displays only manageable type vocabularies
4. Vocabulary UI displays both active and inactive vocabularies
3. Fixed the below issues in Vocabularies UI:
1. Updating a vocabulary item removes is_active flag from collection
2. No vocabulary should be allowed to delete as it might have been used in transactional data. So replaced delete with sd-switch
Requires https://github.com/superdesk/superdesk-core/pull/35
1. Underlying structure of …

(feat & imp) SD-3183 and Vocabulary UI Improvements

---

client/app/scripts/superdesk-dashboard/world-clock/tests/WorldClockConfigController_spec.js
client/app/scripts/superdesk-dashboard/world-clock/tests/WorldClockController_spec.js
client/app/scripts/superdesk-dashboard/world-clock/tests/tzdata_spec.js
client/app/scripts/superdesk-dashboard/world-clock/world-clock.js
client/app/scripts/superdesk-ingest/ingest.spec.js
client/app/scripts/superdesk-ingest/module.js
client/app/scripts/superdesk-ingest/styles/settings.less
client/app/scripts/superdesk-ingest/tests/sdIngestRoutingContent.spec.js
client/app/scripts/superdesk-ingest/views/settings/ingest-routing-schedule.html
client/app/scripts/superdesk/ui/tests/ui_spec.js
client/app/scripts/superdesk/ui/ui.js
client/app/scripts/superdesk/ui/views/sd-timepicker-alt.html
client/spec/dashboard_spec.js
client/spec/helpers/pages.js
client/spec/helpers/utils.js
client/spec/ingest_settings_spec.js
client/tasks/options/template.js
client/test-main.js
server/apps/rules/routing_rules.py
server/apps/rules/routing_rules_tests.py
server/features/routing_rules.feature

Resolves [SD-3350](https://dev.sourcefabric.org/browse/SD-3350).
This PR fixes various issues with ingest routing schedule, e.g.:
* `sdTimepickerAlt` can be optionally configured to *not* convert selected times to UTC in the client browser, avoiding problems when time zone settings on the client's machine differ from the server time zone.
* It is now possible to select the time zone of the times of day in a routing schedule rule. This avoids the trouble of defining a time interval in a local time zone that would span across two different days in UTC due to the time shift (the latter was pretty much impossible to define until now).
The default behavior of the directive is still the same, preserving the backward compatibility.
If no time zone is defined in the routing schedule, UTC is …

Fix handling different time zones in ingest routing schedule

---

client/app/scripts/superdesk-authoring/widgets/widgets.js
client/app/scripts/superdesk-workspace/workspace.js
client/spec/workspace_spec.js

Previous case: Widget is assigned to number by number in order field. Problem here is that in some cases same number is assigned for two widgets.
New case: Widget is assigned by index number from forEach loop. Also, widgets are first sorted by order.
Improvement for task: SD-3414

fix(authoring): Changed the way widget is assigned to number

---

server/apps/archive/common.py
server/apps/io/dpa.py
server/apps/io/reuters.py
server/macros/dpa_derive_dateline.py
server/macros/dpa_derive_dateline_test.py
server/macros/noise11_derive_metadata.py
server/macros/noise11_derive_metadata_test.py
server/macros/reuters_derive_dateline.py
server/macros/reuters_derive_dateline_test.py

The problem is that the datelines we receive from some of the ingest providers/parsers do not conform to what we want. 
I've implemented a couple of macros to try to sort them out, the macros can be called as part of routing or maybe when we re-factor the ingest it might be an idea to nominate a macro to call on ingest.
We can't implement this stuff in the parsers as the same parser may be used for different providers.

[SD-3386] Fixup datelines using macros

---

client/app/scripts/superdesk/auth/auth.js
client/app/scripts/superdesk/auth/session-service.js
client/app/scripts/superdesk/auth/session-service_spec.js
client/app/scripts/superdesk/notification/notification.js

[SD-3548](https://dev.sourcefabric.org/browse/SD-3548)
Close the websocket on session timeout or logout and open the websocket on login. This will stop the events getting fired on the client after session timeout or logout.

(fix) Modified code to intercept the login and logout to open/close websockets

---

server/apps/prepopulate/data_initialization/validators.json

Resolves:
[SD-3460](https://dev.sourcefabric.org/browse/SD-3460) Header length being appropriate still gives an error before publish
[SD-3513](https://dev.sourcefabric.org/browse/SD-3513) Cannot kill or correct video items. Also, added/modified validator definition for other content types.
**Information to Mergers**
After merging, please drop validators collection and recreate from the `validators.json` file.

(fix)  Added/Modified validator definition for other content types

---

server/apps/io/reuters.py
server/features/auto_routing.feature
server/requirements.txt

Requires superdesk/superdesk-core#65
It seems that the dateRange request to Reuters may return duplicated guids

(fix) Reuters ingest routing

---

client/app/scripts/superdesk-search/search.js
client/spec/search_spec.js
server/apps/prepopulate/app_prepopulate_data.json
server/features/search.feature
server/requirements.txt

Tests for slugline search.
Also allows search for things that have a / in them, say AC/DC in the headline.
The PR is dependent on superdesk/superdesk-core#71

Make search by slugline work

---

server/apps/archive/archive_link.py
server/features/content_link.feature

Resolves: [SD-3663](https://dev.sourcefabric.org/browse/SD-3663)

(fix) [SD-3663] Takes are being created in the default incoming stage instead of the working stage

---

client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/views/editor.html

When creating a story with a single paragraph (e.g. a SNAP) HTML P tags was not including in the resulting response.

Editor: when multiBlockEdition is true, wrap all blocks into paragraphs SDPA-49

---

server/apps/publish/content/common.py
server/apps/rules/routing_rules.py
server/features/auto_routing.feature
server/features/steps/steps.py
server/macros/update_to_pass_validation.py

It seems that if the publish happens due to a routing rule we do not get a version created in archive_versions, presumably due to the fact that the publish is not done under the eve context, this PR fixes that. (not in love with the solution, would be happy for alternative suggestions)
It also includes a macro that will truncate the headline, slugline and adds a dateline (bogus), this is to allow Reuters content to pass validation and successfully publish, in order for the functionality to be tested.

[SD-2450] Automatic routing to publish

---

client/app/scripts/superdesk/notification/notification.js

Websocket connection must be retried if there is an existing ws with the
readyState of CLOSED

LBSD-740 fix websocket reconnection

---

client/app/scripts/superdesk/editor/editor.js

Use the user-provided url instead of the embedly one because when this is an image tweet, the embedly url links to the image, instead of the tweet.

editor: fix issue for tweet with picture inside

---

server/apps/templates/content_templates.py
server/features/steps/steps.py
server/features/templates.feature

when creating an item from template generate first/version created fields
SD-3433

fix(templates): ignore template timestamps

---

client/app/styles/less/modals.less

when the text content was longer than the fixed width, the text was cut

modals: header height shouldn't be fixed

---

client/app/scripts/superdesk-desks/desks.js
client/app/scripts/superdesk-desks/views/desk-config-modal.html
client/spec/desks_spec.js
client/spec/helpers/desks.js
server/apps/archive/archive_spike.py
server/apps/archive/common.py
server/apps/desks.py
server/apps/prepopulate/data_initialization/desks.json
server/apps/publish/publish_content_tests.py
server/apps/publish/published_item.py
server/apps/stages.py
server/apps/tasks.py
server/apps/tasks_tests.py
server/features/archive.feature
server/features/content_spike.feature
server/features/embargo.feature
server/features/search.feature
server/features/steps/steps.py
server/features/tasks.feature
server/requirements.txt
server/settings.py

This PR involves following changes to Content Expiry:
- Removed SPIKE_EXPIRY_MINUTES. Spike expiry will be based on Content Expiry.
- Remove PUBLISHED_ITEM_MINUTES. Published Item Minutes will be base on Content Expiry.
- Modified Desk Settings for content expiry
- There will be following settings for content expiry.
- Content Expiry setting globally (in settings.py)
- Content Expiry setting on the desk
- Content Expiry setting on the stage.
- Order of Precedence of content expiry is:
- Stage Content Expiry
- Desk Content Expiry
- Global Content Expiry
The actual process to expire the content will be a separate PR.
To merge this changes run following commands on mongodb:
`db.desks.update({}, {$set: {'content_expiry': NumberInt(4320)}}, false, true);`
`db.desks.update({}, {$unset: …

[SD-3627] (fix) Refactoring of content expiry

---

client/app/scripts/superdesk-authoring/comments/comments.js
client/app/scripts/superdesk-authoring/comments/views/comments-widget.html
client/app/scripts/superdesk-monitoring/monitoring.js
client/app/scripts/superdesk-monitoring/monitoring.spec.js
client/app/scripts/superdesk-monitoring/styles/monitoring.less
client/app/scripts/superdesk-monitoring/views/desk-notifications.html
client/app/scripts/superdesk-monitoring/views/monitoring-group-header.html
client/app/scripts/superdesk-users/tests/users_spec.js
client/app/scripts/superdesk-users/users.js
client/app/scripts/superdesk-users/views/mentions-menu.html
client/app/scripts/superdesk-users/views/mentions.html
client/app/scripts/superdesk/menu/notifications/notifications.js
client/app/scripts/superdesk/menu/notifications/notifications_spec.js
client/app/scripts/superdesk/menu/notifications/views/notifications.html
client/app/scripts/superdesk/menu/views/menu.html
client/spec/helpers/authoring.js
client/spec/notifications_spec.js
server/apps/comments/comments.py
server/apps/comments/user_mentions.py
server/apps/prepopulate/app_prepopulate_data.json
server/features/aap_mm.feature
server/features/activity.feature
server/features/archive_comments.feature
server/features/environment.py
server/features/ingest_provider.feature
server/features/rule_sets.feature
server/features/steps/steps.py
server/requirements.txt

Desk Mention Changes:
- Desk names can be mentioned in the story comments
- Desk comment count will appear next to the desk/stage widget in monitoring (next to item count)
- Hover action will display the comments per that desk
- Users can open the story from the comment
- First user opening the story will acknowledge the message
Activity and Notification Changes:
- Two separate activities created for mentions: desk:mention and user:mention
- Normal users will get these notifications only
- Client doesn't poll the notifications anymore, desk and user mention messages are broadcasted to client
- Activity end point returns only the last 24h of data
When this is merged please clean the activities collection.

Desk mentions

---

client/app/scripts/superdesk-authoring/authoring.js
client/spec/authoring_spec.js
server/apps/prepopulate/app_prepopulate_data.json

[SD-3021],[SD-3743],[SD-3776] An empty text editor box returns empty markup causing grief for validation

---

client/app/scripts/superdesk-archive/related-item-widget/relatedItem.js
client/app/scripts/superdesk-authoring/comments/comments.js
client/app/scripts/superdesk-authoring/editor/find-replace.js
client/app/scripts/superdesk-authoring/macros/macros.js
client/app/scripts/superdesk-authoring/metadata/metadata.js
client/app/scripts/superdesk-authoring/metadata/metadata.less
client/app/scripts/superdesk-authoring/metadata/views/metadata-dropdown.html
client/app/scripts/superdesk-authoring/packages/packages.js
client/app/scripts/superdesk-authoring/versioning/versioning.js
client/app/scripts/superdesk-authoring/widgets/widgets.js
client/app/scripts/superdesk-monitoring/monitoring.js

Resolves:
[SD-3761](https://dev.sourcefabric.org/browse/SD-3761) Disable "find/replace" for killed items
[SD-3459](https://dev.sourcefabric.org/browse/SD-3459) Place field on authoring screen is editable when item is locked

(fix) [SD-3761] [SD-3459]

---

server/apps/archive/common.py

follow-up on https://github.com/superdesk/superdesk/pull/1510

refactor(server: apps: archive: common): use mongo instead of redis sequence for key generation

---

client/app/scripts/superdesk-archive/directives.js
client/app/scripts/superdesk-authoring/authoring.js
client/app/scripts/superdesk-authoring/tests/authoring_spec.js
client/app/scripts/superdesk-monitoring/monitoring.js
server/apps/item_lock/components/item_lock.py
server/apps/publish/content/common.py

Also covers PR https://github.com/superdesk/superdesk/pull/1541
Resolves: 
1. [SD-2097](https://dev.sourcefabric.org/browse/SD-2097): Locking issue when item is published/sent
2. [SD-3557](https://dev.sourcefabric.org/browse/SD-3557): Unusual behavior for published items in monitoring view
3. [SD-3497](https://dev.sourcefabric.org/browse/SD-3497): Unlock button present when opening items from desks where the user is not a member of
4. [SD-3546](https://dev.sourcefabric.org/browse/SD-3546): Unlock issue when accessing item created in custom workspace
5. [SD-3263](https://dev.sourcefabric.org/browse/SD-3263): Edit button should be present if item is unlocked by the lock holder

(fix) [SD-2097] Locking issue when item is published/sent

---

server/Procfile
server/settings.py

This PR separates tasks based as below:
- Expiry related tasks to expiry queue
- Publish related tasks to publish queue
- Legal Archive related tasks to legal queue
- Ingest related task and any other task will go to default queue
- Rest of the tasks to default queue

[SD-3627][SD-3196] Separating task to different queues.

---

client/app/scripts/superdesk-authoring/metadata/metadata.js

When user clicks on remove button on any of the selected term using sd-meta-terms directive, then it's being added back to the list. Because of this the same term appears more than once in the list. This issue is fixed now.

(fix) sd-meta-terms directive

---

server/apps/publish/content/common.py
server/features/takes_publish.feature

- If a take is corrected the last published take should be used as the metadata source
- After a correction of a take, digital file stays 'corrected' even if a new take is published

[SD-3885] - Takes package metadata and status fixes

---

server/apps/preferences.py
server/requirements.txt

This  is dependent  on https://github.com/superdesk/superdesk-core/pull/134.
We need to reload the page on revoking privileges and fetch the active privileges. Eve returns 304 if the `_updated` is not modified. Hence, raised an event to update the affected users and then reload the page.

[SD-2824] Update the user _updated when privileges are revoked

---

README.md
docker/container_build.sh
scripts/docker-local-create-user.sh
scripts/docker-local-demo.sh

Replaced `$(readlink -e $(dirname "$0"))` with `$(echo $(cd -P -- "$(dirname -- "$0")" && pwd -P))"` so we can run `scripts/docker-local-create-user.sh` and `scripts/docker-local-demo.sh` on OSX. (readlink with -e param causes some issues on mac)
When running Superdesk on Docker from OSX, Docker Toolbox needs to be installed. I may create the install guide on how to install superdesk locally and on docker using OSX, but that will go into separate PR.

Update README.md & scripts

---

client/app/scripts/superdesk-authoring/styles/themes.less
client/app/scripts/superdesk/editor/add-embed.ctrl.js
client/app/scripts/superdesk/editor/editor.ctrl.js
client/app/scripts/superdesk/editor/editor.js
client/app/scripts/superdesk/editor/styles.less
client/app/scripts/superdesk/editor/views/editor.html
client/app/styles/less/buttons.less

Reverts superdesk/superdesk#1737
- Others text blocks paragraphs (except selected one) are split into new blocks
- Placeholders appear between each block, except around the selected block
- Remove and reorder block buttons disappear
- A link to exit the reorder mode appears
- the selected block moves to the chosen new position
- the following text blocks are merged
- the reordering mode closes
This PR already [get reviews](https://github.com/superdesk/superdesk/pull/1707). It is now waiting for PA feedback

Editor: reorder blocks

---

client/app/index.html

The one used localy is used for chaging labels

SDNTB-49 Add the genuine translation file

---

server/data/vocabularies.json

https://dev.sourcefabric.org/browse/SDPA-344
Image rendition names are used in the ninjs output. Using blank spaces breaks the spec.

Update image crop size names by removing blank spaces

---

server/data/validators.json

"description" was renamed to "description_text", so "description"
validator would always fail
SD-4162

fix(validators): update validators after schema change

---

server/data/vocabularies.json

https://dev.sourcefabric.org/browse/SDPA-340
Top 5 metadata field is not needed anymore.

Removes top 5 metadata field in favor of ranking

---

server/data/vocabularies.json

Because now order matters for default rendition, it's important to put a better resolution first

cv: thumbnail are no longer first in the renditions list

---

server/data/vocabularies.json

Related issue https://dev.sourcefabric.org/browse/SDPA-368
Mainstream updates to controlled vocabularies expect a `qcode` attribute instead of `value`

Replaces `values` attribute by `qcode`

---

client/app/translations.js

when https://github.com/superdesk/superdesk-client-core/pull/272 is
merged, the CATEGORY label will be changed to SERVICE( there is another
'Category' label in that header and it's confusing) so this is to make
sure that everything looks the same for AAP

SDNTB-135 Rename SERVICE back to CATEGORY

---

server/data/content_types.json

Service metadata needs to be listed here to show up now. It's all lumped together in each content type. I'm not sure of the ordering required. There doesn't exist a good way to make metadata marked for only a particular service to be required when needed.

Listing all cvs in content types to make sure they show up in PA.

---

client/app/index.html
client/package.json
server/requirements.txt

Depends on https://github.com/superdesk/superdesk-client-core/pull/273
`authoring.js` is too long, let's add new services to this file.

add authoring/services.js

---

client/app/index.html

this should be enable for aap, by default it's off
will make more sense once https://github.com/superdesk/superdesk-client-core/pull/337 is merged, but can be merged upfront

feat(workspace): enable ingest/content views

---

server/data/vocabularies.json

… Those renditions are not longer used
Related issue https://dev.sourcefabric.org/browse/SDPA-447

Removes 2x1 and 5x4 from the Image Crops Size controlled vocabulary

---

server/ntb/scanpix/scanpix_datalayer.py

There was a bad check, I've replaced it with a try/except which avoid
this kind of mistake and which is more pythonic
SDNTB-15

fixed description_text in Scanpix search result

---

.travis.yml

some test are presents (e.g.
server/pa/pa_img/pa_img_datalayer_tests.py) but nosetests was not run
in travis.

added nosetests to .travis.yml

---

server/settings.py

- category is now added to item['subject'] with a "category" scheme
- "genre_custom" scheme is now added to found subjects, which are also stored
in item['subject']
there is some code here (mainly add_subjects_scheme) which is not ideal in
settings, this is temporary and this should be moved in a separate
module (with a NITFFeedParser subclass) once SD-4650 is fixed.
SDNTB-213
SDNTB-219

Fixed metadata handling for NITF parser

---

server/ntb/scanpix/scanpix_datalayer.py

'all' subscription value is handled by removing the subscription filter.

[SDNTB-215] Change "subscriptions" in Scanpix search

---

server/ntb/scanpix/scanpix_datalayer.py

the former way of choosing rendition images was to do a best guest
based on actual rendition sizes in settings, and it was not settings
correclty all renditions keys.
As renditions sizes have little chance to change, the code was
simplified and Superdesk renditions to Scanpix preview mapping is now
done with a simple dict containing a list of preview to get in order of
preference.
SDNTB-210

[Scanpix] Simplified rendition images selection

---

server/ntb/tests/io/feed_parsers/nitf_tests.py
server/requirements.txt

Tests were broken due to changes in superdesk-core, needed for NTB.
SDNTB-219

Fixed test for NTB specific NITF parser

---

server/ntb/scanpix/scanpix_datalayer.py

Changes made for SDNTB-210 have caused a regression as video were not
visible anymore in editor.
This commit fix the issue by using mp4 preview if available for baseImage

[Scanpix] fixed video preview in editor

---

client/app/index.html
server/pa/vidible.py
server/pa/vidible_test.py
server/settings.py

- add in backend an endpoint to fetch Vidible video metadata
- define in frontend a special handler for Vidible embed code
requires https://github.com/superdesk/superdesk-client-core/pull/610
and https://github.com/superdesk/superdesk-core/pull/432 to be fully complete

Handles Vidible embed codes SDPA-454

---

server/ntb/scanpix/__init__.py

The 4 instances are hardcoded as it is currently not possible to set
dynamically search providers in frontend.
fix SDNTB-217

[scanpix] create 4 instances of Scanpix search provider

---

server/data/validators.json

If validators update is required for any instance. Please run the following command.
`app:initialize_data --entity-name=validators --file<location>`
where `location` points to the `validators.json file` in the folder `server/data`
This depends on https://github.com/superdesk/superdesk-client-core/pull/656

[SD-4838] (fix) Modified the headline maxlength validation to 42 characters.

---

server/ntb/scanpix/scanpix_datalayer.py

as requested by NTB (see linked ticket), "subscription" filter is
replaced by "punchcard" if set to "subscription" ("inside subscription"
in the frontend) only for ntbtema resource.
fix SDNTB-250

[scanpix] change subscription behaviour for ntbtema

---

server/ntb/scanpix/scanpix_datalayer.py

regex parsing queries was ignoring "*", but it is needed to handle
wildcards.
Also fixed a small docstring issue
fix SDNTB-240

[scanpix] allow "*" in text search

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

only "featureimage" was used, now "featuremedia" is checked too if
"featureimage" is not found
body_html was added to NITF's <body.content/> using the inherited
method from core's NITF Formatter, but this was not getting all the
elements.
To work around this, the inherited method is not used anymore, and
BeautifulSoup is used to transform the HTML to XML, which is then added
to body.content
This commit fixes the issues related in feedback of SDNTB-229 (in the
comments)

[NITF Formatter] fixed featuremedia and body_html handling

---

client/superdesk.config.js

config changes to specify previously hardcoded required media metadata fields.

chore(PA config): add default required media metatadata fields

---

client/superdesk.config.js

config changes to specify previously hardcoded required media metadata fields.

chore(NTB config): add default required media metatadata fields

---

server/ntb/publish/ntb_nitf.py
server/ntb/scanpix/scanpix_datalayer.py
server/ntb/tests/publish/ntb_nitf_test.py
server/requirements.txt

the following elements have been added:
- meta timestamp, ntb-dato, NTBUtDato, NTBStikkord, NTBBilderAntall, NTBDistribusjonsKode, NTBKanal, NTBID, NTBIPTCSequence, NTBEditor
- date.issue now follows NTB format
- added key-list/keyword in docdata
- added tagline/a in body.end
- added distributor/org in body.head
- added baselang in <nitf> root element
- doc-id follow new NTB specifications
following elements have been removed:
- NTBPrioritet
- date.expire
abstract in <p class="lead" lede="true"> element now use text with HTML
elements stripped.
if there is a paragraph in body_html using class="lead", it's changed
for "txt", and lede attribute is removed if it exists.
mime_type had default values of "image/jpeg" for images and
"video/mpeg" for videos.
date has been removed from …

[NITF] [formatter] added new elements

---

server/ntb/publish/__init__.py
server/ntb/publish/ntb_nitf.py
server/ntb/publish/ntb_publish_service.py
server/requirements.txt

<meta name='filename'> element is generated and used for actual
filename using the new PublishService refactoring in superdesk-core
SDNTB-264

[NITF] [formatter] filename generation

---

server/ntb/publish/ntb_nitf.py

"subject" meta element now uses the new specifications with a nyX-
prefix for article updates.
SDNTB-254

[NITF] [FORMATTER] use new specification for subject

---

docker/start.sh

Seems something changes and instead of `localhost` in app.bundle.js we have `0.0.0.0`.

Fix WebSocket url for dev.superdesk.org instances

---

client/package.json
server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

version doesn't seems to work as expected (it doesn't change after an
update), but _current_version do the job, so version as been replaced
by _current_version where it's needed
SDNTB-280

[NITF] [FORMATTER] use _current_version instead of version

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

formatting was failing when parent == None in place (i.e. with top-level
place), this commit fix it.
SDNTB-290

[NITF] [Formatter] fixed formatting of articles with top-level places

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

Following charaters only are allowed in filename: a-z, A-Z, 0-9, ".", "_" and "-", all others are replaced.
SDNTB-291

[NITF] [FORMATTER] replace forbidden characters by "-"

---

server/data/validators.json

Thanks to @petrjasek here is the fix.
This error appears when the "Image Crop Sizes" names are changed in the vocabulary and Superdesk still tries to validate renditions using the hardcoded renditions names.
Related ticket: https://dev.sourcefabric.org/browse/SD-5528

SD-5528 - Associated item <item_name>: RENDITIONS is a required field

---

DEVSETUP.md

It seems there are some link name error on guide. Could you review this change?

Update development setup guide

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

"_current_version" was used to determine version and update numbers, but
this metadata actually change which saved versions, not with publication version which is what is requested.
This commit change this to use "rewrite_sequence" which actually
correspond to the desired information.
fix SDNTB-303

[NTB] [FORMATTER] fixed version/update numbers

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py
server/requirements.txt

<p> element class is now set like this:
- "lead" is used for abstract
- "txt" for <p> immediately following <hl2>
- "txt-ind" in all other cases
SDNTB-304

[NITF] [FORMATTER] filter <p> elements to set NTB requested classes

---

server/ntb/publish/ntb_nitf.py
server/ntb/tests/publish/ntb_nitf_test.py

sign_off were splitted using " " (space), but a slash is actually used
in superdesk. This commit fix it, but it's not a proper solution as "/"
could be used in email addresses, so a new ticket has been opened
(SD-5546) and this is a temporary solution
SDNTB-305

[NITF] [FORMATTER] sign_off are now splitted with "/"

---

.dockerignore
Dockerfile
docker/start-dev.sh

it wasn't installing npm libs when using the volume,
thus missing all client dependencies

fix(docker): fix docker-compose-dev setup

---

README.md

I updated some typing error and elastic search version info. As @petrjasek commented in #2049, elasticsearch 2.x seems not support yet.

Update guide on README

---

.gitignore
server/ntb/scanpix/scanpix_datalayer.py
server/ntb/scanpix/scanpix_datalayer_tests.py

fixed date filters to use scanpix archived parameters and remove unnecessary extract_date function (http://api.scanpix.no/doc/ date - uses standard datetime format)

SDESK-200: FILTERS in advanced search do not work for Search Providers

---

server/ntb/scanpix/scanpix_datalayer.py

update scanpix datalayer to use archivedTime as versioncreated

SDESK-223: Scanpix search: Display archived-date in search results

---

server/ntb/tests/io/feed_parsers/nitf_tests.py
server/settings.py

abstract is taken from first paragraph (<p> element with class "lead")
of body.content, this was resulting in a duplicate abstract (in
abstract and in body_html).
This commit ignore <p> element with class "lead" when parsing
body.content to generate body_html.
SDNTB-312

[FEED PARSER] [NITF] remove abstract from body_html

---

client/package.json
server/requirements.txt

Uses superdesk-core 1.6.2 and superdesk-client-core 1.6.0

Updates qa branch to use latest available server and client

---

docker/docker-compose-services.yml

as it has been done in docker/common.yml

logstash and kibana removed from docker/docker-compose-services.yml

---

client/package.json
server/requirements.txt

temporarily needed to avoid a but introduced in commit 6150da3ad034d2e014d06c1f76f07677407d9808
This reverts commit beb0c250051816636f6f6f6d1a86054338e3ec00.

Revert "updated to v1.7rc1"

---

server/data/dictionaries.json

a field linking to a unexistant file was present in dictionaries
collection, resulting in bad behaviour when trying to modify the
dictionary in the settings.
SDTS-54

[DATA] removed _file_id from dictionaries

---

client/package.json
server/requirements.txt

It's time to update `gunicorn` and `honcho` too, new versions have been in use on `*.test.superdesk.org` instances and seems they are working pretty well.

Update cores, gunicorn and honcho

---

scripts/docker-local-create-user.sh
scripts/docker-local-demo.sh

In the `scripts` folder there are two scripts, `docker-local-demo.sh` and `docker-local-create-user.sh` that use a variable called `$SCRIPT_DIR`. When running these scripts, I ran into the following errors:
```shell
./scripts/docker-local-demo.sh: line 27: cd: /Users/nathan/Developer/Daily: No such file or directory
```
The location of the superdesk folder on my computer is `/Users/nathan/Developer/Daily Bruin/superdesk`. In order to have $SCRIPT_DIR support folders with whitespace, we need to wrap it in quotes when using it. [This Stack Exchange question](https://unix.stackexchange.com/questions/131766/why-does-my-shell-script-choke-on-whitespace-or-other-special-characters) explains the issue in more detail.
Note: this is my first PR, so please let me know if I'm doing everything …

Wrap $SCRIPT_DIR in quotes

---

README.md

There have been some troubleshooting sessions on Slack for helping people to install Superdesk on macOS. I have added extra notes and information into the README to hopefully make it easy for newcomers on macOS to install these requirements.

README: added macOS notes

---

client/superdesk.config.js

validatorMediaMetadata is now handled in server, so it has been removed
from client config.
SDFID-431

[CLIENT] removed validatorMediaMetadata from client config

---

docker/common.yml

Docker is now adding an unique id at the end of container names. This
patch set fixed names to containers, so they are more easy to manipulate.

[DOCKER] set names to containers

---

server/ansa/commands/remove_expired_media.py
server/ansa/remove_expired_media.py

to check if that binary is still in use and
keep it in such case. ansa uses md5 for media
so if same picture is used/uploaded/fetched multiple
times they all have same media id.
SDANSA-401

use media references before removing binary

---

client/package.json
client/superdesk.config.js
server/requirements.txt
server/settings.py

Optional Superdesk modules such as Planning, Analytics and Publisher should use separate branches from the Vanilla Superdesk builds

fix(build): Make master a vanilla Superdesk install

---

docker-compose.yml

Useful for devs:
```bash
$ docker-compose start redis
$ docker-compose start mongodb
$ docker-compose start elastic
$ docker-compose start superdesk-server
```

Expose ports from services and server in Dockerfile

---

README.md

- `compose` is now a sub-command of `docker`, so `docker compose` should be used instead of `docker-compose`.
- The initialization commands used `docker-compose run` which starts a new container, while at this point the container should be already running, so `exec` should be used instead.
- Removed erroneous `run` commands used before `python manage.py`.

Fix `docker compose` commands.
